Pipfile, Pipfile.lock, app/__init__.py
A couple bugs pop up when running behind gunicorn, so I fixed those
as well.
- Validate responses currently produces a bunch of errors. Disabled
that for now
- Set swagger_ui to False so we don't get that error
=> Add gunicorn dependency and fix a bug

manage.py, test_api.py
Removed some unused imports, remnants of templates and refactorings.
=> Remove unused imports

README.md, api/host.py, app/__init__.py, app/config.py, logconfig.ini, run.py
Modified the logging so that we can enable and disable logging in different parts of the application.  In other words, we can enable debug logging for the "api" and "app" parts of the application without enabling debug logging in flask, connexion, etc.
Added an environment variable (INVENTORY_LOGGING_CONFIG_FILE) that points to the logging configuration file.  This file can be shared with guicorn (gunicorn --log-config=$INVENTORY_LOGGING_CONFIG_FILE run).  This logging config file is used to "bootstrap" the logging configuration before the flask app is created.
This approach allows us to be able to configure the logging subsystem outside of the code.
=> Logging configuration changes

app/models.py, test_api.py, test_db_model.py
Adding more tests around resolving the display_name
=> Set the display_name to either the fqdn or id if the display_name is an empty string

README.md, api/host.py, app/__init__.py, app/auth/__init__.py, app/auth/identity.py, logconfig.ini, swagger/api.spec.yaml, test_api.py, test_unit.py
This PR contains only the authentication related changes related to the bulk insert.
This PR adds onto PR#127.
https://projects.engineering.redhat.com/browse/RHIPLAT1-825
=> Openapi 3 conversion bulk insert preshared key authn

README.md, api/host.py, app/__init__.py, app/auth/__init__.py, logconfig.ini, swagger/api.spec.yaml, test_api.py, test_unit.py
This PR depends on PR#125.  This removes the tag cruft from the api.
=> Openapi 3 conversion remove tags from api

README.md, api/host.py, app/__init__.py, app/auth/__init__.py, logconfig.ini, swagger/api.spec.yaml, test_api.py, test_unit.py
This PR changes the interface so that hosts can be created/updated in bulk.  This is a change to the POST /hosts method.
This PR depends on PR#126.
https://projects.engineering.redhat.com/browse/RHIPLAT1-826
=> Openapi 3 conversion bulk insert

README.md, api/json_validators.py, app/__init__.py, swagger/api.spec.yaml, test_api.py, test_json_validators.py
Perform more input validation on the hosts during the POST to /hosts.
=> Input validation

api/host.py
Extracted the _.paginate_ calls as well as the _logger.debug_ calls from the specific host find methods. They were all the same, while the methods are called from only a single place. [Moved](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:dry_get?expand=1#diff-a5c55b46cc9c536070cb56798c97adfaR167) these calls to the [_get_host_list_](https://github.com/RedHatInsights/insights-host-inventory/blob/581d9fea1cd40de0c88072fb9b131e74c659b932/api/host.py#L145) operation method.
Not only the code is more concise, but also saves two parameters from four methods.
=> DRY pagination and logging from find methods

api/host.py
=> Include the account number on the hostname_or_id query

app/utils.py
=> Fix HostWrapper so that it does not use a mutable object as a default value

api/host.py, app/models.py, test_db_model.py
Add a few more tests around the situation where system_profile_facts is None
=> Fixed an issue where the system profile is None

api/__init__.py, app/__init__.py, app/logging.py, test_unit.py
This allows the inventory service to log the request_id with each logstash log message without having to explicitly retrieve/pass around the request id for each log message.
=> Implemented contextual logging to log the request_id using a custom logging.Filter

app/logging.py
The logger used by the gunicorn arbiter ignores configuration from the logconfig.ini/--log-config.  This class is required so that the log messages emmitted by the arbiter are routed through the logstash formatter.  If they do not get routed through the logstash formatter, then kibana appears to ignore them.  This could cause us to lose "WORKER TIMEOUT" error messages, etc.
=> Adding a custom gunicorn logger so that all gunicorn error messages are output using the logstash formatter.

api/host.py
=> Include the account number on the hostname_or_id query (#148)

api/host.py
=> Use ujson to serialize the outgoing json data on create/update

app/models.py, test_api.py
https://github.com/RedHatInsights/insights-host-inventory/issues/176
=> Relax the validation performed on the yum repo base_url

Pipfile, Pipfile.lock, app/logging.py
* Add a watchtower logging adapter
* Read the openshift namespace from a file and use that as the logging stream name
* This works, but it needs to be be cleaned up
=> Add a watchtower logging adapter (#204)

app/__init__.py, tasks/__init__.py
Signed-off-by: Jesse Jaggars <jjaggars@redhat.com>
=> passing flask app context to task worker

README.md, app/__init__.py, app/config.py
When the INVENTORY_LEGACY_API_URL environment variable is set to something other than an empty string then that api path will be added.
=> Adding support for legacy api.

app/models.py, swagger/api.spec.yaml, test_api.py
This commit adds a new cloud provider string field to the system
profile.
=> Add `cloud_provider` to system profile

app/models.py, swagger/api.spec.yaml, test_api.py
=> Add the ability to set the display_name using a PATCH on /hosts

app/models.py, tasks/__init__.py, test_api.py
Missed a threadctx reference that needed to be removed
System profile is not updated on POST
=> Performance related changes - request_id logging fix, do not update system_profile on POST (#225)

api/metrics.py, tasks/__init__.py
Signed-off-by: Jesse Jaggars <jjaggars@redhat.com>
=> adding metrics for system profile processing (#231)

api/__init__.py, api/host.py, app/auth/__init__.py, app/auth/identity.py, app/config.py, app/logging.py, app/models.py, logconfig.ini, tasks/__init__.py
Add "inventory." as the logger prefix
Change the way the loggers are created
As usual, I'm not completely happy with this change (particularly the way i'm setting the account_number in the threadctx...its gross).  I tried to keep the amount of change as small as possible and still get the logging we want.
=> Change logger name prefix

Jenkinsfile-smoke.groovy
Same as #234 but re-doing this so I can merge with a rebase
=> Change marker used to run smoke tests

test_api.py
The [_CreateHostsWithSystemProfileTestCase.test_create_host_without_system_profile_then_update_with_system_profile_](https://github.com/RedHatInsights/insights-host-inventory/blob/643f2619a9563861861d29cdb1defe554c32edc8/test_api.py#L939) test was [marked](https://github.com/RedHatInsights/insights-host-inventory/blob/643f2619a9563861861d29cdb1defe554c32edc8/test_api.py#L938) as skipped, because system profile can be [no longer](https://github.com/RedHatInsights/insights-host-inventory/commit/04c652e862aa28216c7555dd71621b4ba52bf0cb) updated via the POST action. It is now [updated](https://github.com/RedHatInsights/insights-host-inventory/commit/ccf216ee6e81ad7ca4cbc97ac75ebe4ab2bea5a8) by a message picked from a Kafka message queue.
Amended the tests so it uses the message handler …
=> Fix update system profile test

api/host.py
=> Try to improve handling concurrent delete operations

README.md, api/host.py, api/metrics.py, app/__init__.py, app/config.py, app/events.py, dev.yml, logconfig.ini, swagger/api.spec.yaml, tasks/__init__.py, test_api.py, test_unit.py
- add delete hosts functionality
- various test improvements
=> Merge delete host functionality into stable

test_api.py, test_db_model.py
I broke the tests by adding the Indexes to the model.  This should resolve the issue with the tests (though this is an ugly hack).
=> Temporarily rename the indices in the tests

test_api.py
There are now more tests that check that error _404 Not Found_ is raised when _limit/offset_ parameters are out of bounds. This error has a custom message. Amended the tests so they check for this error message as well.
This is a result of merging both #216 and #240.
=> Test limit/offset 404 custom message

README.md, app/config.py
=> Fix an environment variable name in the README

app/config.py, app/logging.py, inv_mq_service.py, logconfig.ini, utils/kafka_producer.py
@dehort I confirmed that threadctx was working as expected and could see the request_id and account_number in the logstash message locally.
=> Getting app.logging wired into the new inv_mq_service

app/config.py
Minor tweak.  Just reorganized the db/kafka configuration log messages.
=> Config logging tweak

test_unit.py
Added tests for the _from_json_ and _to_json_ of the [_Host_](https://github.com/Glutexo/insights-host-inventory/blob/aa63af1c1314ee434ea7039a6bc5452c325f7d11/app/models.py#L30), [_CanonicalFacts_](https://github.com/Glutexo/insights-host-inventory/blob/aa63af1c1314ee434ea7039a6bc5452c325f7d11/app/models.py#L201)
and [_Facts_](https://github.com/Glutexo/insights-host-inventory/blob/aa63af1c1314ee434ea7039a6bc5452c325f7d11/app/models.py#L241) classes. For the Host methods there are two sets of tests: one that mocks the internal calls and one compound that tests these three models as a one unit.
This is a part of the host import/export extraction. The tests will allow to move around the code and verifying the logic has not been changed. Later the changes in the tests will describe the …
=>  Test host (de)serializaton

test_db_model.py, test_unit.py
I'm not sure what happened here.  I must have merged some code into the branch in the wrong order and broke something.
@Glutexo please take a look and make sure I didn't do anymore damage.  Also, there are some more tests failing.  I'd appreciate it if you can look at those.
=> Fix some tests that broke due to moving code around

api/host.py, host_dumper.py, test_db_model.py, test_unit.py
Fixed Flake8 issues related to hanging and visual indentation. With these changes I didn’t try to do it nicely or consistently, just to satisfy Flake8 in a way that Black wouldn’t change it either. 
This is a part of the first step towards cleaner code: fixing all Flake8 errors. See #331, #189 and #331.
=> Formatting: fix Flake8 indentation

app/queue/ingress.py, app/queue/metrics.py, inv_mq_service.py, lib/metrics.py
Initial commit. We can discuss other metrics we would like to add.
=> Adding prometheus metrics to inv_mq_service

api/__init__.py
This reverts commit 25f8d676c0363006cdc50854c212f9e60ab942bc.
The logging in CI is acting goofy.  I'm reverting my most recent change to see if that somehow broke it (i can't see how it would though).
=> Revert "Fix the status code logging"

api/__init__.py
This fix does not appear to be causing the logging issues I noticed previously.  This PR adds the fix back.
=> Fix the status code logging

.gitignore
I noticed that some uncommitted files were lingering after running the unit tests locally, so I made some minor updates to `.gitignore`.
=> Some additional gitignore entries for data generated by pytest

README.md, api/host.py, app/models.py, app/queue/egress.py, app/queue/ingress.py, app/queue/metrics.py, app/serialization.py, inv_mq_service.py, lib/host_repository.py, test_unit.py, utils/kafka_consumer.py, utils/kafka_producer.py
Fix all pre-commit hooks violations introduced in the [_split_inventory_service_](https://github.com/RedHatInsights/insights-host-inventory/tree/split_inventory_service) branch. This will allow to use the pre-commit hooks when working on this branch.
=> Fix pre-commit violations

Makefile, utils/kafka_producer.py, utils/payloads.py, utils/rest_producer.py
Script that lets you send a bunch of messages to the rest interface just like you would with the kafka script (makefile target / edit number of messages within the script)
=> Adding a simple script to hit the rest interface

utils/kafka_producer.py
Ignore the branch title.. left 180k hosts in the mq testing script. Probably just want to stick to default. 
@dehort
=> Left in 180000 hosts as default..

utils/kafka_consumer.py, utils/kafka_producer.py
Reordered imports so they are listed in a standard way. Split multiple imports to single lines.
=> Reorder imports

README.md, api/host.py, app/events.py, app/models.py, test_api.py
https://projects.engineering.redhat.com/browse/RHCLOUD-1995  https://projects.engineering.redhat.com/browse/RHCLOUD-1561
=> RHCLOUD-1995 and RHCLOUD-1561

app/events.py
Removed validations from HostEvent(Schema).
=> Removed Validations

api/host.py
Updated the race condition catch and added additional comments to explain the operation.  See RHCLOUD-2219 for additional information on the changes made.
(https://projects.engineering.redhat.com/browse/RHCLOUD-2219)
=> Updated race condition catch

app/models.py, lib/host_repository.py
Adding db_context_manager to handle db disconnects
=> updating the event handler to handle db disconnects

swagger/api.spec.yaml, test_api.py
Added branch_id and unit tests to Post, Delete, Patch, Put and Get.  
See:  https://projects.engineering.redhat.com/browse/RHCLOUD-1611
=> Added branch_id and unit tests to each API method

Jenkinsfile, README.md, api/host.py, app/__init__.py, app/config.py, app/events.py, app/payload_tracker/__init__.py, app/payload_tracker/metrics.py, app/serialization.py, run.py, swagger/api.spec.yaml, tasks/__init__.py, test_api.py, test_payload_tracker.py, test_unit.py
This includes payload tracker changes, delete changes, branch_id changes.
=> Merge master into split_inventory_service branch

Makefile, app/queue/ingress.py, inv_mq_service.py
=> Payload tracker integration with the MQ service

test_api.py
I have created an automatic test for the ObjectDeletedError catch.  Please note that this will probably have to be changed quite a bit as more changes are made to this error catch.
=> created test for current race condition catch.

test_api.py
Created more test cases for the automatic race condition tests focused on the status codes returned in a series of scenarios.  See https://projects.engineering.redhat.com/browse/RHCLOUD-2222 for more details.
=> Created tests for status codes

Jenkinsfile, Makefile, README.md, api/host.py, app/__init__.py, app/config.py, app/events.py, app/models.py, app/payload_tracker/__init__.py, app/payload_tracker/metrics.py, app/queue/ingress.py, app/queue/metrics.py, app/serialization.py, inv_mq_service.py, lib/host_repository.py, run.py, swagger/api.spec.yaml, tasks/__init__.py, test_api.py, test_payload_tracker.py, test_unit.py, utils/kafka_producer.py, utils/payloads.py, utils/rest_producer.py
RHCLOUD-2113 - mq service thread does not recover after database server failure
RHCLOUD-1904 - payload tracker integration with mq service
=> Move RHCLOUD-2113 and RHCLOUD-1904 to QA

app/models.py, app/utils.py, test_db_model.py
Moving this PR from master to tagging branch
=> Basic changes needed to get tags back into the db.

README.md
2 minor changes:
1. add small blurb to README about using pyenv to manage multiple py versions
2. add vscode dir to gitignore
=> DOC: update README and gitignore

test_api.py
Added the additional request_id test and query.all() in host.py.
=> Added request_id test

test_api.py
Moved _datetime_ [return value](https://github.com/Glutexo/insights-host-inventory/blob/53f215846fe93eb46aaf6bcea8d8d10f3abb001b/app/events.py#L27) [patch](https://github.com/RedHatInsights/insights-host-inventory/blob/b0308b020de7c3f5b046a5f971f7aac7280f98cb/test_api.py#L1279) to the shared [__delete_](https://github.com/Glutexo/insights-host-inventory/blob/53f215846fe93eb46aaf6bcea8d8d10f3abb001b/test_api.py#L1291) method and the [timestamp](https://github.com/Glutexo/insights-host-inventory/blob/53f215846fe93eb46aaf6bcea8d8d10f3abb001b/test_api.py#L1289) to [_setUp_](https://github.com/Glutexo/insights-host-inventory/blob/53f215846fe93eb46aaf6bcea8d8d10f3abb001b/test_api.py#L1287). That gets us rid of passing around the timestamp and digging it out of the mock.
This is a follow-up to …
=> Request ID tests: extract datetime patching to setUp

test_api.py
Simplify [tests](https://github.com/Glutexo/insights-host-inventory/blob/7c07e77bf6792acd9f077efeb4a18835bbb45e2b/test_api.py#L1280) by leveraging the [_setUp_](https://github.com/Glutexo/insights-host-inventory/blob/7c07e77bf6792acd9f077efeb4a18835bbb45e2b/test_api.py#L1288) method. Extracted the [host ID](https://github.com/Glutexo/insights-host-inventory/blob/7c07e77bf6792acd9f077efeb4a18835bbb45e2b/test_api.py#L1290) there.
This is a follow-up to #419.
=> Request ID tests: Extract host ID to the setUp method

test_api.py
Check request ID only in request ID tests. This [removes](https://github.com/RedHatInsights/insights-host-inventory/pull/474/files#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2L1303) the no request ID [test](https://github.com/Glutexo/insights-host-inventory/blob/9aa762f3b5a4b0c60acd787a0a62ba89df8de1fd/test_api.py#L1342) duplication and make the tests a little bit more atomic.
This is a follow-up to #419.
=> Request ID tests: do not check request ID in every test

test_api.py
[Build](https://github.com/Glutexo/insights-host-inventory/blob/f376c83d811122d15a7e6f287df3f36566631ea2/test_api.py#L1291) the URL in the [_setUp_](https://github.com/Glutexo/insights-host-inventory/blob/f376c83d811122d15a7e6f287df3f36566631ea2/test_api.py#L1288) method, so it’s not necessary to build it in every test case and pass it around.
=> Request ID tests: Extract URL to the setUp method

test_api.py
Move the request ID [header composition](https://github.com/RedHatInsights/insights-host-inventory/blob/b0308b020de7c3f5b046a5f971f7aac7280f98cb/test_api.py#L1290) from the DELETE [method](https://github.com/RedHatInsights/insights-host-inventory/blob/b0308b020de7c3f5b046a5f971f7aac7280f98cb/test_api.py#L1288) to the request ID [tests](https://github.com/Glutexo/insights-host-inventory/blob/c15b40dcdc27c8f4c0c81fce64b28bdc8b879774/test_api.py#L1333). Like this, the logic is at a more appropriate [place](https://github.com/Glutexo/insights-host-inventory/blob/c15b40dcdc27c8f4c0c81fce64b28bdc8b879774/test_api.py#L1338).
This is a follow-up to #474.
=> Request ID tests: compose request ID header in the separate tests

test_api.py
[Remove](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:added_request_id_test_remove_common_method?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2L1316) the universal test [method](https://github.com/RedHatInsights/insights-host-inventory/blob/b0308b020de7c3f5b046a5f971f7aac7280f98cb/test_api.py#L1316) and call the stuff from its body directly. Like this the [tests](https://github.com/Glutexo/insights-host-inventory/blob/6824b2435ce5cd401311e6933dcf63f885e72078/test_api.py#L1316) are more straightforward.
This is a follow-up to #419.
=> Request ID tests: Remove the common test method

.github/CODEOWNERS
This sets up default assignees on pull requests
=> set up code owners

app/models.py, app/serialization.py, migrations/alembic.ini, migrations/versions/b2102a7db5e8_timestamptz.py, test_api.py, test_unit.py
https://projects.engineering.redhat.com/browse/RHCLOUD-2872
=> migrate timestamp columns to use timestamptz

Pipfile, Pipfile.lock, app/__init__.py
https://projects.engineering.redhat.com/browse/RHCLOUD-2880
=> collect and export HTTP metrics from flask

Makefile
for rare cases when the commit hooks does not kick in automatically
=> add a makefile command to run style checks

utils/payloads.py
* Removed unused variables, constants and functions.
* Ordered the objects so variables come before functions.
* Moved literal values and variables used only in one place to the respective place of usage.
=> Performance input: Cleanup payloads variables and functions

api/host.py, app/utils.py
I think this should fix the 500 issues that @karelhala has been encountering. If not, it still improves the functionality of the /tags and /tags/count endpoints
=> Tagging fix 500

app/__init__.py, app/auth/__init__.py, app/config.py, app/serialization.py, app/xjoin.py, logconfig.ini
Common cross join code for #532 and #526. Final touches and tests to be added.
=> Cross-join common code

Pipfile, Pipfile.lock
should help with frequent partition rebalances according to https://github.com/dpkp/kafka-python/issues/1418
=> upgrade kafka-python to 1.4.7 RHCLOUD-3625

app/logging.py
https://projects.engineering.redhat.com/browse/RHCLOUD-3864
=> make CloudWatch log_stream configurable (and default to hostname)

app/serialization.py, test_api.py
Use _dateutil_ to parse ISO 8601 timestamps from the Cross-Join responses. This applies to _created_on_, _modified_on_ and _stale_timestamp_ fields. Timestamps without decimal part and with offset timezones are now accepted.
=> Use dateutil.isoparse to parse timestamps

app/models.py, app/validators.py, test_api.py, test_mq_service.py
https://projects.engineering.redhat.com/browse/RHCLOUD-4515
=> RHCLOUD-4515 Disallow empty string keys in facts and system_profile

README.md
1. Moved any API-related docs to https://gitlab.cee.redhat.com/insights-platform/platform-docs/merge_requests/53
2. Attempt to re-org the content around to main topics:
(1.) Getting Started
(2.) Running the server locally
3. Go here to see the finished product: https://github.com/RedHatInsights/insights-host-inventory/tree/FixTheDocs
**TODO**
Definitely needs more work, but hopefully this is a good start
=> DOC: reconcile README content w/ platform docs

api/host_query_xjoin.py, api/tag.py, app/xjoin.py, test_api.py
[Link to Jira](https://projects.engineering.redhat.com/browse/RHCLOUD-4531)
Migrating all of the GraphQL queries to work with the [new schema in xjoin-search](https://github.com/RedHatInsights/xjoin-search/pull/48)
=> [WIP] New schema migration (RHCLOUD-4531)

app/models.py, test_api.py, test_db_model.py, test_mq_service.py
Jira: https://projects.engineering.redhat.com/browse/RHCLOUD-3524
=> RHCLOUD-3524: Enforce stale timestamp timezone

app/models.py, app/validators.py, test_validators.py
Fix to allow validation of satellite_ids that come from Sat 5 hosts.
See https://bugzilla.redhat.com/show_bug.cgi?id=1821321
=> update validation on satellite_id to support Sat 5

api/host.py, api/host_query_db.py, lib/host_repository.py, test_api.py
Jira: https://projects.engineering.redhat.com/browse/RHCLOUD-4824
=> RHCLOUD-4824 - Culled Host No Dedup

.github/CODEOWNERS
Give me the power, I promise to use it wisely.
=> Make shdunning code owner

app/events.py, app/queue/egress.py, app/queue/ingress.py, lib/host_delete.py, tasks/__init__.py, test_api.py, test_mq_service.py, utils/kafka_consumer.py
Jira: https://projects.engineering.redhat.com/browse/RHCLOUD-5000
=> RHCLOUD-5000: Add msg headers to indicate msg type

app/queue/ingress.py
This might be helpful for debugging "where are my tags?" types of situations
=> MQ ingress logging - log the incoming tags

app/auth/identity.py, app/instrumentation.py, app/models.py, test_api.py, test_unit.py, utils/validate_hosts_for_delete.py
Jira: https://projects.engineering.redhat.com/browse/RHCLOUD-6055
=> RHCLOUD-6055 - always update stale_timestamp from next reporter

README.md, dev.dockerfile
This is useful when setting up the xjoin/syndication dev environment. Might be useful to inventory devs too.
=> Dockerfile for development purposes

swagger/api.spec.yaml
The current schema for what is returned by these endpoints is incorrect. This PR fixes that
=> Fix the schema for get hosts and hosts/{id_list} [RHCLOUD-4434]

Pipfile, Pipfile.lock
This package was removed from pypi and it looks like we never use it in the first place. This updated the pipfiles to remove it
=> removed unused dependency

app/__init__.py
Shutdown handler registration has been extracted to _lib.handlers_. Reused that in the Flask application.
A follow-up to [RHCLOUD-5357](https://projects.engineering.redhat.com/browse/RHCLOUD-5357) #688 and [RHCLOUD-5358](https://projects.engineering.redhat.com/browse/RHCLOUD-5358) #691.
=> DRY shutdown handlers

README.md
- Fixed MarkDown numbering to be nicer in plain text.
- Replaced _stage_ and _prod_ with longer names _staging_ and _production_.
- Mentioned that App SRE bot needs to be added to a fork.
- Added a link to the list of code owners.
=> Little touches to update release process

api/metrics.py, app/logging.py, app/xjoin.py, lib/middleware.py, logconfig.yaml
- metrics for response times
- propagate urllib3 logs
=> RHCLOUD-8795 Outbound http request observability improvements

README.md
Fix header base64 encoded parameter to consider the new payload key called type
=> Fix README api call examples

app/models.py, swagger/system_profile.spec.yaml
Pending the merging of the inventory-schema PR here:
https://github.com/RedHatInsights/inventory-schemas/pull/17
=> Add tuned_profile to facts

app/models.py, swagger/system_profile.spec.yaml
Pending Schema PR here: https://github.com/RedHatInsights/inventory-schemas/pull/24
=> Add selinux facts to system_profile

app/models.py, swagger/system_profile.spec.yaml
Pending schema PR: https://github.com/RedHatInsights/inventory-schemas/pull/25
=> Add addtional SAP facts to system profile

deployment.yaml
This is a separate commit so the app-interface MR to get the ephemeral
envs can be set up so PR #737 can pass its PR check.
=> Add ClowdApp deployment template

api/host.py, swagger/api.spec.yaml, tests/fixtures/api_fixtures.py, tests/test_api_hosts_update.py
Addresses https://issues.redhat.com/browse/RHCLOUD-10546
=> Check-In endpoint refactoring and cleanup

docs/pull_request_template.md
Addresses bullet point #3 on [this Jira card](https://issues.redhat.com/browse/RHCLOUD-10357).
=> Add secure coding PR template

docs/pull_request_template.md
=> Add an Overview section to the PR template

.gitignore, .sonar/sonar-scanner.properties.template, README.md, sonar_scan.sh
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-10357).
It adds Sonar integration functionality, and adds setup instructions to the README.
=> Set up Sonar integration

swagger/system_profile.spec.yaml, tests/helpers/system_profile_utils.py, tests/helpers/test_utils.py
This is the corresponding PR to https://github.com/RedHatInsights/inventory-schemas/pull/28
~~- [ ] Output Encoding~~
~~- [ ] Authentication and Password Management~~
~~- [ ] Session Management~~
~~- [ ] Access Control~~
~~- [ ] Cryptographic Practices~~
~~- [ ] Error Handling and Logging~~
~~- [ ] Data Protection~~
~~- [ ] Communication Security~~
~~- [ ] System Configuration~~
~~- [ ] Database Security~~
~~- [ ] File Management~~
~~- [ ] Memory Management~~
~~- [ ] General Coding Practices~~
=> Only allow unique items for sap_sids

lib/host_synchronize.py, tests/helpers/mq_utils.py, tests/test_synchronizer.py
Use host id as the event key
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-8122).
=> RHCLOUD-8122 fix event key

api/host.py, app/instrumentation.py, host_reaper.py
This changes how we log the access rule invoked for delete events to prevent the reaper from crashing when it tries to produce event success/failure log messages.
=> Fix reaper logging bug

README.md
This PR updates the identities in the README file to work with the changes introduced in the authenticated systems PR
=> updated user and system identities in README

app/auth/identity.py, lib/host_repository.py, tests/helpers/test_utils.py, tests/test_api_auth.py
This PR improves out identity validation to prevent system identities lacking the required fields.
=> system identity validation fix

Dockerfile, build_deploy.sh, deployment.yaml, pr_check.sh
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11665).
This PR will:
* Build and deploy to latest and qa only on a push to master. 
* Update the Clowdapp template (deployment.yaml) to use the new podSpec inside deployments
* Remove `source build_deploy.sh` from pr_check
* Build and tag a pr_check hash without pushing to latest or qa 
* Copy `dev.dockerfile` to `Dockerfile` for build process -- Discuss rename
=> Update build pipeline -- phase one

Pipfile, Pipfile.lock, app/config.py, pr_check.sh, tests/fixtures/db_fixtures.py, tests/test_unit.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11665).
These changes will
* Run unit tests in PR checks using Clowder
* Add a `port` option for the Postgresql URI
* Lock prance to 20.0 and lock sqlalchemy-utils to 0.36.7 (due to a bug in 36.8)
* Pipe the db creds into the `set_environment` method
=> Run unit tests in pr_check.sh

swagger/system_profile.spec.yaml
Syncing System Profile. PR: https://github.com/RedHatInsights/inventory-schemas/pull/43
This is a copy-paste of the schema.
=> sync system-profile

api/host.py
Pylint on my VS code was giving me warnings for possible syntax errors. So, I decided to investigate and found out that we are not providing sufficient parameters to one function and we are not using the other function at all.
=> Fix syntax errors and remove unused function

app/models.py, swagger/system_profile.spec.yaml
This PR is being created to address [this Jira](https://issues.redhat.com/browse/HBISPSC-33).
This adds "rhsm" to match a similar PR in inventory schema.
=> add rhsm to marshmallow

lib/system_profile_validate.py, tests/helpers/mq_utils.py, tests/test_system_profile.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12307).
Allows the SP validator endpoint to fetch all partitions for the host-ingress topic. Adds a new test that verifies that messages from multiple partitions are validated.
=> SP Validator partition fix

app/models.py, swagger/system_profile.spec.yaml, tests/helpers/system_profile_utils.py, tests/helpers/test_utils.py, utils/payloads.py
This PR adds `rhc_client_id` to system_profile, which is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11619).
The corresponding inventory_schemas PR: https://github.com/RedHatInsights/inventory-schemas/pull/49
=> rhc-11619: sync rhc_client_id in system_profile to on one in inventory_schemas

lib/system_profile_validate.py, system_profile_validator.py
This PR makes some tiny changes to the validator's exception handling. There's currently an issue where a generic error message is returned and it's unclear what caused it or where it was being thrown from, and it turns out we should be using logger.exception() for these scenarios whenever possible.
=> Better exception handling for validator

lib/system_profile_validate.py
This is just a small bugfix for situations where hosts are parsed but don't have a reporter field.
=> Set reporter to "unknown_reporter" if reporter is missing

system_profile_validator.py
This tiny PR just modifies the format of the comments that get posted by the SP validator.
I made this change after looking at [this dippy-bot comment](https://github.com/RedHatInsights/inventory-schemas/pull/54#issuecomment-800771714).
I have removed the checklist for this PR because this is a one-character change to a text field.
=> Modify format of posted comments

lib/system_profile_validate.py, system_profile_validator.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12982).
- Fix faulty PR-check logic
- Create new consumer for each PR iteration
- Fix comment wording
=> SP Validator Fixes

docs/_index.md
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12611).
Adds alethia support to our docs.
(none apply)
=> Add alethia header to main doc

Makefile, app/__init__.py, app/config.py, app/queue/event_producer.py, app/queue/queue.py, deployment.yaml, docs/_index.md, tests/fixtures/mq_fixtures.py, tests/test_mq_service.py, tests/test_unit.py, utils/kafka_consumer.py
This PR removes all references to the deprecated `platform.inventory.host-egress` topic.
=> Removing all references of host-egress topic

api/host.py, app/__init__.py, app/queue/event_producer.py, app/queue/queue.py, lib/host_delete.py, lib/host_synchronize.py, tests/helpers/mq_utils.py, tests/test_mq_service.py, tests/test_unit.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-xxxxx).
(A description of your PR's changes goes here.)
=> Topic logic refactoring

app/queue/queue.py, utils/payloads.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13237).
logging host info should help locating the source reporter with problematic message.
=> rhc-13237: log host info when identity not provided

api/host_query_xjoin.py, api/system_profile.py, api/tag.py, tests/test_xjoin.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-xxxxx).
(A description of your PR's changes goes here.)
=> Add new system profile filters

docs/_index.md
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13266).
I wanted to make sure that we documented the new system_profile fields we can filter on. I noticed that the current docs use fields that actually are not supported so I updated the examples to use supported fields instead. I also added a list of the fields we do support so that it's not ambiguous for users.
=> updated system_profile filtering section

api/host_query_db.py, lib/host_repository.py, tests/test_api_hosts_get.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13331).
This PR renames 4 function names for clarity because they were almost identical and poses confusion and difficulty during debugging.
- [x ] Keep PR title short, ideally under 72 characters
- [x ] Descriptive comments provided in complex code blocks
=> rename almost identical function names

README.md
The auto numbering was glitching out because of the code snippets. Hard coding them should fix it
=> Fix numbering in read me

README.md
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13160).
Updates the README with additional information about the README, including enforcement. Also renames a section header and clarifies why we set the Identity.
(Additionally, I updated the Platform Docs link to the new site).
- None (doc update)
=> Update README with Identity info

deployment.yaml, pr_check.sh
This PR is being created to address the change in Kafka topics [introduced here](https://github.com/RedHatInsights/insights-host-inventory/pull/843/files). `pr_check.sh` needs the updated template and topics to deploy correctly.
=> Update Kafka Topics for Clowder Template

deployment.yaml
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13451).
Blake made some updates to the Clowder template this morning, and that led me to realize that there are other updates in e2e-deploy that should be reflected here.
(None apply)
=> Update Clowder template to reflect e2e-deploy changes

docs/_index.md
This PR is documents the work done on: https://issues.redhat.com/browse/RHCLOUD-13204
=> Updating docs to mention /hosts sparse field functionality

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13499).
Adds an additional reporter filter to the kibana url in grafana dashboard.
=> Grafana - Adding reporter filter to kibana query [RHCLOUD-13499]

app/queue/queue.py
This PR is being created to address [RHCLOUD-13002](https://issues.redhat.com/browse/RHCLOUD-13002).
Host deserialization throws a ValidationException when the Host data does not adhere to the schema (including System Profile). In these situations, we don't want to log the entire exception along with the stack trace; we only want to see the error message itself, so that it's easier to use Kibana to identify issues.
=> Schema validation error logging

app/queue/queue.py, tests/test_mq_service.py
This PR is being created to address [RHCLOUD-13640](https://issues.redhat.com/browse/RHCLOUD-13640).
We were seeing errors in our Kibana logs that didn't make any sense, and it was due to the Identity validation occurring before `threadctx.request_id` had been set. This caused errors to be attributed to the `request_id` for the most recent message whose Identity did not fail validation. This moves the Identity validation into the PayloadTrackerContext so that our `platform_metadata`/Identity error logs are no longer misleading.
=> Only perform validation after Request ID is set

docs/_index.md
This PR is being created to document `platform_metadata` as a must-have requirement.  It addresses the deprecated requirement for platform_metadata requirement pointed out by [Kevin Howell](https://ansible.slack.com/archives/CDVFMQU31/p1618427296195100?thread_ts=1618426725.192400&cid=CDVFMQU31)
=> document platform_metadata as a must-have requirement

pr_check.sh, unit_test.sh
Switches pr_check.sh and unit_test.sh to use common cicd scripts
=> Edit pr_check to use common code

app/auth/identity.py, tests/test_mq_service.py, utils/payloads.py
Removed email and user name removed as requirements as for adding/updating hosts. These two params are not used for finding hosts.
@fstavela  asked Lindani whether email requirement should be removed.  Lindani has okay the removal.
cc: @lphiri 
=> removed user email and name as a requirement in identity

api/host_query_xjoin.py, tests/test_xjoin.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13257).
We need a way to filter based on the operating system field of system profile. This adds support and some tests.
corresponding xjoin-search PR is here: https://github.com/RedHatInsights/xjoin-search/pull/95
=> Add filter for system profile operating_system field

api/host_query_xjoin.py, tests/test_xjoin.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13172).
Adds filter for owner_id including. Also fixes a bug that fails on multiple strings filtering.
=> Add owner id filter

docs/_index.md
Untracked work :partying_face: 
This is just a quick docs change to add in the new filters: `operating_system` and `owner_id`
I also noticed some of the types left the values we expect a little ambiguous so I added some examples into the table to help clarify.
=> add new filters to docs

app/config.py
This PR is part of the work needeed for [this Jira](https://issues.redhat.com/browse/RHCLOUD-10353).
This is a similar PR to that of RedHatInsights/insights-advisor-service#293
The Kafka Consumer API doc can be found [here](https://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html).
=> Adding kafka consumer ssl configs

app/auth/identity.py
This PR is being created to allow JWT auth.
=> Hotfix: Add JWT and UHC Auth

swagger/system_profile.spec.yaml
Corresponding `inventory_schemas` PR: https://github.com/RedHatInsights/inventory-schemas/pull/61
=> Add field to identify edge hosts

swagger/system_profile.spec.yaml
Corresponding inventory_schemas PR: RedHatInsights/inventory-schemas#62
Signed-off-by: Christopher Sams <csams@redhat.com>
=> Add field for greenboot status

deployment.yaml
This PR is being created to help clean up the deployment for HBI & Remediations.
It's echoing the changes being made in this [e2e-deploy PR](https://github.com/RedHatInsights/e2e-deploy/pull/3091).
=> Update xjoin url in deployment

deployment.yaml
This PR is just to add one character that I missed in my initial changes.
=> Deploy template typo hotfix

README.md
Realized this update while checking something else.
=> Update python version in Getting Started in README

app/queue/queue.py, dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [RHCLOUD-13815](https://issues.redhat.com/browse/RHCLOUD-13815).
It changes the labels on the Prometheus metrics to use the more specific exception, when available. This will allow our Grafana dashboard to distinguish between validation exceptions, inventory exceptions, and uncaught errors.
=> Update Prometheus labels & Grafana dashboard

Dockerfile
This PR is being created to apply security patches to the `ubi8/python38`.   For the context, following is the message from @casey-williams-rh:
> Hey Muhammad, it looks like your deployment for insights-inventory pulled an older version of “ubi8/python-38” [1], and the update did not patch out several fixable vulnerabilities. Additionally, you can add RUN dnf upgrade --security to pull Z-Stream security updates. Meaning that updates it should not introduce any breaking changes, only backports if available. 
> I would add RUN dnf upgrade --security to your dockerfile, and respin the pod with the newest “ubi8/python-38" [2]
> 
> [1] https://catalog.redhat.com/software/containers/ubi8/python-38/5dde9cacbed8bd164a0af24a?tag=1-54.1618436884
> [2] …
=> Proactively apply security patches to the image

deployment.yaml
This PR sets HBI replica sizes to the same as `saas-deployed`.
=> Update clowder deployed replicas to same as saas-deployed

Dockerfile, swagger/system_profile.spec.yaml
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-14534).
This is making our validation of MAC addresses stricter. The corosponding change in the inventory schemas repo has already been merged ([see here](https://github.com/RedHatInsights/inventory-schemas/pull/69)).
=> added spec change

deployment.yaml
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11573).  This PR is the last step of other services accessing HBI.
=> Set hbi service proxy to handle not-yet-clowderized services

Pipfile, Pipfile.lock, app/config.py, lib/system_profile_validate.py, tests/helpers/mq_utils.py
This PR is being created to bump the kafka-python library to support the SCRAM-SHA-512 option for the sasl_mechanism that's required by  fedramp.
=> Bumping kafka-python library

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [ESSNTL-761](https://issues.redhat.com/browse/ESSNTL-761).
Our Grafana dashboard has been broken for the Stage datasource, due to the Clowder-related name changes. This changes the references to services and log streams in order to align with the Clowder changes.
=> Fix Grafana dashboard to align with Clowder-related changes

deployment.yaml, utils/synchronizer_clowd_job_invocation.yaml
This PR is being created to as a part of [this Jira](https://issues.redhat.com/browse/ESSNTL-745) implementation.
This specific PR adds Reaper CronJob and Synchronizer Job to the Clowder app.
The reaper and synchrnizer jobs were created from:
https://gitlab.cee.redhat.com/aarif/saas-templates/-/blob/master/templates/inventory/insights-inventory-reaper.yaml
https://gitlab.cee.redhat.com/aarif/saas-templates/-/blob/master/templates/inventory/inventory-host-synchronizer.yaml
=> add reaper cronjob and synchronizer job to Clowdapp definition

app/config.py, app/payload_tracker/__init__.py
This PR is to resolve the :bug: introduced in #937 . Merging this might resolve our partial `stage` outage. :crossed_fingers: 
=> Fixing payload tracker kafka producer config

deployment.yaml, utils/synchronizer_clowd_job_invocation.yaml
This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-xxxxx).
This PR adds new parameters to the ClowdApp's parameters list.  So the new params values could be read from the `app-sre` environment variables file.
=> add params for reading vars from app-sre env file

app/config.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-761).
This may fix the metrics problem for the Clowder deployed HBI
=> Add the missing prometheus server path from Clowder config

swagger/system_profile.spec.yaml
Signed-off-by: Christopher Sams <csams@redhat.com>
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-14104).
It adds limited data from rpm ostree deployments as reported by `rpm-ostree status --json` to the system profile.
=> Add deployments from rpm ostree status to system profile.

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
Another PR created as part of [ESSNTL-761](https://issues.redhat.com/browse/ESSNTL-761).
This updates our Grafana dashboard to match our new service monitor strategy for Clowder, and removes an old unused table (HTTP-based Host-create requests).
=> Update dashboard metrics to match new strategy; remove unused table

app/serialization.py, tests/test_deduplication.py
This PR is being created to address [ESSNTL-772](https://issues.redhat.com/browse/ESSNTL-772).
Some duplication is being caused by reporters not agreeing on capitalization. This PR does a casefold on the canonical facts fields upon deserialization; that's essentially a lowercase in most situations, and is designed to remove case differences from the equation. 
Since deserialization happens very frequently, I want to make the `_recursive_casefold` function as performant as possible. If you can think of a way to make it even faster, please let me know!
=> Casefold canonical facts

deployment.yaml
There isn't a Jira for this PR. It fixes the default parameter values for the Prometheus pushgateway and Kafka vars, as that was causing unexpected behavior in some envs. It also renames some parameters to what's provided in app-interface, so we don't have to provide redundant parameter values in deploy-clowder.
=> Fix deployment env vars

app/config.py
This PR isn't associated with a Jira. It aims to fix the Kafka SASL-related error we're seeing in Stage and Ephemeral envs.
=> Don't try to get user/pass if sasl property doesn't exist

app/models.py, app/validators.py, tests/test_mq_service.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-549).
Pretty simple one. We aren't validating these MAC addresses very well, we just check that they are a reasonable length. This PR adds validation allowing all valid MAC address formats, including those weird long ones that we get occasionally.
=> Improve canonical facts MAC address validation

Pipfile, Pipfile.lock, api/host.py, app/models.py, app/queue/events.py, app/queue/queue.py, app/serialization.py, lib/system_profile_validate.py, tests/test_models.py, tests/test_unit.py
This PR is being created to address [ESSNTL-890](https://issues.redhat.com/browse/ESSNTL-890).
It upgrades our version of Marshmallow to 3.8.0, and fixes many breaking changes that were introduced since version 2.x. This upgrade will make it simpler to validate certain field types without adding unnecessary custom code (such as IP addresses, for instance).
=> Upgrade Marshmallow to 3.8.0

deployment.yaml
This PR is being created to add system profile validaator cronjob as a part of [this Jira](https://issues.redhat.com/browse/ESSNTL-745).
=> Add system profile validator cron job to HBI clowdapp definition

api/host.py, api/host_query_db.py, api/host_query_xjoin.py, lib/host_repository.py, tests/fixtures/mq_fixtures.py, tests/test_api_hosts_get.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-893](https://issues.redhat.com/browse/ESSNTL-893).
My previous PR (#948) attempted to casefold the canonical facts, in order to eliminate case-sensitivity in our identifiers, and thus reduce duplication. However, I didn't account for our filter logic not casefolding as well, so this is meant to rectify that.
=> Casefold canonical fact filters

deployment.yaml
This PR is being created to fix the pendo syncher deployment 
=> Fix pendo creds pull in deployments

deployment.yaml
This PR will reduce the logging for the pendo syncher job.
=> Reduce pendo syncher logging

build_deploy.sh
Reverts RedHatInsights/insights-host-inventory#972
=> Revert "pull the image before building it to ensure the latest image"

build_deploy.sh
Reverts RedHatInsights/insights-host-inventory#974
=> Re-add "--pull=true"

app/config.py, deployment.yaml, lib/middleware.py, run_gunicorn.py, tests/fixtures/api_fixtures.py
This PR is being created to address [ESSNTL-143](https://issues.redhat.com/browse/ESSNTL-143).
By request, it changes our `RBAC_ENFORCED` variable to be a more positive indicator (`BYPASS_RBAC`), and adds a couple places where it's set by default (running the app locally, and running unit tests). 
=> Change RBAC variable wording and default value

deployment.yaml
This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-930).
According to [clowder documentation](https://clouddot.pages.redhat.com/docs/dev/getting-started/ephemeral/smoke.html#_clowdapp_settings) this is needed in order to run iqe-host-inventory-plugin tests in ephemeral environments.
=> Add host-inventory IQE Plugin to deployment.yaml

app/models.py, app/queue/events.py, app/serialization.py, app/utils.py, swagger/api.spec.yaml, tests/helpers/api_utils.py, tests/helpers/db_utils.py, tests/helpers/mq_utils.py, tests/test_api_hosts_update.py, tests/test_deduplication.py, tests/test_unit.py, tests/test_xjoin.py, utils/payloads.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-1003).
=> remove rhel_machine_id and references from HBI code

lib/host_remove_duplicates.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-xxxxx).
=> added expunge to end of loops to hopefully prevent OOM

tests/test_duplicate_hosts.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-1221).
This PR adds additional tests for duplicates deletion script.
=> Duplicates delete tests

deployment.yaml
This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-1221).
It adds a new parameter, REQUEST_LIMIT, for customizing memory request size.  It will be used by `deploy_clowder.yaml`.
=> Add new parameter REQUEST_LIMIT to deployment.yml

Pipfile, Pipfile.lock, app/models.py, app/validators.py, tests/helpers/system_profile_utils.py, tests/test_culling.py, tests/test_system_profile.py
This PR is being created to address [ESSNTL-1170](https://issues.redhat.com/browse/ESSNTL-1170).
Changes our date-time string validation to be more lenient, allowing time zone data to be omitted.
I had to remove the old implementation, because it was necessarily strict and didn't allow for that kind of customization. Instead, I've opted to redo this using a custom validator approach.
The original PR to add date-time validation is [here](https://github.com/RedHatInsights/insights-host-inventory/pull/968).
=> Use custom format checker to validate date-time strings

app/config.py, rebuild_events_topic.py, tests/helpers/mq_utils.py, tests/test_event_rebuilder.py
This PR is being created to address [ESSNTL-1363](https://issues.redhat.com/browse/ESSNTL-1363).
Basically, reverts most of the bigger changes I made in my last bugfix (#1008), and makes a small JSON fix.
=> Rebuild events bugfix

app/instrumentation.py, app/queue/queue.py
This PR is being created to address [ESSNTL-1690](https://issues.redhat.com/browse/ESSNTL-1690).
This makes it so the root cause of the error makes it to the "Error adding host" logs. 
=> Add exception detail to log_add_host_failure message

README.md
Update docs link in README again
=> Update docs link in README again

deployment.yaml
=> Fix the floorist query

deployment.yaml
This is based on feedback from the datahub team. This will be an incremental process to refine the query. The initial request is to send them data related to Red Hat products which I think this mostly covers.
=> Add more fields to floorist query

app/instrumentation.py, app/queue/queue.py, rebuild_events_topic.py
This PR is being created to address [ESSNTL-1965](https://issues.redhat.com/browse/ESSNTL-1965) and [ESSNTL-1968](https://issues.redhat.com/browse/ESSNTL-1968). 
It turns out the Lambda function that copies our logs to ElasticSearch has an issue with a few of our logs, which this PR fixes:
- Two of the log statements attempt to render object containing the headers as a string, which it doesn't seem to like. This removes the string conversion and keeps the headers in the "extra" object.
- Two other log statements attempt to render the whole "message" object, but ES apparently has an issue converting it sometimes. I've changed this to just render "message.value", which shows the important contents without having to render the fields we don't care about.
More information on the Lambda errors …
=> Logging fixes

Dockerfile, Pipfile, Pipfile.lock, README.md, dev.dockerfile
Reverts RedHatInsights/insights-host-inventory#1066
=> Revert "Fix dependency issue and add Snappy support"

deployment.yaml
=> Remove synchronizer CJI

deployment.yaml
=> Fix floorist "resources" param indent (deployment.yaml)

api/filtering/filtering.py, api/filtering/filtering_common.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-2084](https://issues.redhat.com/browse/ESSNTL-2084) and [ESSNTL-2162](https://issues.redhat.com/browse/ESSNTL-2162).
I think it's reasonable to expect users would like to use range operations on integer and time-stamp fields. Xjoin-search already supports it so we just had to forward the right operations on and adjust our validation. Unfortunately this added some unused variables to the builder functions for the sake of having a uniform interface, but they may need that information down the line so I think it's acceptable.
=> Int and timestamp range operations

sonarqube.sh
This PR is being created to address [ESSNTL-1588](https://issues.redhat.com/browse/ESSNTL-1588).
The sources directory originally passed to the sonar-scanner does not exist in the insights-host-inventory repository. This PR addresses that issue.
=> Fix sources directory in sonarqube.sh

deployment.yaml
This PR is being created to add our app label to the `events-topic-rebuilder` ClowdJobInvocation.
Hopefully it'll fix the issue of the missing app label, but it won't hurt anything if it doesn't work.
=> Add app label to CJI

api/filtering/filtering.py, tests/test_api_hosts_get.py, tests/test_xjoin.py
This PR is part of the solution for [ESSNTL-1629](https://issues.redhat.com/browse/ESSNTL-1629).
Other related PRs:
- Chrome: https://github.com/RedHatInsights/insights-chrome/pull/1783
- Inventory Front-end: https://github.com/RedHatInsights/insights-inventory-frontend/pull/1502
This change should be merged first since the front-end changes depend on it.
We had an urgent request to allow searching for if the ansible objects was nil/not_nil. We currently support this behavior on scalar system_profile fields, but not on objects. This PR allows nil/not_nil queries to be made against object fields in the same way we allow it with scalars.
=> Allow querying for the existence of objects on hosts

api/host.py
This PR is fixed the problem caused by https://github.com/RedHatInsights/insights-host-inventory/pull/1047#discussion_r829027619
=> add message for no host available

api/system_profile.py, tests/test_xjoin.py
This PR is being created to fix an issue with the format of SAP xjoin calls.
=> Fix hostFilter on SAP calls

pr_check.sh
Send test results to Ibutsu from PR checks
=> Send test results to Ibutsu from PR checks

README.md, dev.dockerfile
This makes it possible to build the dev.dockerfile Dockerfile with rootless podman
=> Update dev Dockerfile to not to require root to build

swagger/api.spec.yaml, swagger/openapi.json
This PR is being created to address [ESSNTL-2067](https://issues.redhat.com/browse/ESSNTL-2067).
It appends `(case-insensitive)` to the applicable fields in the API spec for clarification purposes.
Our consoledot docs refer to this API spec for details on the REST interface, so there's no reason to duplicate it there.
=> Clarify case-insensitivity for filters in the API spec

deployment.yaml
This PR is being created to address [ESSNTL-2927](https://issues.redhat.com/browse/ESSNTL-2927).  This is not a permanent solution but should allow PR checks to succeed, while a more permanent fix is being looked into.
=> lower gunicorn workers to 1 to avoid port 9000 conflicts

app/queue/events.py, host_synchronizer.py, lib/host_synchronize.py
This PR is being created to address [ESSNTL-1292](https://issues.redhat.com/browse/ESSNTL-1292).
It makes some minor updates to host-synchronizer, which we can use to send the update events (rather than rebuild-events-topic).
=> Minor updates to host-synchronizer

deployment.yaml
This PR is part 2 of [ESSNTL-2526](https://issues.redhat.com/browse/ESSNTL-2526).
It makes a CJI for the host synchronizer, which will also trigger a new run in Stage. When we do this in Prod, we'll need to first deploy the commit ref with the org_id populator, and then this one.
=> Add CJI for host synchronizer; update env var

api/host.py, tests/test_api_hosts_delete.py
This PR is being created to address [ESSNTL-2359](https://issues.redhat.com/browse/ESSNTL-2359).
A small fix to remove the 404 response when deleting all hosts does not succeed. 
=> Update returned message when no host is found for deletion (delete all hosts)

deployment.yaml
This PR is being created to address [ESSNTL-3113](https://issues.redhat.com/browse/ESSNTL-3113).
It increases the maximum request field size, which means we won't hit the header limit people are running into in Prod.
=> Increase gunicorn's request field size limit

deployment.yaml
Make it possible to configure topic (platform.inventory.events) and consumer group (inventory-mq) via deployment.yaml template parameters
- [-] Tests: validate optimal/expected output
- [-] Tests: validate exceptions and failure scenarios
- [-] Tests: edge cases
- [-] Recovers or fails gracefully during potential resource outages (e.g. DB, Kafka)
- [-] Uses [type hinting](https://docs.python.org/3/library/typing.html), if convenient
- [-] Documentation, if this PR changes the way other services interact with host inventory
- [-] Links to related PRs
- [-] Input Validation
- [-] Output Encoding
- [-] Authentication and Password Management
- [-] Session Management
- [-] Access …
=> Make it possible to configure topic and consumer group

deploy/clowdapp.yml
This PR's purpose is to update the new deployment config (deploy/clowdapp.yml) with the changes made in #1161, so that it will stay in sync with the original (deployment.yaml).
=> Update new deploy file to keep in sync with original

deployment.yaml
This makes it possible to deploy two different namespaces with HBI to one cluster
=> Make it possible to configure more Clowder's CRD properties

deployment.yaml
Reverts RedHatInsights/insights-host-inventory#1166
=> Revert "add missing environment variables"

app/config.py, deployment.yaml
It's causing producer errors in Stage.
=> Revert "Don't try to create a topic if it isn't used"

deploy/clowdapp.yml
This PR is being created to address [ESSNTL-3124](https://issues.redhat.com/browse/ESSNTL-3124).
It's just updating the new `deploy/clowdapp.yml` deployment file to keep it in sync with the latest changes to `deployment.yaml`.
=> Update our new deployment files again

deploy/clowdapp.yml, deployment.yaml
This PR is being created to address [ESSNTL-3171](https://issues.redhat.com/browse/ESSNTL-3171).
It adds the events topic var to the reaper and host-synchronizer jobs. We recently had to remove using default values for our kafka topics because of the migration to managed Kafka, as well as changes made for perf-devel environment testing.
=> Add kafka events topic var to Reaper and Synchronizer

deploy/clowdapp.yml
This PR is being created to address [ESSNTL-3124](https://issues.redhat.com/browse/ESSNTL-3124).
Adds the notification topic vars to the new template to keep it up to date with the old template.
=> Add notification topic vars to new deployment template

app/config.py, rebuild_events_topic.py
This PR is being created to address [ESSNTL-3367](https://issues.redhat.com/browse/ESSNTL-3367).
This will hopefully fix the issue with `events_topic_rebuilder.py` in Stage. This config change worked in ephemeral environments; I've also added debug statements to provide more insight when run with LOGLEVEL=DEBUG.
=> Fix event-rebuilder job

app/auth/identity.py, tests/test_identity_schema.py
This PR is being created to address [ESSNTL-647](https://issues.redhat.com/browse/ESSNTL-647).
Implemented Marshmallow schemas to validate identity data.
=> Validate Identity objects using a schema.

app/auth/identity.py, tests/test_identity_schema.py
This PR is being created to address [ESSNTL-3492](https://issues.redhat.com/browse/ESSNTL-3492).
This adds restrictions for "auth_type" and "cn" fields, along with tests for both.
=> Identity fixes

app/queue/queue.py
This PR is being created to address [ESSNTL-3565](https://issues.redhat.com/browse/ESSNTL-3565), and also the work I'm doing to help Advisor identify and resolve an orphaned host in Stage. It logs every host it finds in the events topic, and then logs additional information depending on whether it generated a "deleted" event.
=> Log ID of every host processed by events-topic rebuilder

iqe_tests.sh
This PR is being created to address [ESSNTL-3529](https://issues.redhat.com/browse/ESSNTL-3529).
This PR adds a script for a new GitHub action that will run the full IQE test suite on all PRs.
It will not be mandatory to wait for this action to finish or succeed before you want to merge your PR. Especially if you have a small PR with a quick fix, don't wait for it to finish, it can take up to 2 hours.
The reason for this new GH action is to speed up the testing of significant changes and speed up our Prod deployments because with big changes these tests would have to be run anyway.
This PR will be followed by app-interface MR.
=> Add script for running full IQE test suite on PRs

iqe_tests.sh
This PR is being created to address [ESSNTL-3529](https://issues.redhat.com/browse/ESSNTL-3529).
This PR fixed the script for the new GitHub action.
=> Fix script for new IQE github action

app/queue/queue.py, rebuild_events_topic.py
This PR is being created to address [ESSNTL-3589](https://issues.redhat.com/browse/ESSNTL-3589) and [ESSNTL-3565](https://issues.redhat.com/browse/ESSNTL-3565). It reduces the excessive amount of logging we were doing during debugging, and re-introduces shutdown handling. If the shutdown handler causes it to break again, we'll revert this PR.
=> Handle shutdown in events-topic rebuilder

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [ESSNTL-3607](https://issues.redhat.com/browse/ESSNTL-3607) and [ESSNTL-3603](https://issues.redhat.com/browse/ESSNTL-3603).
It adds a panel to help us keep track of our RDS burst balance, since that has a dramatic effect on DB performance. It also fixes the Reaper panels to be actually readable and useful.
=> Add Burst Balance panel; fix Reaper panels

app/config.py
This PR addresses a Kafka security configuration issue discovered in the Stage environment. Slack conversation for context: https://ansible.slack.com/archives/C022YV4E0NA/p1669131144878159
=> Fix kafka security protocol and mechanism config

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [ESSNTL-3612](https://issues.redhat.com/browse/ESSNTL-3612).
Our old expressions don't work with the new managed-kafka topics; this PR updates the expressions to work with both managed-kafka and our current setup. I validated these on Stage Grafana; feel free to try them out there or in Prometheus if you'd like to validate them as well.
=> Update topic expressions in Grafana queries

api/group.py, api/host.py, swagger/api.spec.yaml, swagger/openapi.json
This PR is being created to address [ESSNTL-4070](https://issues.redhat.com/browse/ESSNTL-4070).
This PR adds the paths specified on [ADR-008: Inventory Groups](https://docs.google.com/document/d/1_zWWRpunieVbvuR6SMjP2fReA1YOS1XruLQaTnYjb6A/edit#) to HBI's REST interface.
=> ESSNTL-4070: add paths for groups

Dockerfile
This PR is being created to address [RHCLOUD-23862](https://issues.redhat.com/browse/RHCLOUD-23862).
The JIRA card provides the reason as to why ubi8-minimal image is being used. Let's see how this image respond when deployed into minikube and OpenShift.
=> RHCLOUD-23862 use ubi8-minimal image for building host-inventory images

.pre-commit-config.yaml, api/filtering/filtering.py, api/host.py, api/parsing.py, app/models.py, app/payload_tracker/__init__.py, app/queue/queue.py, host_delete_duplicates.py, host_synchronizer.py, pendo_syncher.py, system_profile_validator.py, tests/helpers/tracker_utils.py, tests/test_api_hosts_delete.py, tests/test_api_hosts_get.py, tests/test_payload_tracker.py, tests/test_unit.py, tests/test_xjoin.py
This PR upgrades our `Black` pre-commit hook to version 23.1.0, and formats our existing files accordingly.
=> Upgrade black hook

Pipfile, Pipfile.lock, README.md, api/unleash.py, app/__init__.py, app/config.py, deploy/clowdapp.yml, lib/feature_flags.py, swagger/api.spec.yaml, swagger/openapi.json, tests/fixtures/api_fixtures.py, tests/test_unit.py, tests/test_utils.py
**NOTE: The only changes from the original PR are from [this commit](https://github.com/RedHatInsights/insights-host-inventory/pull/1269/commits/c3bf5d6fdf555d9810ba0176e0cb03af7e215c29) onwards.**
This PR is being created to address [ESSNTL-3754](https://issues.redhat.com/browse/ESSNTL-3754).
This re-implements #1259, which was reverted by #1268. In addition to undoing that reversion, it configures a cache directory for Unleash in Clowder environments. It uses the `/tmp/.unleashcache` folder by default; if we decide we want to configure this path later, we can add `UNLEASH_CACHE_DIR` to our clowdapp config.
For non-clowder environments, it leaves `UNLEASH_CACHE_DIRECTORY` unset; this makes it use fcache to decide, which is generally recommended (when there aren't permission issues). I …
=> feat(ESSNTL-3754): Add Unleash support, with fix

api/group.py, api/unleash.py, app/instrumentation.py, lib/feature_flags.py, lib/group_repository.py, lib/metrics.py, swagger/api.spec.yaml, swagger/openapi.json, tests/fixtures/api_fixtures.py, tests/test_api_groups_delete.py, tests/test_utils.py
This PR is being created to address [ESSNTL-3712](https://issues.redhat.com/browse/ESSNTL-3712).
This creates the endpoint `DELETE /groups/{group_id}/{host_id1},{host_id2},{etc}`. It allows the user to remove host-group associations so that hosts no longer appear to be in a group. It also adds a new fixture and logging functions, and updates the `DELETE /groups/{group_ids}` endpoint to return 204 instead of 200.
Update: I've also corrected the `GroupIn` component in the swagger spec to include Org ID and account number. Additionally, I added the component `NonStrictUUID` because it was really confusing having a GroupID use the HostID component (and description) for its schema. Finally, I've removed the endpoint that GETs a single group, since it's redundant and clashes with our current …
=> feat(ESSNTL-3712): Create endpoint to remove hosts from group

api/filtering/filtering.py, api/host.py, api/tag.py, tests/test_tags.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-4399](https://issues.redhat.com/browse/ESSNTL-4399), [ESSNTL-4405](https://issues.redhat.com/browse/ESSNTL-4405), and [ESSNTL-4402](https://issues.redhat.com/browse/ESSNTL-4402):
- It allows for the start and end dates to be equal
- It fixes the bulk-delete validation so it also considers updated_start and updated_end
- It adds exception handling to the `GET /tags` to convey a useful message in case of user error
This follows up on the original updated_start and updated_end PR (#1272).
=> fix(ESSNTL-4399, ESSNTL-4405, ESSNTL-4402): Fix updated_start & updated_end edge-cases

.pre-commit-config.yaml, api/tag.py
Update pre-commit hooks and run them to fix the files.
=> Update pre-commit hooks

app/models.py, app/queue/queue.py, lib/host_repository.py, tests/fixtures/mq_fixtures.py, tests/helpers/db_utils.py, tests/helpers/mq_utils.py, tests/helpers/test_utils.py, tests/test_mq_service.py, utils/payloads.py
The new Errata notification reporter will report only a subset of the yum repositories and packages that are reported by insights. 
Currently, HBI performs a shallow merge of system profile facts. So any data below the first level, like yum repos and packages, are overwritten in their entirety. This means that sparse data reported by the Errata notification reporter would overwrite any existing full set of data. Changes need to be made to the system profile update logic to ensure that this doesn't happen.
Toward this end, this PR implements changes to enable the passing of optional arguments to the existing "add_host" operation.
The specific argument implemented here is `defer_to_reporter`, which indicates which reporter's system profile data should have priority over the caller's data. …
=> Implemented operation_args for the add_host operation.

api/group.py, app/instrumentation.py, app/models.py, app/serialization.py, lib/group_repository.py, lib/metrics.py, swagger/api.spec.yaml, swagger/openapi.json, tests/fixtures/api_fixtures.py, tests/fixtures/db_fixtures.py, tests/helpers/api_utils.py, tests/test_api_groups_create.py, tests/test_api_groups_delete.py, tests/test_api_groups_update.py, tests/test_models.py
This PR is being created to address [ESSNTL-3704](https://issues.redhat.com/browse/ESSNTL-3704) and [ESSNTL-4390](https://issues.redhat.com/browse/ESSNTL-4390).
Add the POST /groups endpoint. The payload is as follows:
```
{
"name": "test-host",
"host_ids": []
}
```
`name` is mandatory but `host_ids` can be an empty list.
I have improved the error messages in comparison to the first PR, but I noticed that API is the one that checks if the host_ids are valid based on the spec. In order for the API to accept invalid host_ids (and a group to be created even if the customer sends invalid ids), the spec would have to change.  More details about this issue [here](https://issues.redhat.com/browse/ESSNTL-4390) and [here](https://redhat-internal.slack.com/archives/CQFKM031T/p1676505465420629). I …
=> feat(ESSNTL-3704, ESSNTL-4390): Add POST /groups endpoint

build_deploy.sh
Fixing the build deploy script that was missing a space
None Apply
=> Fixing build deploy script

app/queue/queue.py, rebuild_events_topic.py, tests/test_event_rebuilder.py
Reverts RedHatInsights/insights-host-inventory#1394
=> Revert "Remove DB session from events-topic-rebuilder"

api/host_group.py, tests/test_api_host_group.py
This PR is being created to address [ESSNTL-4930](https://issues.redhat.com/browse/ESSNTL-4930).
Add request body validation and return consistent status code (400) and error message
=> fix(ESSNTL-4930): Validate request body and return consistent error message

rebuild_events_topic.py
This PR is being created to address a potential memory issue with the events-topic-rebuilder script. This re-scopes the DB session so that it contains fewer transactions at once.
=> Update DB session scope in events-topic-rebuilder

tests/test_api_hosts_delete.py
This PR is being made to fix a unit test fixture. The unit tests pass locally, but fail in the PR check. Hopefully changing this fixture will resolve the issue.
=> Fix unit test fixture

api/group_query.py, swagger/api.spec.yaml, swagger/openapi.json, tests/test_api_groups_get.py
This PR is being created to address an openapi issue discovered by @fstavela. It seems like there was some issue with the component references, so I followed an established pattern used by PaginationOut and a few other components.
=> Fix OpenAPI reference issue

migrations/versions/2e3c52165bf0_make_host_groups_non_nullable.py
This PR is being created to make the hosts.groups DB column NOT NULL. The latest changes to the host-synchronizer updated all of the null fields and replaced them with an empty array (`[]`), and that same script is now running in Prod. This DB migration will help us avoid null-related data consistency issues.
=> Make hosts.groups DB column non-nullable

app/models.py, migrations/versions/fc4921790a66_create_account_staleness_culling_table.py, tests/fixtures/db_fixtures.py, tests/helpers/db_utils.py, tests/test_models.py
This PR is being created to address [ESSNTL-5023](https://issues.redhat.com/browse/ESSNTL-5023).
This PR creates the migration script to create the table in the DB, ORM model and add tests to validate it.
=> [ESSNTL-5023] - Create table and ORM model for account_staleness_culling

api/assignment_rule.py, api/assignment_rule_query.py, app/instrumentation.py, app/serialization.py, swagger/api.spec.yaml, swagger/openapi.json, tests/fixtures/api_fixtures.py, tests/helpers/api_utils.py, tests/test_api_assignment_rules_get.py
This PR is being created to address [ESSNTL-4879](https://issues.redhat.com/browse/ESSNTL-4879).
Implemented the GET /assignment-rules/<id> endpoint.
Please note: Given the amount of common files and code, I've included the code from:
https://github.com/RedHatInsights/insights-host-inventory/pull/1415
in this PR, to make it easier to merge them in the future. I hope it doesn't cause confusion.
=> [ESSNTL-4879]: Create GET /assignment-rules/<id> endpoint.

LICENSE.txt
This PR is being created to add a license file. @fpjrh is coordinating with the other teams to see if we should standardize, but we can stick with GPLv2 for now.
=> Add GPLv2 license

swagger/api.spec.yaml, swagger/openapi.json
This PR is being created to address an issue @fstavela noticed and [reported via Slack](https://redhat-internal.slack.com/archives/CQFKM031T/p1692271909666479). It tags the assignment-rules endpoints as "groups", because they're very closely related. It also puts the System Profile validation endpoint in the "system_profile" group, because I didn't like that it was just in the default group.
=> Update OpenAPI tags

deploy/cji.yml, deploy/clowdapp.yml
This PR is being created to address [RHINENG-1401](https://issues.redhat.com/browse/RHINENG-1401).
It adds a new Job which runs only the host_synchronizer script.
=> Add new job for just host_synchronization

deploy/clowdapp.yml
This PR is being created to address [RHINENG-4101](https://issues.redhat.com/browse/RHINENG-4101).
This PR fixes the Job name in the image deployed by the host_synchronizer job.  The correct job name should have hyphens NOT underscore.  The image specified previously referenced the image in which the CJI job name had undercore.  Furthermore, the new job name set in the CJI was not in the image referred.
=> Use August 28, 2023 host-inventory image for CJI

api/account_staleness.py, app/__init__.py, app/instrumentation.py, app/models.py, app/serialization.py, lib/account_staleness.py, swagger/api.spec.yaml, swagger/openapi.json, tests/fixtures/api_fixtures.py, tests/helpers/api_utils.py, tests/helpers/rbac-mock-data/inv-account-staleness-read-only.json, tests/helpers/rbac-mock-data/inv-account-staleness-write-only.json, tests/test_api_account_staleness_create.py
This PR is being created to address [ESSNTL-5037](https://issues.redhat.com/browse/ESSNTL-5037).
Adding `account staleness` POST endpoint
=> feat(ESSNTL-5037): Adding staleness post endpoint

deploy/clowdapp.yml
=> Add rhc_client_id to floorist query

api/account_staleness.py
This PR is being created to address [ESSNTL-5037](https://issues.redhat.com/browse/ESSNTL-5037).
Adding feature flag on create staleness endpoint
=> feat(ESSNTL-5037): adding feature flag on staleness endpoint

app/xjoin.py, swagger/api.spec.yaml, swagger/openapi.json, tests/test_xjoin.py
This PR is being created to address [RHINENG-1642](https://issues.redhat.com/browse/RHINENG-1642).
=> RHINENG-1642: Add sort by group_name to the api code

api/account_staleness.py, app/instrumentation.py, lib/account_staleness.py, swagger/api.spec.yaml, swagger/openapi.json, tests/test_api_account_staleness_update.py
This PR is being created to address [ESSNTL-5039](https://issues.redhat.com/browse/ESSNTL-5039).
Add update endpoint for staleness culling.
=> feat(ESSNTL-5039): Add update endpoint for staleness

lib/feature_flags.py
This PR is being created to address [ESSNTL-5400](https://issues.redhat.com/browse/ESSNTL-5400).
The code was already set up to block requests when the feature flag was turned off, but the feature flag's fallback value was being used. Turns out this was because the wrong feature flag name was being used; updating it to the correct one should fix the issue.
=> feat(ESSNTL-5400): Fix assignment-rules feature flag

Pipfile.lock
This PR is to update the `pipfile.lock` to apply minor code dependency updates.
=> Minor Code Deps Updates

api/assignment_rule.py, api/assignment_rule_query.py, app/instrumentation.py, swagger/api.spec.yaml, swagger/openapi.json, tests/helpers/api_utils.py, tests/test_api_assignment_rules_get.py, tests/test_api_facts.py, tests/test_api_hosts_update.py
This PR is being created to address [RHINENG-1695](https://issues.redhat.com/browse/RHINENG-1695).
It implements the following:
- fix RBAC attributeFilter check
- remove option to sort results by account and org_id
- add RBAC attributeFilter test
- remove assignments to unused variables
- remove manual url creation in tests
- rename `test_get_assignment_rule_with_bad_name`
- substitute "assignmentrule" for "assignment_rule" which is the name convention
- capitalize log message
=> fix(RHINENG-1695): GET /assignment-rules follow-ups

api/staleness.py
This PR is being created to address [ESSNTL-5422](https://issues.redhat.com/browse/ESSNTL-5422).
Improving error messages on staleness endpoint
=> fix(ESSNTL-5422): Improve error message

Dockerfile, Makefile, README.md, deploy/clowdapp.yml, docs/running_special_job.md, unit_test.sh, utils/deploy.py
This PR is being created to address an issue with failing image build. The build fails, because it can't find `python`.
More info here: https://redhat-internal.slack.com/archives/C022YV4E0NA/p1700034021351159
=> Update python commands in Dockerfile

api/segmentio.py, tests/test_segmentio.py
This PR is being created to address [RHINENG-3405](https://issues.redhat.com/browse/RHINENG-3405).
We're currently sending an event for every Inventory API call whether it's from UI, CLI, or command line tool but the only events that we actually want to see are the requests done through a command line tool(ex. curl). This means we're sending millions of events to Segment that we are not actually using and are not providing any business value. The total monthly event limit for all Red Hat sources is 150 million per month and our Red Hat Insights API - Prod itself is sending about 2.5 million events per day. 
We need to filter these events in the code where we are doing the track call so that we are only sending the necessary events. The only events that we need to track in Segment are API …
=> fix(RHINENG-3405): limit API events sent to Segment

swagger/openapi.json, swagger/system_profile.spec.yaml, swagger/system_profile_commit_id
This PR is being created to address [RHINENG-3403](https://issues.redhat.com/browse/RHINENG-3403).
It syncs the changes from [inventory-schemas PR 121](https://github.com/RedHatInsights/inventory-schemas/pull/121) to HBI.
=> chore(RHINENG-3403): Update System Profile

system_profile_validator.py
This PR is being created to address [RHINENG-3402](https://issues.redhat.com/browse/RHINENG-3402).
It refactors `system_profile_validator` in order to consolidate `_does_pr_require_validation`, which allows the job to re-check the PR it's validating before posting a comment.
There's more info in the Jira, but this is needed because it takes over an hour to run the full validation. After an hour, a new validator is spun up and does not see a comment from itself (dippy-bot), so it runs a new validation; this happens a few times. Then, each of the running jobs posts a comment to the PR as it finishes its validation. This PR prevents that by simply checking the PR again right before posting the comment. …
=> fix(RHINENG-3402) Stop sp-validator from posting multiple comments in a row

dashboards/grafana-dashboard-insights-inventory-msk.configmap.yaml
This PR is being created to address [RHINENG-2397](https://issues.redhat.com/browse/RHINENG-2397).
It adds a new Grafana Dashboard showing metrics from MSK.  Host-inventory appears to be the first service using MSK for Grafana, which means the panels in this dashboard may change in future.
=> RHINENG-2397: 

app/config.py, tests/test_api_staleness_get.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-5604](https://issues.redhat.com/browse/ESSNTL-5604).
Update custom staleness defaults for edge systems
=> chore(ESSNTL-5604): Update custom staleness defaults for edge systems

api/filtering/filtering.py, app/xjoin.py, tests/helpers/graphql_utils.py, tests/test_tags.py, tests/test_xjoin.py
Reverts RedHatInsights/insights-host-inventory#1551
=> Revert "fix(RHINENG-3425) Fix dict & tuple mismatches"

lib/host_synchronize.py
This reverts commit 328674b4503a9b9cb5672c85ca462e2425c35018.
=> Revert "hot-fix(RHINENG-4855): Add expection to write_event (#1560)"

deploy/clowdapp.yml
This PR is being created to address [RHINENG-5364](https://issues.redhat.com/browse/RHINENG-5364)
=> chore(RHINENG-5364) Perform DB downgrade in stage

lib/host_synchronize.py
=> hotfix(RHINENG-4856): Add expection to host synchronizer

docs/connect_to_k8s_env.md
This PR is being created to address [RHINENG-6138](https://issues.redhat.com/browse/RHINENG-6138).
=> Add missing steps to README for creating elasticsearch index

app/auth/identity.py, tests/helpers/test_utils.py, tests/test_identity_schema.py
This PR is being created to address [RHINENG-5479](https://issues.redhat.com/browse/RHINENG-5479).
It adds the Identity type `ServiceAccount` and updates tests.
=> feat(RHINENG-5479): Update API to handle Service Account type

.gitignore, .unleash/create_unleashdb.sql, .unleash/flags.json, README.md, api/host.py, app/__init__.py, app/config.py, dev.yml, lib/feature_flags.py
* Add feature flag and fall back
* Add a custom strategy so the feature can be applied only to select orgs for testing
=> Add hbi.api.disable-xjoin feature flag

api/host.py, api/host_query_db.py, dev.yml, lib/host_repository.py, run_gunicorn.py, tests/test_tags.py
This PR is being created to address [RHINENG-7074](https://issues.redhat.com/browse/RHINENG-7074).
* Add feature flag check to enable query via posgtres instead of xjoin
* Add a get_host_tags_list_by_id_list function using only sqlalchemy leveraging existing functions
* Add validation checks to keep behavior consistent with xjoin experience
* Update existing get_host_list_by_id_list_from_db function to allow you to specify columns to return instead of the entire model (minimizing the amount of data that needs to be extracted and returned from the DB when possible)
* Add some unit test cases that call the API with the feature flag enabled allowing testing of the postgres flow
* Update docker-compose better kafka integration
* Update run_gunicorn to use hot reloads for easier development …
=> [RHINENG-7074] Convert GET /hosts/{host_id_list}/tags/count endpoint from XJoin to DB

deploy/testing-integration.yml
We want to have a debug version of the SaaS file that would run a different command in the container. So the args needs to be parametrized.
The related MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/94999
=> Turn container args into a parameter for testing integration

lib/middleware.py, tests/helpers/test_utils.py, tests/test_api_auth.py, tests/test_unit.py
This PR is being created to address [RHINENG-5479](https://issues.redhat.com/browse/RHINENG-5479).
Adds Service account to the list of identities that goes throught rbac.
=> Update api service account

api/host.py, tests/test_api_hosts_get.py
This PR is being created to address [RHINENG-7071](https://issues.redhat.com/browse/RHINENG-7071).
This adds the DB implementation of GET /hosts/{id_list}. The main filtering logic was implemented in #1609.
=> feat(RHINENG-7071): Implement DB version of GET /hosts/{id_list}

api/host_query_db.py, api/system_profile.py, tests/test_system_profile.py
This PR is being created to address [RHINENG-7077](https://issues.redhat.com/browse/RHINENG-7077).
* Add feature flag and new DB based call to API
* Create new DB query aggregation on sap_system value
* Add new test case to create sap_system entries and compare aggregation for true/false values
=> Convert GET /system_profile/sap_system endpoint from XJoin to DB

swagger/api.spec.yaml, swagger/openapi.json
This PR is being created to address [RHINENG-7754](https://issues.redhat.com/browse/RHINENG-7754).
Adds "satellite" and "discovery" (and their negations) to the allowed values when filtering by reporter.
=> fix(RHINENG-7754) Add satellite & discovery to reporter filter

api/host_query_db.py, api/system_profile.py, tests/test_system_profile.py
This PR is being created to address [RHINENG-7076](https://issues.redhat.com/browse/RHINENG-7076).
* Add unleash flag condition and call to postgres based query method
* Add sap_sids aggregation function with search support
* Add test cases with and without search for systems primed with sap_sid values in system profile
=> Convert GET /system_profile/sap_sids endpoint from XJoin to DB

migrations/versions/727301ac6483_add_gin_for_operating_system.py
This PR is being created to address [RHINENG-5459](https://issues.redhat.com/browse/RHINENG-5459).
It creates a GIN for the operating_system name using CONCURRENTLY. We can merge this after perf testing is complete (provided the results are acceptable).
=> perf(RHINENG-5459) Add GIN for operating_system

api/host_query_db.py, api/tag.py, tests/test_tags.py
This PR is being created to address [RHINENG-7078](https://issues.redhat.com/browse/RHINENG-7078).
* Add unleash flag in tags API
* Introduce new call to the get_tag_list_db function
* Created function for order_by params for tags
* Created function utilizing query_filters function to collect all distinct namespaces, keys, and values along with the associated count
* Introduced regex querying for tags across namespaces, keys, and values
* Enabled ordering by alpha or by count
=> Convert GET /tags endpoint from XJoin to DB

tests/test_api_host_group.py
* Allow tests to pass ignoring cases like leap day
=> feat: Handle leap day test issue

Makefile, README.md
* Update README docs
* Add make target to simplify
* Update README docs
* Add make target to simplify
=> docs(db): Update migration creation flow with new flask version

Makefile, api/filtering/db_filters.py, tests/test_api_hosts_get.py, tests/test_tags.py
Direct transformation of logic from filtering.py into sqlalchemy filter SQL
https://github.com/RedHatInsights/insights-host-inventory/blob/master/api/filtering/filtering.py#L294-L316
https://github.com/RedHatInsights/insights-host-inventory/blob/master/app/xjoin.py#L101-L110
https://github.com/RedHatInsights/insights-host-inventory/blob/master/app/xjoin.py#L145-L171
=> feat(api): Add database support for filter by registered_with

deploy/clowdapp.yml
This PR just makes it so we won't have multiple Reaper jobs running at once (like is happening right now). If the previous job hasn't finished, the new one won't begin.
=> Forbid concurrent Reaper jobs

api/filtering/db_filters.py, tests/test_api_hosts_get.py, tests/test_tags.py
* Direct transformation of logic from filtering.py into sqlalchemy filter SQL
https://github.com/RedHatInsights/insights-host-inventory/blob/master/app/xjoin.py#L91-L98
https://github.com/RedHatInsights/insights-host-inventory/blob/master/app/xjoin.py#L136-L142
=> feat(api): Add database support for filter by staleness

app/models.py, migrations/versions/7c97d8464b6b_add_indexes_for_display_name_and_system_.py
This PR is being created to address [RHINENG-8548](https://issues.redhat.com/browse/RHINENG-8548).
* Add index for display_name from filter and order_by frequency
* Add index for system_profile_facts from filter frequency
=> feat(rhineng-8548): Create new indexes based on query analysis

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [RHINENG-5450](https://issues.redhat.com/browse/RHINENG-5450).
It adds 2 new panels for ratio of failed messages (to produce, due to size) and for size of produced and consumed messages.
=> chore(RHINENG-5450): update grafana dashboard

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [RHINENG-5450](https://issues.redhat.com/browse/RHINENG-5450).
Very small PR to correct the positioning of one panel and shorten the name of the other for better visibility.
=> fix(RHINENG-5450): correct panel location

api/filtering/db_filters.py, tests/test_api_hosts_get.py
* Update fliters to perform case insensitive queries for identified fields.
=> bug(rhineng-9037): Resolve case insensitive filtering issue

migrations/versions/7c97d8464b6b_add_indexes_for_display_name_and_system_.py
This PR is being created to address the DB issue we're seeing in Prod.
=> Hotfix: Remove groups GIN from newest migration

migrations/versions/7c97d8464b6b_add_indexes_for_display_name_and_system_.py
This PR is being created to remove the System Profile index from the latest DB migration.
=> Remove SP index from latest migration

unit_test.sh
=> refactor(dev): update postgresql-rds image tag

tests/test_api_hosts_delete.py, tests/test_api_hosts_get.py
This PR is being created to fix some unit tests:
- Fixed a magicmock that was breaking because it was missing a return value
- Removed a couple test parametrizations that were pushed early
=> Fix unit tests

api/host_query_db.py, tests/test_tags.py
* Update subqueries to remove distinct to resolve counts
* Update subqueries to add consistent label naming to enforce search query
* Added test to make sure negative search case is covered.
=> bug(rhineng-9037): Fix subquery labeling to clean up search and count properly

unit_test.sh
This PR fixes a quoting typo, and applies suggestions from [Shellcheck](https://www.shellcheck.net/), applies formatting.
=> Small patch

api/filtering/db_custom_filters.py, api/filtering/db_filters.py, api/filtering/filtering_common.py, api/host_query_db.py, tests/test_api_hosts_delete.py, tests/test_api_hosts_get.py, tests/test_system_profile.py
This PR is being created to address the most recent bugs identified in [RHINENG-9037](https://issues.redhat.com/browse/RHINENG-9037):
- If you use /hosts/<hosts_ids> and no hosts are found, it now returns HTTP 200 with an empty list instead of HTTP 404.
- If you filter on multiple values for an array-type field, it now uses "AND" logic.
- If you don't include an operator when filtering on an array-type field, it uses "contains" implicitly.
- If you filter on operating_system with multiple range operations (gt, lt, etc), it combines those using "AND".
- If you filter on operating_system without including a minor version, it now uses the appropriate logic to ignore the minor version (the logic is a bit complicated, but I documented it pretty thoroughly).
- If you filter on an integer field …
=> fix(RHINENG-9037) More XJoin migration bugfixes

swagger/openapi.json
This PR is being created to address [RHINENG-8706](https://issues.redhat.com/browse/RHINENG-8706).
Improves code 200 descriptions for `PATCH /groups/{group_id}` and `POST /groups/{group_id}/hosts` to point out the changes might have already been made.
=> perf(RHINENG-8706): improve api docs

.gitignore, Dockerfile, dev.dockerfile, pg_repack.dockerfile
This PR is being created to address the credentials leak. It replaces the instances of `COPY . .` with a bunch of explicit copy commands, and adds to the .gitignore.
=> Replace COPY . ., add to .gitignore

api/host_query_db.py
* Reduce burden on DB as current implementation is impacting DB performance
* Perform the search and pagination functionality in python code
=> bug(rhineng-9037): Perform tag API functionality in python

.dockerignore, .gitignore
This PR is being created to address [RHINENG-9437](https://issues.redhat.com/browse/RHINENG-9437).
Adds .dockerignore, removes entries from .gitignore.
=> Add .dockerignore

api/host_query_db.py
* The aggregation and subquery are slow performing query in DB
* Regex will be simpler to perform in python
=> perf: perform regex and count of sap_sids in python

api/host_query_db.py
This PR moves the aggregation & counting of results for the `/system_profile/operating_system` endpoint to python, instead of using a SQL subquery.
=> perf: aggregate & count operating_system results in python

api/host_query_db.py
This PR is being created to test for performance improvements when using flask-sqlalchemy's db.session.query instead of model.query.
=> perf: Use db.session.query instead of model query 

app/config.py
This PR is being created to increase the SQLAlchemy pool size. I'll observe the changes in metrics and revert this if appropriate.
=> perf: Increase SQLAlchemy pool size to 15

api/host_query_db.py
Closes DB sessions after doing API queries. Seeing if this helps reduce the number of active connections overall.
=> Close sessions when finished querying

api/host_query_db.py, api/system_profile.py
* Use sqlalchemy paginate built-in method to get data and total, should eliminate a query to the db
=> feat(perf): Use sqlalchemy paginate built-in method to get data and total

api/filtering/db_custom_filters.py, tests/test_api_hosts_get.py
This PR is being created to address [RHINENG-9707](https://issues.redhat.com/browse/RHINENG-9707).
* Handle case where the spec level is the object and not a field.
=> bugfix(rhineng-9707): Handle system_profile queries with operations against the object

migrations/versions/091e613af3d9_add_index_support_for_bootc_queries.py
* Add an new index to better support bootc queries
=> feat(perf): Introduce index for bootc queries

api/host_query_db.py, app/models.py, app/serialization.py
* This change means the tags column will no longer be selected (it is not used)
* This change means the system_profile_facts column will only be selected when the fields are being selected
=> feat(perf): Limit columns on list hosts

app/config.py
This PR is being created to address [RHINENG-9832](https://issues.redhat.com/browse/RHINENG-9832), which is discussed in [this Slack thread](https://redhat-internal.slack.com/archives/CCRND57FW/p1713672548525079).
=> chore: Set partition assignment strategy to cooperative-sticky

api/filtering/db_filters.py
Filtering by staleness resulted in redundant checks against host_type. This change refactors the host_type check so it only gets added once per host_type (i.e. once for "edge" and once for None), rather than 3 times each.
=> perf(RHINENG-9788) Remove redundant host_type filtering

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [RHINENG-5450](https://issues.redhat.com/browse/RHINENG-5450).
This PR fixes a small error in the new `Message sizes` grafana dashboard that was giving incorrect values.
=> fix(RHINENG-5450): Small fix to the previous grafana dashboard

migrations/versions/ea9d9c5cb4e4_add_operating_system_multicolumn_index.py
Adds a new multicolumn index for operating_system. Hopefully this will speed up requests that filter on that field.
=> perf(RHINENG-9788) Add new multicolumn index for operating_system

iqe_rbac_tests.sh, iqe_tests.sh, pr_check.sh, pr_check_common.sh
This PR is being created to address [RHINENG-4648](https://issues.redhat.com/browse/RHINENG-4648).
Add new pipeline into the PR check which will run the RBAC integration IQE tests. I'm creating a new pipeline instead of adding these tests to the existing pipelines, because this way they can run in parallel, not increasing the total amount of time needed for the PR check.
This PR is a followup for this IQE MR: https://gitlab.cee.redhat.com/insights-qe/iqe-host-inventory-plugin/-/merge_requests/1110
This PR has to be merged before the app-interface MR: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/107201
=> [RHINENG-4648] Add PR check pipeline with RBAC integration tests

app/config.py, lib/feature_flags.py
This PR suggests a simpler implementation attempted by https://github.com/RedHatInsights/insights-host-inventory/pull/1765
=> Disable xjoin with minimum changes

Pipfile, Pipfile.lock
=> feat(api): Add redis dependency for backend utilization

api/cache.py, api/host.py, app/queue/queue.py, deploy/clowdapp.yml, host_reaper.py, inv_mq_service.py, lib/host_delete.py
Reverts RedHatInsights/insights-host-inventory#1779
That PR seems to have broken the event producer, which in turn broke Cyndi. It will need another pass and a test before going back in.
=> Revert "feat(api): Enable caching of host APIs with associated cache invalidation"

api/staleness_query.py, app/serialization.py, swagger/api.spec.yaml, swagger/openapi.dev.json, swagger/openapi.json, tests/__init__.py, tests/helpers/api_utils.py, tests/test_api_staleness_update.py
* extract delay type
* consolidate optionals in type specification
* use allOf to compose the types better
* consolidate Per reporter Staleness timestamp type
=> consolidate/correct  openapi types - 

Dockerfile, app/config.py, app/queue/export_service.py, app/queue/metrics.py, app/queue/queue.py, deploy/clowdapp.yml, dev.dockerfile, inv_export_service.py, lib/metrics.py, tests/helpers/export_service_utils.py, tests/test_export_service.py
This PR is being created to address [RHINENG-8714](https://issues.redhat.com/browse/RHINENG-8714).
It created the HBI export-service and consume events from the export-service Kafka topic.
=> feat(RHINENG-8714): Consume events from platform.export.requests

api/host_query_db.py, tests/test_api_hosts_get.py
This PR is being created to address [RHINENG-10674](https://issues.redhat.com/browse/RHINENG-10674).
* Handle case where result has a None value in the response array
=> bugfix(rhineng-10674): Handle None result in operating system query

api/host.py, app/instrumentation.py, app/queue/event_producer.py, app/queue/notifications.py, app/queue/queue.py, app/serialization.py, host_reaper.py, lib/host_delete.py, tests/fixtures/mq_fixtures.py, tests/helpers/mq_utils.py, tests/test_api_hosts_delete.py, tests/test_api_hosts_update.py, tests/test_culling.py, tests/test_custom_staleness.py, tests/test_unit.py
This PR is being created to address [RHINENG-7830](https://issues.redhat.com/browse/RHINENG-7830).
This PR adds notification for deleted systems and updates tests.
=> feat(RHINENG-7830): add system-deleted notification

app/config.py, lib/feature_flags.py
This reverts commit b48cba18901e2d6770bddd9c1b9df4781be9f5f3.
=> Revert "[RHINENG-9943] Fix bypass xjoin flag by config"

app/queue/export_service.py, app/queue/queue.py, deploy/clowdapp.yml, inv_export_service.py, tests/helpers/export_service_utils.py, tests/test_export_service.py
This PR is being created to address [RHINENG-8714](https://issues.redhat.com/browse/RHINENG-8714).
Add resource string, change the app string and simplify the validation logic.
=> feat(RHINENG-8714): add resource string and change app string

app/config.py, lib/feature_flags.py
This PR fixes and simplifies the `bypass_xjoin` by config code applied in #1770.
=> [RHINENG-9943] Fix bypass xjoin flag by config

docs/pull_request_template.md
This PR is being created to add an item to the PR checklist. This new item should help us more thoroughly review changes related to DB queries.
=> Add item to PR template

deploy/clowdapp.yml
=> bugfix(deploy): Alter configmap name to avoid collisions in ephemeral environment

security-scan.sh
This script will provide the same level of support as the standard PlatSec GitHub Workflow, but will run on a RHEL-Based Jenkins Node.
A copy of the [security-scan-source-template.sh](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/jenkins/security-scan-source-template.sh) has been added to this repo, and the (GitHub) `platsec-gh-vulnerability-scan` Jenkins Job has be added to the Host-Inventory `build.yml` in App-Interface.
Similar to the standard GitHub Workflow, we can accommodate feature requests and provide updates on the fly and with full transparency. The `security-scan-source-template.sh` script, which sources the main [security-scan.sh](https://github.com/RedHatInsights/platform-security-gh-workflow/blob/master/jenkins/security-scan.sh) script, allows …
=> Security-Scan Script to Enable Jenkins Security Scan Job

lib/feature_flags.py, tests/test_utils.py
This PR is being created to address [RHINENG-9943](https://issues.redhat.com/browse/RHINENG-9943). 
=> [RHINENG-9943] Fix bypass xjoin flag by config and adds tests

app/models.py, tests/test_models.py
This PR is being created to address [RHINENG-10794](https://issues.redhat.com/browse/RHINENG-10794).
Implemented schema supporting version 1 canonical facts, as described in this [doc](https://docs.google.com/document/d/1-4hYT_sVLWQ98SWvCkT96rTX3zlw_8w55rnk4XKx0l4/edit?usp=sharing).
The original schema is designated version 0. The new schema supports both versions 0 and 1.
All reporters using schema versions > 0 must specify the **canonical_fact_version** fact specifying the schema version they're using.
=> Implemented versioned CanonicalFactsSchema with initial new version.

api/staleness.py
This PR is being created to address [RHINENG-10926](https://issues.redhat.com/browse/RHINENG-10926).
* Add delete_keys call to staleness CUD APIs
=> bugfix(rhineng-10926): Cache invalidation added to staleness endpoints

deploy/clowdapp.yml
This PR is being created to address [RHINENG-11169](https://issues.redhat.com/browse/RHINENG-11169).
* Remove stanza for the metrics endpoint with empty response
=> bugfix(rhineng-11169): Have nginx pass through the metrics endpoint

.export-service/create_exportdb.sql, .gitignore, Makefile, README.md, dev.yml, example_export_request.json
This PR is being created to address [RHINENG-11187](https://issues.redhat.com/browse/RHINENG-11187).
This PR adds the support of the export-service in order to be able to use the latter locally.
=> feat(RHINENG-11187) Add export-service components to the dev.yml file

api/host_query_db.py, app/auth/identity.py, app/queue/export_service.py, lib/middleware.py, tests/helpers/export_service_utils.py, tests/test_export_service.py
This Pull Request addresses the following JIRA Cards:
- RHINENG-9060
* RHINENG-9824 (Use RBAC filter)
* RHINENG-9825 (Structure database content)
=> feat(RHINENG-9060) Add DB Call Implementation for Export Service

api/host.py, app/queue/events.py, app/queue/queue.py, lib/group_repository.py, lib/host_remove_duplicates.py, lib/host_synchronize.py, tests/helpers/mq_utils.py, tests/test_mq_service.py
This PR is being created to address [RHINENG-9536](https://issues.redhat.com/browse/RHINENG-9536).
=> Populate Kafka header with bootc information.

deploy/clowdapp.yml
* Create new deployment to enable connection to alternate read replica for horizontal scaling
* Add parameters for replica and secret
* Update nginx to use new deployment service
=> feat(api): Update deployment to enable support for addl read replica

app/queue/export_service.py, lib/middleware.py, tests/test_export_service.py
This PR is being created to address [RHINENG-11401](https://issues.redhat.com/browse/RHINENG-11401).
It refactors the RBAC implementation, extracts logical blocks of the code into their own functions, and simplifies its usage within export_service.
=> chore(RHINENG-11401): Refactor RBAC

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [RHINENG-11502](https://issues.redhat.com/browse/RHINENG-11502) and [RHINENG-11339](https://issues.redhat.com/browse/RHINENG-11339).
It does the following:
- Updates the "Request Rate" panel to use a more accurate metric
- Removes the IOPS Burst Balance panel (which was no longer used)
=> fix(RHINENG-11502, RHINENG-11339) Fix Request Rate panel; remove Burst Balance panel

Dockerfile
This PR is being created to address [RHINENG-11481](https://issues.redhat.com/browse/RHINENG-11481).
Supersedes #1838, based on #1837 (by @jpramos123).
Fixes redocly in our PR check.
=> fix(RHINENG-11481): Fix redocly in PR check

api/host_query_db.py, app/culling.py, app/queue/export_service.py, app/serialization.py, tests/helpers/export_service_utils.py, tests/test_export_service.py, utils/json_to_csv.py
This PR is being created to address [RHINENG-9820](https://issues.redhat.com/browse/RHINENG-9820).
It adds a host serializer specific for the export-service and a JSON to CSV parser.
This PR addresses:
- [RHINENG-9820](https://issues.redhat.com/browse/RHINENG-9820)
* [RHINENG-11163](https://issues.redhat.com/browse/RHINENG-11163)
* [RHINENG-9826](https://issues.redhat.com/browse/RHINENG-9826)
* [RHINENG-9827](https://issues.redhat.com/browse/RHINENG-9827)
=> [RHINENG-9820] Structure export content in JSON/CSV

Pipfile, Pipfile.lock
* Update setuptools, certifi, requests
=> feat(deps): Update dependencies from Grype scan

app/__init__.py
* If org_id and access_id are not found then make_key returns None
* Updating processing in the make_key flow for system type auth
```
[2024-07-24 18:55:16,754] [14] [139769392633600] [flask_caching] [ERROR] Exception possibly due to cache backend.
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/flask_caching/__init__.py", line 392, in decorated_function
rv = self.cache.get(cache_key)
File "/usr/local/lib/python3.9/site-packages/cachelib/redis.py", line 72, in get
return self.serializer.loads(self._read_client.get(self.key_prefix + key))
TypeError: can only concatenate str (not "NoneType") to str
```
=> bugfix(api): Resolve None key value when processing System identity for make_key

app/__init__.py
* Disable serving the dev API spec via connection so correct version is available
=> bugfix(api): Serve correct openapi spec

app/queue/export_service.py
This PR is being created to address [RHINENG-11697](https://issues.redhat.com/browse/RHINENG-11697).
This PR fixes constant failures while fetching RBAC Permissions for the export-service:
```
{"@timestamp": "2024-07-25T14:50:11.292Z", "@version": 1, "source_host": "host-inventory-export-service-67d6ff8f67-4ks8q", "name": "inventory.lib.middleware", "msg": "Failed to fetch RBAC permissions: %s", "args": ["Header part (UUID('617092f8-8411-4dae-81fa-0496d894a16d')) from ('x-rh-insights-request-id', UUID('617092f8-8411-4dae-81fa-0496d894a16d')) must be of type str or bytes, not <class 'uuid.UUID'>"], "levelname": "ERROR", "levelno": 40, "pathname": "/opt/app-root/src/app/instrumentation.py", "filename": "instrumentation.py", "module": "instrumentation", "stack_info": null, "lineno": 283, …
```
=> fix(RHINENG-11697) Fix fetching RBAC Permissions failures

api/host.py, api/metrics.py
* Add metric counter
* Add increment when system is found in the cache and being returned
=> feat(api): Add prometheus metric to track cached system hits

iqe_tests.sh
This PR is being created to address [RHINENG-11668](https://issues.redhat.com/browse/RHINENG-11668).
The all tests pipeline often fails without the tests being finished.
=> Extend timeout for 'All tests' pipeline

Pipfile, Pipfile.lock, api/__init__.py, api/segmentio.py, tests/test_segmentio.py
This PR is being created to address [RHINENG-11321](https://issues.redhat.com/browse/RHINENG-11321).
Prevent a flood of Segmentio track calls when we experience a spike in API calls.
=> Add rate limiting for segmentio track calls.

api/cache.py
* Remove simple cache configuration
=> bugfix(cache): Remove simple cache option for development to avoid unintended use

app/queue/queue.py
* Add Unleash flag gating for this capability.
=> feat(cache): Enable mq worker system caching using unleash flag

Dockerfile
* remove older setuptools from image
=> bugfix(image): Remove older setuptools

api/cache_key.py, app/__init__.py, tests/test_api_auth.py, tests/test_utils.py
* Raise exception to enforce stricter cache key requirements
=> feat(cache): raise cache key exceptions

app/__init__.py, tests/helpers/test_utils.py
* If user_id isn't present fall back to username
=> feat(api): Enable alternate user identifier for ephemeral env

api/cache.py, app/queue/queue.py
This PR is being created to add logging to the Redis cache-deletion flow to make Stage tests easier to debug. We can remove some or all of these logs after we identify and fix the issue.
=> Add logging to Redis cache-deletion flow

api/cache.py
This PR is being created to add more logs to debug cache deletion.
=> Extra logs for cache debugging

api/cache.py
This PR is being created to address the cache-deletion issue.
=> Fix CACHE_EXECUTOR.submit call

migrations/versions/11cd38415793_fix_hosts_groups_with_wrong_value_in_db.py
This PR is being created to address [RHINENG-5391](https://issues.redhat.com/browse/RHINENG-5391).
This code is meant to fix the hosts that contains a wrong value for the groups field.
Today some hosts have the value of groups field equal to "{}", which should not be possible.
It is validated that the Host MQ does not accept this value during the host insertion anymore.
The solution is to perform an simple update call to the hosts table, finding the hosts WHERE groups = "{}" and update it to groups = "[]", which is current default state for new hosts that are not associated to any inventory group.
Produced message:
```
[2024-08-12 17:51:33,903] [148030] [139710726680640] [inventory.migrations.11cd38415793_fix_hosts_groups_with_wrong_value_in_db_py] [INFO] Matched rows for UPDATE: 5
``` …
=> fix(RHINENG-5391): Fix hosts groups with wrong value in DB

migrations/versions/dbbecd6bf7d1_fix_hosts_groups_with_wrong_empty_array_.py
This PR is being created to address [RHINENG-5391](https://issues.redhat.com/browse/RHINENG-5391).
Output from my local env
```
[2024-08-20 13:13:23,779] [1197545] [140596029141056] [sqlalchemy.engine.Engine] [INFO] UPDATE hosts SET groups=%(groups)s WHERE hosts.groups = %(groups_1)s
[2024-08-20 13:13:23,779] [1197545] [140596029141056] [sqlalchemy.engine.Engine] [INFO] [generated in 0.00014s] {'groups': '[]', 'groups_1': '"[]"'}
[2024-08-20 13:13:23,780] [1197545] [140596029141056] [inventory.migrations.dbbecd6bf7d1_fix_hosts_groups_with_wrong_empty_array__py] [INFO] Matched rows for UPDATE: 2
[2024-08-20 13:13:23,780] [1197545] [140596029141056] [alembic.runtime.migration] [DEBUG] update 11cd38415793 to …
```
=> fix: DB migration to fix string groups value in DB

api/cache.py
* Update log entry to lessen the potential I/O with thousands of keys being printed.
=> feat(cache): Log delete key count instead of all keys

api/group.py, api/host.py, api/host_group.py, api/staleness.py, api/system_profile.py, api/tag.py, app/queue/queue.py
This PR is being created to address [RHINENG-12085](https://issues.redhat.com/browse/RHINENG-12085).
* Remove API layer caching an only focus on cert-auth system caching
=> bugfix(rhineng-12085): Minimize cache wildcard lookups causing cache pressure

iqe_rbac_tests.sh
This PR is being created to address [RHINENG-12135](https://issues.redhat.com/browse/RHINENG-12135). Require merged  https://gitlab-prod-west.cee.redhat.com/insights-qe/iqe-host-inventory-plugin/-/merge_requests/1195 MR first. 
=> fix(RHINENG-12135): Update iqe marker 'service_accounts' to 'service_account'

lib/host_repository.py
Reverts RedHatInsights/insights-host-inventory#1870
=> Revert "Flag mac_addresses as immutable."

deploy/clowdapp.yml
This PR is being created to address [RHINENG-11960](https://issues.redhat.com/browse/RHINENG-11960).
* Update to the latest nginx container image
=> bugfix(nginx): Update container image tag

app/queue/notifications.py
This PR is being created to address [RHINENG-11885](https://issues.redhat.com/browse/RHINENG-11885).
Make `event_type` hyphenated in all headers/kafka messages.
=> refactor(RHINENG-11885): standardize event_type

api/host_query_db.py, app/config.py, app/queue/export_service.py, tests/test_export_service.py
This PR is being created to address [RHINENG-11833](https://issues.redhat.com/browse/RHINENG-11833).
This PR aims to improve the DB call that is made by the export service.
Today if we have a big amount of hosts for in a account, and we make an export request, the pods are killed because of Out Of Memory (OOM) issue.
Using batched queries would reduce the chances of breaking the pods.
I'm proposing using `yield_per` from [SQLAlchemy](https://docs.sqlalchemy.org/en/20/core/connections.html#streaming-with-a-fixed-buffer-via-yield-per)  to address this change and the use of generators for serialize each host individually. This would reduce the memory used, as the serialized data is reduced compared to the data that is fetch from the DB. …
=> feat(performance): Use batched queries to improve DB call performance 

api/host_query_db.py, app/serialization.py, tests/helpers/export_service_utils.py, tests/test_export_service.py
This PR is being created to address [RHINENG-11769](https://issues.redhat.com/browse/RHINENG-11769).
This commit adds a new host serializer specifically for the exp-svc feature.
Example:
```
{'display_name': 'b1280d.foo.redhat.com',
'group_id': None,
'group_name': None,
'host_type': 'conventional',
'host_id': '937c265c-53a3-40c5-9a83-cbc5bf913a27',
'fqdn': 'b1280d.foo.redhat.com',
'os_release': 'Red Hat EL 7.0.1',
'satellite_id': None,
'state': 'fresh',
'subscription_manager_id': None,
'updated': '2024-08-07T12:09:54.867575+00:00',
'tags': [{'key': 'key3', 'namespace': 'NS1', 'value': 'val3'},
{'key': 'key3', 'namespace': 'NS3', 'value': 'val3'},
{'key': 'prod', 'namespace': 'Sat', 'value': None},
{'key': 'key', 'namespace': 'SPECIAL', 'value': 'val'}]}
```
You can find documentation on …
=> fix(RHINENG-11769) Fix Export Data Field names and add some new

api/host_query_db.py
This PR is being created to deliver a minor fix for [RHINENG-11709](https://issues.redhat.com/browse/RHINENG-11709).
Adds single-quotes around the insights ID in an error log for consistency.
=> fix(RHINENG-11709) Update error log for consistency

app/queue/export_service.py, tests/test_export_service.py
This PR is being created to address [RHINENG-11863](https://issues.redhat.com/browse/RHINENG-11863).
This fixes the issue that was allowing user without host-read to export hosts from inventory. Now it raises an exception when the user does not have the correct permission and fails the export request. 
=> fix(RHINENG-11863): User without host read permission is able to export hosts

Dockerfile, dev.dockerfile, pg_repack.dockerfile
This PR is being created to address [RHINENG-12237](https://issues.redhat.com/browse/RHINENG-12237).
* Update container files to use ubi9 minimal image
* Update references for previous el8 items
=> feat(rhineng-12237): Update container files for ubi9 minimal

Dockerfile, dev.dockerfile, pg_repack.dockerfile
Reverts RedHatInsights/insights-host-inventory#1938
=> Revert "feat(rhineng-12237): Update container files for ubi9 minimal"

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [RHINENG-11340](https://issues.redhat.com/browse/RHINENG-11340).
- add a new datasource
- update the `incoming message rate` panel title and query according to devprod instructions ([slack thread](https://redhat-internal.slack.com/archives/CQFKM031T/p1725293818372129?thread_ts=1725293753.960369&cid=CQFKM031T))
- add a `outgoing byte rate` panel
=> fix(RHINENG-11340): 'incoming message rate' showing no data

app/queue/export_service.py, app/queue/queue.py
This PR is being created to address [RHINENG-11863](https://issues.redhat.com/browse/RHINENG-11863).
It fixes an error handling that was failing in the code.
=> fix(RHINENG-11863): Fix error handling

iqe_tests.sh
This PR is being created to address [RHINENG-12645](https://issues.redhat.com/browse/RHINENG-12645).
The all-tests pipeline now takes just about an hour or less, so we don't need a workaround for the pipeline getting stuck anymore.
=> Update all-tests pipeline

app/models.py, deploy/clowdapp.yml
This PR is being created to address [RHINENG-12923](https://issues.redhat.com/browse/RHINENG-12923).
* Provide current default of the "public" schema with a env variable to alter the reference for testing purposes
* Update the Model objects so that foreign keys and relationships specify the schema
The intent is to allow for testing after a manual migration, before writing the migration code.
=> feat(rhineng-12923): Update model objects to allow for db schema to be specified

app/instrumentation.py, app/queue/queue.py, tests/helpers/mq_utils.py
This PR is being created to add more logging for consumed MQ messages.
=> Log partition and offset for consumed messages

README.md, app/config.py, app/queue/notifications.py, deploy/clowdapp.yml, tests/helpers/mq_utils.py
This PR is being created to address [RHINENG-12212](https://issues.redhat.com/browse/RHINENG-12212).
- sets `CONSOLEDOT_HOSTNAME` for creating the host url
=> fix(RHINENG-12212): fix host_url in notification

app/instrumentation.py
This PR is being created to address a bug introduced by #1967.
=> Fix request_id reference

api/host_query_db.py
This PR is being created to address [RHINENG-12481](https://issues.redhat.com/browse/RHINENG-12481).
It refact `_find_all_hosts` method, and split it into two methods, the old one, and one that is specifically used by `export service`.
I tried to keep everything into one method `_find_all_hosts` but there is a label called `host_type` in the `DEFAULT_COLUMNS` variable that do not allow to use `query.options(load_only(*columns))`. 
=> refact(RHINENG-12481): Refact _find_all_hosts function

deploy/clowdapp.yml
This PR is being created to address [RHINENG-13646](https://issues.redhat.com/browse/RHINENG-13646).
* update image tag for nginx deployment
=> feat(rhineng-13646): Update nginx version to tag 1-30

deploy/clowdapp.yml
rh-pre-commit.version: 2.2.0
This PR is for [RHINENG-12228](https://issues.redhat.com/browse/RHINENG-12228) to fix the new floorist queries which prevented them from collecting data to populate S3 buckets.
=> RHINENG-12228: Fix the new floorist queries

deploy/clowdapp.yml
rh-pre-commit.version: 2.2.0
This PR is being created to address [RHINENG-12228](https://issues.redhat.com/browse/RHINENG-12228).
=> Fix the floorist query prefix to use "hms_analytics"

deploy/clowdapp.yml, migrations/versions/1e276ea9970d_create_hbi_schema_and_move_tables.py
This PR is being created to address [RHINENG-13808](https://issues.redhat.com/browse/RHINENG-13808).
* Create migration with schema creation and move tables to new schema
* Update deployment to use new schema location for data tables
=> feat(rhineng-13808): Migrate data from public schema to hbi schema

app/models.py, tests/fixtures/app_fixtures.py
This PR is being created to address [RHINENG-13808](https://issues.redhat.com/browse/RHINENG-13808).
* Change default post data migration
=> feat(rhineng-13808): Default schema config to hbi after migration

deploy/clowdapp.yml
This PR is being created to address [RHINENG-13492](https://issues.redhat.com/browse/RHINENG-13492).
* Update ephemeral environments to use PG 16
=> feat(rhineng-13492): Set clowdapp database version to 16

app/queue/notifications.py
This PR is being created to address [RHINENG-10451](https://issues.redhat.com/browse/RHINENG-10451).
=> fix(RHINENG-10451): fix schema inconsistencies

migrations/env.py
This PR is being created to address [RHINENG-13958](https://issues.redhat.com/browse/RHINENG-13958).
The change to the alembic table rolls back without this COMMIT call.
=> fix(RHINENG-13958) Hotfix to commit changes to alembic table

.pre-commit-config.yaml
This PR comments out the redocly pre-commit step that's currently breaking. We will uncomment this once we have identified and fixed the issue.
=> Temporarily comment out redocly

deploy/clowdapp.yml
This PR is being created to address [RHINENG-14862](https://issues.redhat.com/browse/RHINENG-14862).
* Update image tag to latest
=> Update nginx deployment to use 1-37.1735831629

tests/test_host_mq_service.py, tests/test_payload_tracker.py, tests/test_tags.py
=> Fix ruff ARG errors

renovate.json
=> Tell Renovate to ignore updates into Pipfile

deploy/clowdapp.yml
This PR can be considered a part of [RHINENG-15237](https://issues.redhat.com/browse/RHINENG-15237).  It adds two types of queries to the `host-inventory-hms` FloorPlan.  The first type of queries with names like `${ENV_NAME}/hosts|groups` collect raw data from the database.  The collected raw will then be used to compute metrics.  The implementation of computing metrics ourselves is expected to take sometime.  
The second type queries with names  `${ENV_NAME}/hosts_metrics|groups_metrics` collect the actual numbers/metrics that has been collected manually every week.  These numbers are ready for generating charts/html files.  Having these queries run my Floorist should save us time needed for running the Gabi queries …
=> Add to FloorPlan gabi queries to avoid running them manually

.pre-commit-config.yaml, renovate.json
This PR is being created to address [issue #2204](https://github.com/RedHatInsights/insights-host-inventory/issues/2204).
It fixes `renovate.json` by removing a comma and also adds the `check-json` pre-commit hook to prevent similar issues in the future. I ran the pre-commit before fixing the JSON file and it correctly identified that it was malformed. Here is the output:
```
trim trailing whitespace.................................................Passed
fix end of files.........................................................Passed
check yaml...............................................................Passed
check json...............................................................Failed
- hook id: check-json
- exit code: 1
renovate.json: Failed to json decode (Expecting value: line 5 …
```
=> Fix renovate.json and add 'check-json' pre-commit hook

deploy/clowdapp.yml, inv_publish_hosts.py, lib/metrics.py
This PR is being created to address [RHINENG-14720](https://issues.redhat.com/browse/RHINENG-14720).
=> RHINENG-14720: Add metrics for hosts syndication

Dockerfile, dev.dockerfile
This PR is being created to address [RHINENG-12237](https://issues.redhat.com/browse/RHINENG-12237).
=> (RHINENG-12237) Migrate from ubi8-minimal to ubi9-minimal

.tekton/host-inventory-pull-request.yaml, .tekton/host-inventory-push.yaml
- https://github.com/konflux-ci/build-definitions/blob/main/task/sast-coverity-check-oci-ta/0.2/MIGRATION.md
- https://github.com/konflux-ci/build-definitions/blob/main/task/coverity-availability-check-oci-ta/0.2/MIGRATION.md
=> Manual konflux migration

deploy/clowdapp.yml
This PR is being created to address [RHINENG-15850](https://issues.redhat.com/browse/RHINENG-15850).
* Bump nginx version
=> RHINENG-15850: Update nginx to 124:1-38

app/queue/notifications.py
This PR is being created to address [RHINENG-15175](https://issues.redhat.com/browse/RHINENG-15175).
Removes headers that have `None` as value before sending the notification
=> feat(RHINENG-15175): remove unnecessary fields from notification header

inv_publish_hosts.py
This PR is being created to address [RHINENG-14838](https://issues.redhat.com/browse/RHINENG-14838).  This PR increments the publication success metrics every time the syndication job runs and finds the DB publication.
=> RHINENG-14838: Log success every time the publication is found

app/models.py, migrations/versions/286343296975_add_ungrouped_workspaces_table.py
This PR is being created to address [RHINENG-15817](https://issues.redhat.com/browse/RHINENG-15817):
- Adds the ungrouped_workspaces table ([RHINENG-15826](https://issues.redhat.com/browse/RHINENG-15826))
- Adds workspace_name and workspace_id columns to the hosts table ([RHINENG-15824](https://issues.redhat.com/browse/RHINENG-15824))
- Adds indexes for workspace_name and workspace_id to the hosts table ([RHINENG-15825](https://issues.redhat.com/browse/RHINENG-15825))
- Adds indexes for name and org_id to the ungrouped_workspaces table ([RHINENG-15825](https://issues.redhat.com/browse/RHINENG-15825))
=> feat(RHINENG-15817): Add DB table, columns, indexes

.github/dependabot.yml
In case you missed it, GitHub Actions is introducing a number of breaking changes starting this March/April, including end of support of the ubuntu-20 runner image and deprecation of certain workflow actions.
https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/
This PR adds the GitHub Actions to the Dependabot tool in order to maintain them automatically up to date.
This PR is being created to address [RHINENG-15965](https://issues.redhat.com/browse/RHINENG-15965).
=> RHINENG-15965: Add GH Actions to Dependabot

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [RHINENG-14838](https://issues.redhat.com/browse/RHINENG-14838).
This PR fixed errors in kibana and prometheus queries.
=> RHINENG-14838: Fixed grafana and prom queries.

.tekton/host-inventory-pull-request.yaml, .tekton/host-inventory-push.yaml
This reverts commit 8f1743ac4caaed25b43220cf19ca165275d87d4d.
=> Revert "chore(deps): update konflux references (#2315)"

generate_stale_host_notifications.py
This PR is being created to address [RHINENG-15972](https://issues.redhat.com/browse/RHINENG-15972).
- Use count() to get the total number of records we'll process
- Use yield_per() so that we only load in 500 hosts at a time
- Swap around some logic for clarity
- Reraise the exception if thrown so we don't lose the stacktrace
=> fix(RHINENG-15972) Fix OOM in stale notification job

Pipfile.lock, dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [RHINENG-14838](https://issues.redhat.com/browse/RHINENG-14838).
=> Fix the sydication metric property

api/filtering/db_filters.py, api/host.py, api/host_query.py, api/host_query_db.py, api/staleness.py, api/staleness_query.py, api/system_profile.py, app/queue/host_mq.py, app/serialization.py, generate_stale_host_notifications.py, host_reaper.py, lib/group_repository.py, lib/host_repository.py, utils/payloads.py
This PR is being created to address [RHINENG-16421](https://issues.redhat.com/browse/RHINENG-16421).
Does some refactoring that's blocking Kessel Phase 0. Includes the following:
- Removes the `get_current_identity()` fallback from`get_staleness_obj()`, because that breaks unless you're in an API context
- Refactors staleness-related functions to require org_id rather than Identity
- Remove some uses of `create_mock_identity_with_org_id`, which was only required for structural reasons (the org_id is the only part of the identity that was actually used)
- Sets `"org_id": "test"` in payloads.py to match the README so as not to confuse new developers. The currently-used org_id does not match the b64 identity header in the README, so contributors currently create hosts using the kafka …
=> chore(RHINENG-16421) Use org_id rather than Identity for staleness functions

app/models.py
This PR is being created to address [RHINENG-15447](https://issues.redhat.com/browse/RHINENG-15447).
- fix a case where the host doesn't have anything in `tags_alt` and a tag has to be deleted.
=> fix(RHINENG-15447): fix delete tags_alt

deploy/clowdapp.yml
This PR is being created to address [RHINENG-16634](https://issues.redhat.com/browse/RHINENG-16634).
* Move to latest nginx image
=> feat(rhineng-16634): Update nginx image

logconfig.yaml
This PR is being created to address [RHINENG-15778](https://issues.redhat.com/browse/RHINENG-15778).
The cause of the duplication was that we were using the same handler `logstash` in the `root` and `inventory` logger, and also propagating (propagate was set to `true`) the log from `inventory` to its parents loggers, in this case the `root` logger.
A suggestion from Python logging module is to attach the `handlers` only to the `root` logger, and set `propagate=True` in the child loggers[1]
[1] https://docs.python.org/3/library/logging.html#logging.Logger.propagate
Before the change:
```
[2025-03-18 16:18:13,035] [1001699] [140513069859520] [inventory.app.config] [INFO] Insights Host Inventory Configuration:
[2025-03-18 16:18:13,035] [1001699] [140513069859520] [inventory.app.config] …
```
=> fix: Fix duplicate logging

host_reaper.py
This PR is being created to address [RHINENG-16901](https://issues.redhat.com/browse/RHINENG-16901).
Meanwhile, prevent rhsm-system-profile-bridge hosts to be culled and deleted by host-reaper.
=> adhoc: prevent rhsm-system-profile-bridge to be culled an deleted

migrations/versions/837d2ee7bbd8_add_last_check_in_column_to_host_table.py
Revert the table migration, and just add the column to the table.
=> adhoc: add last_check_in column, but do not update hosts

.tekton/host-inventory-pull-request.yaml, .tekton/host-inventory-push.yaml
This PR is being created to address the new Conforma (Enterprise Contract) requirements we have from April 1st.
Having this task included is necessary to keep building with Konflux after that date.
[RHINENG-17041](https://issues.redhat.com/browse/RHINENG-17041) and [KONFLUX-2264](https://issues.redhat.com/browse/KONFLUX-2264)
We had this task already, but it was requiring a wrong bundle, so running diferent task then it stated.
=> ci: Add required sast task

inv_publish_hosts.py, migrations/versions/f94ada908824_use_pkey_idx_for_replica_identity.py
This PR is being created to address [RHINENG-15712](https://issues.redhat.com/browse/RHINENG-15712).
- Create new publication with versioned name
- Define columns to replicate
- Remove filtering as this doesn't function when columns are specified
- Define mechanism for dropping a publication
=> feat(rhineng-15712): Create versioned publication with explicit columns

utils/payloads.py
=> fix: update payload file

app/queue/host_mq.py, tests/helpers/mq_utils.py
Debeizum kafka event contains payload in envelope(which needs to be processed by consumer): 
```
{
"schema": {
"type": "string",
"optional": false,
"name": "io.debezium.data.Json",
"version": 1
},
"payload": "{\"org_id\": \"123456789\", \"operation\": \"update\", \"workspace\": {\"id\": \"01958ebd-3c61-74b3-86a3-d235b6b62010\", \"name\": \"My Workspace\", \"type\": \"standard\", \"created\": \"2022-07-25T14:30:00Z\", \"modified\": \"2022-08-01T12:00:00Z\"}}"
}
```
Another changes is about datetime columns:
created_at -> created
update_at -> modified
=> Parse debezium envelope in workspace consumer

dev.yml
This PR is being created to address dev experience.
* Current image will pull down a version 17 image of postgres
* We should align development with the production DB instance
=> feat(dev): Specify postgres version for podman compose setup

deploy/clowdapp.yml
This PR is being created to address [RHINENG-17432](https://issues.redhat.com/browse/RHINENG-17432).
* Bump the version of nginx deployed to 1-39.1741813445
=> feat(rhineng-17432): Update image tag for nginx

lib/group_repository.py
This PR is being created to address [RHINENG-18586](https://issues.redhat.com/browse/RHINENG-18586).
Tweaks the DB session usage in the DELETE /groups API flow.
=> Tweak session usage

lib/group_repository.py
Reverts RedHatInsights/insights-host-inventory#2665
Memory usage appeared to be the same as before.
=> Revert "Tweak session usage"

api/group.py
This PR is being created to address [RHINENG-18586](https://issues.redhat.com/browse/RHINENG-18586).
Adds debug logs to the delete_groups flow, to hopefully narrow down the memory usage issue.
=> chore(RHINENG-18586) Add debug logs for memory usage

.hermetic_builds/add_manual_build_dependencies.sh, .hermetic_builds/generate_requirements_build.sh, mk/hermetic_builds.mk
We've created the PR with wrong paths :) Almost there.
=> chore: Correct the path for the manual pip dependencies
