insights/settings.py, inventory/auth.py, inventory/tests.py
Created an authentication [middleware](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:dummy_http_auth?expand=1#diff-03dda6e671f3e8c6185e73dd813c5446R10), that rejects every request that doesn’t contain the _x-rh-identity_ header. This header can currently contain anything for it to pass the validation. This is a stub for an actual header parsing and verification.
The authentication applies to the Django REST API UI too, so I made this to be used only outside the _DEBUG_ mode.
```bash
$ curl -I 'http://localhost:8000/api/' 
HTTP/1.1 403 Forbidden
…
```
```bash
$ curl -I -H 'x-rh-identity: something' 'http://localhost:8000/api/'
HTTP/1.1 200 OK
…
```
I’d like to ask @dehort for a review.
=> Use a dummy authentication middleware

migrations/README, migrations/alembic.ini, migrations/env.py, migrations/script.py.mako, migrations/versions/829a43db0969_create_hosts_table.py
Added Alembic default files generated by `manage.py db init`. Created [the first migration](
https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:db_schema?expand=1#diff-38a1839a77a8d0a25574d61d97372f3)f that creates the first attempt on a ["hosts" table](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:db_schema?expand=1#diff-38a1839a77a8d0a25574d61d97372f3fR21).
=> Initialize a database with the first migration

app/__init__.py
This picks up the database connection configuration from the following four environment variables:
- `INVENTORY_DB_USER` - the username to connect as - defaults to `insights`
- `INVENTORY_DB_PASS` - the password to use when connecting - defaults to `insights`
- `INVENTORY_DB_HOST` - the host address to connect to - defaults to `localhost`
- `INVENTORY_DB_NAME` - the database name to connect to - defaults to `test_db`
This allows e.g. docker systems, developer systems and other environments to set the database connection without disturbing the code.
=> Accept database URI details from environment for flexibility

api/host.py, app/models.py, run.py, swagger/api.spec.yaml, test_api.py
This corrects the definition of the Host's `id` field as an integer, when it is defined in the migration as a UUID.
=> Set Host id field to UUID, randomly generated by default

run.py
[Set](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:openshift#diff-6e38f16215ae91c11fc5c54b74c66d54R11) Flask’s _host_ variable to accept connections from everywhere. This is probably not the best thing to do. Using an IP provided by OpenShift would be better. Unfortunately I don’t know how to do that. 
This would at least allow for now to deploy to OpenShift from [_master_](https://github.com/RedHatInsights/insights-host-inventory/tree/master), even though there are many issues with the current configuration.
=> Allow access from any host

README.md, app/__init__.py, app/auth/__init__.py, test_api.py, test_unit.py
Created [an Authentication Manager](https://github.com/RedHatInsights/insights-host-inventory/pull/30/files#diff-3b16d374ef08532ca6b01246c5f0fa41R17) that hooks to every request. It parses and validates an identity HTTP header and makes the payload available to views. Currently the parsing and validation is only [a dummy stub](https://github.com/RedHatInsights/insights-host-inventory/pull/30/files#diff-3b16d374ef08532ca6b01246c5f0fa41R9): every request is valid if the header is present.
Replaces #7. Asking @dehort for a review.
I created [a new file](
https://github.com/RedHatInsights/insights-host-inventory/pull/30/files#diff-13729a38e16bcaf94b928e33e5dd468a) with unit tests, keeping [_test_api.py_](
https://github.com/RedHatInsights/insights-host-inventory/pull/30/files#diff-dc4308fba8c7 …
=> Hook a dummy auth validation to requests

README.md, app/__init__.py, app/auth/__init__.py, app/auth/identity.py, test_api.py, test_unit.py
This is a follow-up pull-request to #30. Replaces #9.
Created a dummy [Identity module](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:auth_with_dummy_identity?expand=1#diff-aaeb53fba2b4225a7fde4430b4b26033). This module does the same primitive validation as the original __validate_identity_ function. [Bound](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:auth_with_dummy_identity?expand=1#diff-3b16d374ef08532ca6b01246c5f0fa41R29) to the Authentication Manager so it can be replaced by a real working module.
After #30 gets merged, would appreciate a review from @dehort.
=> Bind validation to an identity module interface

app/auth/identity.py, test_unit.py
Created an authentication [module](
https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:auth_identity_module?expand=1#diff-aaeb53fba2b4225a7fde4430b4b26033) that [parses](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:auth_identity_module?expand=1#diff-aaeb53fba2b4225a7fde4430b4b26033R31) and [validates](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:auth_identity_module?expand=1#diff-aaeb53fba2b4225a7fde4430b4b26033R40) the identity header data injected by 3Scale. The [validation](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:auth_identity_module?expand=1#diff-aaeb53fba2b4225a7fde4430b4b26033R40) itself is pretty dummy as it only checks whether the …
=> Introduce an identity model module

app/models.py, app/utils.py, swagger/api.spec.yaml
This allows the output JSON structure to be read in Javascript and used as an object.  It also makes it compatible with Django-rest-framework's serializers.
=> Use underscores rather than dashes as property name separators

api/__init__.py, swagger/api.spec.yaml, test_api.py
Added a new view [_/health_](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:health_probe?expand=1#diff-b5704d15302288389d3aef6d5ab2a4f3R210) that simply responds with 200. This can serve as a responder for a health probe. It still requires the request to be authenticated though.
~~I didn’t write tests for this yet. Pushing here so it’s ready for you to use.~~
After #38 gets merged, the health probe can be modified so it won’t require authentication:
```python
from app.auth import bypass_auth
@bypass_auth
def health():
…
```
=> Create a primitive health probe

api/host.py, app/auth/__init__.py, test_unit.py
To have more control on which operations require the identity header, the authenticated view function must now be marked as such. All not marked views are considered unauthorized, they are available without the identity header and the identity object is not retrievable within
them.
Introduced a [_requires_identity_](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:requires_identity?expand=1#diff-3b16d374ef08532ca6b01246c5f0fa41R46) decorator that enables the identity header validation and access for a given view. This is a rather temporary measure: the following step is to mark the views automatically from the information in the OpenAPI specification.
There are no functional test, because the current implementation does not allow to add custom API to be …
=> Explicitly mark authenticated views

README.md
Add a new [Deployment section](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:health_docs?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8R70) to the [README file](
https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:health_docs?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8). Mentioned the existence of the health check endpoint there. Nothing special, just decreasing the number of undocumented features.
~~This is based on #41. Please do not merge before that pull request gets merged.~~
=> Mention the health check in the README

test_api.py
Altered the health check endpoint [test](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:health_test_without_auth?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R709): the identity header is [no longer passed](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:health_test_without_auth?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2L714). [The test](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:health_test_without_auth?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R709) now verifies that the operation works even when the identity header is not present. That is how it is going to be used.
This can effectively replaces #52 as I noted In my [comment]( …
=> Test health check does not require identity

run_gunicorn.py
Introduce a new [run script](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:prometheus_temp_dir?expand=1#diff-297b2ac7e7abfacd1d2c7aefe0c8b500) that creates [a temporary directory](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:prometheus_temp_dir?expand=1#diff-297b2ac7e7abfacd1d2c7aefe0c8b500R16) for
Prometheus and [runs](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:prometheus_temp_dir?expand=1#diff-297b2ac7e7abfacd1d2c7aefe0c8b500R31) Gunicorn in a subprocess with this directory path
set. This makes it easier to run the service locally for development without paying attention to Prometheus configuration and cleanup.
The server is …
=> Create a run script with temporary directory

swagger/api.spec.yaml
Filled in titles and descriptions for every operation and descriptions for every parameter in the [OpenAPI specification](
https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:descriptions?expand=1#diff-b5704d15302288389d3aef6d5ab2a4f3). Edited the existing titles and descriptions to be more unified.
These descriptions should make it more clear about the meaning and content of the entities. They can also appear in the Swagger UI console.
Asking @dehort for a review of the concept and of my crappy English.
=> Fill in descriptions wherever posible

README.md
Added a new [Documentation](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:documentation?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8R97) section to the [README](
https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:documentation?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8). It contains [a link](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:documentation?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8R100) to the API specification file, clickable on GitHub, and [a link](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:documentation?expand=1#diff-04c6e90faac2675aa89e2176d2eec7d8R102) to the Swagger UI Console, clickable on localhost with a running app …
=> Mention the API spec and UI in README

app/config.py, test_api.py
There were some typos in test names and log messages. Fixed those.
Fixes #97 and #90. Review? @dehort
=> Fix some typos

api/host.py, swagger/api.spec.yaml, test_api.py
Can now query with GET /hosts?fqdn="something.com" -- `get_host_by_canonical_facts` will be used. If the host exists, a list of 1 host is returned. Otherwise, empty list is returned.
=> Add ability to filter by fqdn

app/models.py
Simplified the function determining the default value for the _display_name_ field. It’s now more concise.
Arose from an earlier [discussion](https://github.com/RedHatInsights/insights-host-inventory/pull/121#discussion_r262115538). The `context.get_current_parameters()` call is now no longer repeated. Also used _or_ instead of _if/else_ statement to improve expressiveness.
=> Simplify display_name default

README.md, app/models.py, app/utils.py, swagger/api.spec.yaml, test_api.py
source_ref is a host’s reference in the external source e.g.
AWS EC2, Azure, OpenStack, etc.
For AWS EC2, source_ref maps to 'instance-id' attribute
(e.g. i-1234567890abcdef0), which can be discovered by insights
client by e.g. using:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
Topological Inventory '/vms' API endpoint has a source_ref
attribute that maps to this value.
=> Add external_id canonical fact

README.md, api/host.py, app/__init__.py, app/auth/__init__.py, logconfig.ini, swagger/api.spec.yaml, test_api.py, test_unit.py
Converted the swagger 2 interface doc to openapi 3.
Removed the more manual approach to x-rh-identity header authentication.
https://projects.engineering.redhat.com/browse/RHCLOUD-146
=> Openapi 3 conversion

app/auth/identity.py, test_unit.py
Added a test to make sure the issue doesn't come back.
=> Fixed an issue where extra data in the x-rh-identity header can cause an authentication failure.

api/host.py
It’s not necessary to extract the total number of records and the records itself in each find function. Modified those to return the result set itself. The code is now more concise and expressive.
=> DRY getting the query results

logconfig.ini
Added SQLAlchemy’s default logging [configuration](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:sqlalchemy_logging?expand=1#diff-b289960fa46262613513c74bcd6b9471R26) to the [_logconfig.ini_](
https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:sqlalchemy_logging?expand=1#diff-b289960fa46262613513c74bcd6b9471). With that it’s easy to change its loglevel to INFO to see the queries or to DEBUG to see even the results.
See [the docs](https://docs.sqlalchemy.org/en/latest/core/engines.html?highlight=log%20level#configuring-logging) for reference.
=> Add SQLAlchemy logging configuration

app/models.py, swagger/api.spec.yaml, test_api.py
Use marshmallow to validate the external_id.
=> Move the external_id length checks out of the openapi interface definition.

app/config.py
Update [_APP_NAME_](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:url_defaults?expand=1#diff-4b1fc3357c304348032d92a3c42978d0R28) and [_PATH_PREFIX_](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:url_defaults?expand=1#diff-4b1fc3357c304348032d92a3c42978d0R29) environment configuration defaults so they match the new deployments. The inventory API will be available at _/api/inventory/v1_.
=> Change URL defaults to match the deployments

test_api.py
Resolved the FIXMEs in the tests: added checks for the query results.
* When querying hosts themselves.
* When querying hosts system profiles.
The multiple hosts with system profiles test checks the pagination too.
=> Test query results

api/host.py, swagger/api.spec.yaml, test_api.py
Changed the pagination parameters from _[page](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:limit_offset?expand=1#diff-b5704d15302288389d3aef6d5ab2a4f3L254)/[per_page](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:limit_offset?expand=1#diff-b5704d15302288389d3aef6d5ab2a4f3L263)_ to standard _[limit](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:limit_offset?expand=1#diff-b5704d15302288389d3aef6d5ab2a4f3R254)/[offset](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:limit_offset?expand=1#diff-b5704d15302288389d3aef6d5ab2a4f3R264)_. The _offset_ starts with 0 and that’s also the default. The _limit_ is capped at 100 and its default is 50, just as …
=> Change pagination to LIMIT/OFFSET

api/host.py, swagger/api.spec.yaml, test_api.py
Made the query results more compliant with the Platform API documentation.
* Moved count and pagination metadata to its own dictionary key _"meta"_.
* Renamed the _"results"_ key to _"data"_.
The switch from the _page/per_page_ parameters to _limit/offset_ is in #172. The _"links"_ field will be added by another pull request.
1. Run a _/hosts_ or _/hosts/{}/system_profile_ query.
2. See that the count and paging metadata is under the _"meta"_ key.
3. See that the results are under the "data" key.
```
GET http://localhost:8080/api/inventory/v1/hosts/47363ef2-720c-4c88-89be-11983bda65e6,337a287f-e2d9-4692-856d-19efc548a04d,e6e717fb-eba2-47c7-ac00-a37532e33ce2/system_profile
HTTP/1.1 200 OK
Server: gunicorn/19.9.0
Date: Wed, 10 Apr 2019 14:15:15 GMT
Connection: close …
```
=> Change query request format

api/host.py, swagger/api.spec.yaml, test_api.py
When using _LIMIT/OFFSET_ pagination together with **consistent** first/next/previous/last links, it’s necessary to allow negative offsets. Otherwise, it wouldn’t be possible to keep the _LIMIT_ value across the pages.
Added support for negative _OFFSET_, converting the API _LIMIT/OFFSET_ values to the PostgreSQL ones, keeping the pagination cursor consistent. Any offset that would return no records yields _404 Not Found_. In case of having no records at all, 0 is the only allowed _OFFSET_.
Please see a [Gist](https://gist.github.com/Glutexo/54efb5601b837f533953a5b2c390bfd3#file-pagination-example-md) with examples that illustrate this graphically. I put quite some thought into this, consulted with co-workers and concluded that this is the only way how to do it without arbitrary decisions …
=> Allow negative offset

api/host.py, test_api.py
If a query is run with bad _LIMIT/OFFSET_ parameters, the 404 error message is not explanatory. It doesn’t say “Page Not Found” any more.
[Suggested](https://github.com/RedHatInsights/insights-host-inventory/pull/216#issuecomment-486225182) by @fijshion at #216.
=> Add verbose message to bad offset error

api/host.py, api/metrics.py, test_api.py
Adding a couple of metrics for the host delete operation
Commit the deleted hosts
Only emit events for hosts that were actually deleted
Verify the host is deleted in the test case
=> Adding a couple of metrics for the host delete operation

swagger/api.spec.yaml, test_api.py
commit c08633b7a93896f48b3a50e2269f0841f6c9f022
Author: dehort <dehort@redhat.com>
Date:   Wed May 8 12:55:27 2019 -0500
Add "branch_id" parameter to GET and PATCH (#262)
Add unused "branch_id" parameter to the GET /hosts/{host_id_list} and PATCH /hosts/{host_id_list} methods.  This is required for satellite integration.
=> Add "branch_id" parameter to GET and PATCH 

test_api.py
The tests addressing invalid pagination parameters were intended to catch invalid values, not invalid names. Fixed that to test the new _limit/offset_ parameter names. Also _0_ is a valid offset.
I forgot to amend the tests in #182.
=> Fix invalid pagination parameter tests

test_api.py
Replaced the current supplementary pagination [test](https://github.com/RedHatInsights/insights-host-inventory/compare/pagination...Glutexo:limit_offset_tests#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2L724) with a full [test suite](https://github.com/RedHatInsights/insights-host-inventory/compare/pagination...Glutexo:limit_offset_tests#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R1245). The original test was only added to some query tests to check that the pagination works for them. The new [tests](https://github.com/RedHatInsights/insights-host-inventory/compare/pagination...Glutexo:limit_offset_tests#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R1245) specifically test many possible _limit/offset_ combination for various result sets and with all three queries.
These new …
=> Explicitly test limit/offset pagination

app/__init__.py, tasks/__init__.py
This is an attempt to make the initialization of the event producer more explicit.  Instead of initializing the event producer when the tasks module is loaded, the event producer (and system profile consumer) is initialized/started when the init_tasks() method is called from app.create_app().
The config object is passed down into the tasks module and a reference is stored there as a global (see the cfg global).  The global is needed because the emit_event() method needs to get the topic from the configuration object.  I'm not too happy with the use of a global here, but I think this is a step in the right direction.
=> Modified the way the tasks module is initialized.

README.md
The [_Testing API Calls_](https://github.com/RedHatInsights/insights-host-inventory/blob/c08633b7a93896f48b3a50e2269f0841f6c9f022/README.md#testing-api-calls) section of the [_README_](https://github.com/RedHatInsights/insights-host-inventory/blob/c08633b7a93896f48b3a50e2269f0841f6c9f022/README.md) contains an example authentication HTTP header. These were printed as plain-text. Changed them to code so they are more distinguishable and readable. The JSON is even syntax-highlighted by GitHub.
Also changed the typography a bit.
=> Fix style of the authentication header in README

test_api.py
The __base_paging_test_ method has been [removed](https://github.com/RedHatInsights/insights-host-inventory/commit/939991b2439f13646a9f9de4f87648ee6c938490#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2L830) in favor of explicit pagination tests. One method call was however forgotten in the [_test_query_using_host_id_list_](https://github.com/RedHatInsights/insights-host-inventory/compare/pagination...Glutexo:fix_host_id_list_test?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R1289) test. Fixed by removing this [call](https://github.com/RedHatInsights/insights-host-inventory/compare/pagination...Glutexo:fix_host_id_list_test?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2L1301).
The tests are now 🍏 again.
=> Remove missed _base_paging_test

test_api.py
There were no tests verifying that _400 Bad Request_ is raised if the [_insights_id_](https://github.com/RedHatInsights/insights-host-inventory/blob/c08633b7a93896f48b3a50e2269f0841f6c9f022/swagger/api.spec.yaml#L36) in the [query](https://github.com/RedHatInsights/insights-host-inventory/blob/c08633b7a93896f48b3a50e2269f0841f6c9f022/swagger/api.spec.yaml#L7) is not a valid UUID. Added such [test](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:query_by_insights_id_tests?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R1513).
This is a part of fixes for #265. Related to #92.
=> Test query hosts by invalid insights ID

test_api.py
Added tests for the _PATCH /hosts/{host_id_list}_ [operation](https://github.com/RedHatInsights/insights-host-inventory/blob/c08633b7a93896f48b3a50e2269f0841f6c9f022/swagger/api.spec.yaml#L141), testing the cases when the IDs are not 100% ok:
* At least one of the IDs is not a UUID [→](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:patch_hosts_by_host_id_tests?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R1308) _400 Bad Request_
* Some IDs are non-existent, but not all [→](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:patch_hosts_by_host_id_tests?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R1280) _200 OK_
This is a part of fixes for #265. Related to #92.
=> Test patch hosts by troublesome IDs

test_api.py
Replaced all the bare usages of `str(uuid.uuid4())` with the already existing [_generate_uuid_](https://github.com/RedHatInsights/insights-host-inventory/blob/c08633b7a93896f48b3a50e2269f0841f6c9f022/test_api.py#L32) function. The code is now DRIER and more expressive.
=> Unify new UUID generation

test_api.py
[_DeleteHostsTestCase.test_create_then_delete_](https://github.com/RedHatInsights/insights-host-inventory/blob/af65dea5c62211083f301db800a1d126acba4372/test_api.py#L1318) fails, because unittest.mock is not imported. [Added](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:fix_tests_unittest_mock?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R4) missing import.
Still I don’t like the usage of _unittest.mock_ here. Please see #280 for more details.
=> Fix test failing by unittest.mock import

README.md
We're about to change some things that will make org_id a required field. Want to get ahead of it in these examples.
=> Change base64 sample

api/host.py, swagger/api.spec.yaml, test_api.py
Added [pagination links](https://github.com/RedHatInsights/insights-host-inventory/compare/pagination...Glutexo:pagination_links?expand=1#diff-b5704d15302288389d3aef6d5ab2a4f3R598) ([_first_](https://github.com/RedHatInsights/insights-host-inventory/compare/pagination...Glutexo:pagination_links?expand=1#diff-b5704d15302288389d3aef6d5ab2a4f3R607), [_next_](https://github.com/RedHatInsights/insights-host-inventory/compare/pagination...Glutexo:pagination_links?expand=1#diff-b5704d15302288389d3aef6d5ab2a4f3R611), [_previous_](https://github.com/RedHatInsights/insights-host-inventory/compare/pagination...Glutexo:pagination_links?expand=1#diff-b5704d15302288389d3aef6d5ab2a4f3R616), [_last_](https://github.com/RedHatInsights/insights-host-inventory/compare/pagination...Glutexo:pagination_links?ex …
=> Add pagination links to query outputs

test_api.py
The plain _/hosts/{host_id_list}_ [query](https://github.com/RedHatInsights/insights-host-inventory/blob/c08633b7a93896f48b3a50e2269f0841f6c9f022/swagger/api.spec.yaml#L104) has not had any tests yet. Added some testing:
* Regular [queries](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:query_by_host_id_tests?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R1474) for a single and multiple hosts
* [Queries](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:query_by_host_id_tests?expand=1#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R1485) with valid, but non-existent IDs
* Invalid [queries](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:query_by_host_id_tests?expand=1#diff-dc4308fba8c70f6d0b9ab17c …
=> Test query host by ID

migrations/versions/5dbbd56ce006_add_modified_on_id_index.py
[Added](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:default_ordering_index?expand=1#diff-4136aafb770721d5b4cc452e6b4f0518R22) a new index that gets used by the default hosts ordering: `"modified_on" DESC, "id" DESC`.
This is a complement to #325.
- _EXPLAIN SELECT_ without the index:
```
Limit  (cost=93366.28..93366.40 rows=50 width=685)
->  Sort  (cost=93366.28..95866.20 rows=999969 width=685)
Sort Key: modified_on DESC, id DESC
->  Seq Scan on hosts  (cost=0.00..60148.03 rows=999969 width=685)
Filter: ((account)::text = 'abc123'::text)
```
- _EXPLAIN SELECT_ with the index:
```
Limit  (cost=0.42..11.57 rows=50 width=685)
->  Index Scan using hosts_modified_on_id on hosts  (cost=0.42..222970.08 rows=999969 width=685)
Filter: ((account)::text = …
```
=> Add index on modified_on DESC, id DESC

README.md
The db "migrate" command should not be necessary.
The prometheus environment variable should not be necessary.
=> Improve/correct instructions in README

swagger/api.spec.yaml, test_api.py
Invalid UUIDs were causing facts operations (PUT, PATCH) to crash with 500 Internal Server Error. Fixed this so it now fails properly with 400 Bad Request.
The problem was in that the [_host_id_list_](https://github.com/RedHatInsights/insights-host-inventory/blob/1dab76aaaab5f77aeaf866efbd075b31022ad738/swagger/api.spec.yaml#L215) parameter didn’t have the _uuid_ format specified. Connexion thus didn’t validate it and any arbitrary string value was passed to a SQL query for a UUID field.
This’d be better fixed by unifying the _host_id_list_ parameter in the OpenAPI [spec](https://github.com/RedHatInsights/insights-host-inventory/blob/1dab76aaaab5f77aeaf866efbd075b31022ad738/swagger/api.spec.yaml) file. I’ll do this in a separate pull request.
=> Fix UUID validation on facts operations

test_api.py, test_unit.py, test_utils.py
test.support.EnvironmentVarGuard is an internal python api.  Its usage is causing issues for setting up automated tests.  Replaced the usage of test.support.EnvironmentVarGuard with a custom contextmanager.
The test_utils.py module needs to be moved to tests/utils.py later on.
=> Stop using test.support.EnvironmentVarGuard

swagger/api.spec.yaml
The OpenAPI [specification](https://github.com/RedHatInsights/insights-host-inventory/blob/1dab76aaaab5f77aeaf866efbd075b31022ad738/swagger/api.spec.yaml) describes the same parameter multiple times for different operations. Extracted those the parameters sections and replaced the in-place definition with a reference.
This also solves an UUID validation bug (#289) for facts operations, as there was missing the string format key.
=> Extract common query parameters

app/models.py, test_api.py
This reverts commit df7bc53ae861ab0cb0cd9a7d43ca41bc87df76f9.
=> Revert "Normalize the UUIDs that makeup canonical facts column"

api/host.py, swagger/api.spec.yaml, test_api.py, test_unit.py
Added ordering query parameters ([_order_by_](https://github.com/Glutexo/insights-host-inventory/blob/64d83729ff4ff1120e089fca4bbd975313e6a953/swagger/api.spec.yaml#L357) and [_order_how_](https://github.com/Glutexo/insights-host-inventory/blob/64d83729ff4ff1120e089fca4bbd975313e6a953/swagger/api.spec.yaml#L367)) to all three query operations ([_/hosts_](https://github.com/Glutexo/insights-host-inventory/blob/64d83729ff4ff1120e089fca4bbd975313e6a953/swagger/api.spec.yaml#L7), [_/hosts/{host_id_list}_](https://github.com/Glutexo/insights-host-inventory/blob/64d83729ff4ff1120e089fca4bbd975313e6a953/swagger/api.spec.yaml#L105), [_/hosts/{host_id_list}/system_profile_](https://github.com/Glutexo/insights-host-inventory/blob/64d83729ff4ff1120e089fca4bbd975313e6a953/swagger/api.spec.yaml#L209)). …
=> Add support for custom ordering ✨

test_api.py
There was forgotten debugging [block](https://github.com/RedHatInsights/insights-host-inventory/blob/47426c49d8e6595cc703d7271f84269fb3dc9c2a/test_api.py#L1684) in one of the tests helper [methods](https://github.com/Glutexo/insights-host-inventory/blob/b853f860d1205ff86c92e2d14d1cfb96ccb0ed21/test_api.py#L1673). [Removed](https://github.com/RedHatInsights/insights-host-inventory/pull/299/files#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2L1682) those lines as they should not be there.
=> Remove forgotten debug statements 🔥

app/__init__.py, inv_mq_service.py
Allow the "tasks" (threads, system profile kafka consumers, delete host event kafka producers to be disabled.  The tasks stuff should likely be injected in.
=> Allow the "tasks" to be disabled

app/__init__.py, run.py
The create_app() method is used in various areas of the code (tests, db migrations, host_dumper, etc) where tasks (threads, kafka producer, kafka consumer, etc) are not required.  For now, make it so that the tasks are only started when explicitly asked to.
=> Do not start the tasks subsystem unless explicitly asked to

api/metrics.py, lib/host.py, lib/metrics.py
This commit adds the prometheus metrics back to the add_host logic and moves the metrics out of the api module and into the (poorly named) lib module.
=> Move the metrics around.  Add the metrics back to the add_host logic.

api/host.py, app/models.py, app/serialization.py, host_dumper.py, lib/host.py
Created a new module [app.serialization](https://github.com/Glutexo/insights-host-inventory/blob/b8d9e8b8334fe33f054448499f3ede9245e3fbd3/app/serialization.py). Extracted all Host serialization and deserialization logic into that module. Used the existing paradigm from [_CanonicalFacts_](https://github.com/Glutexo/insights-host-inventory/blob/b8d9e8b8334fe33f054448499f3ede9245e3fbd3/app/serialization.py#L43) and [_Facts_](https://github.com/Glutexo/insights-host-inventory/blob/b8d9e8b8334fe33f054448499f3ede9245e3fbd3/app/serialization.py#L83) classes for the [_Host_](https://github.com/Glutexo/insights-host-inventory/blob/b8d9e8b8334fe33f054448499f3ede9245e3fbd3/app/serialization.py#L8) itself too. All the logic and behavior remained unchanged.
This is a part of the bigger picture of …
=>  Extract host (de)serialization

api/host.py, api/metrics.py, app/models.py, migrations/versions/76b7bc1d1d12_add_subscription_manager_id_index.py, test_host_dedup_logic.py
This change uses subscription_manager_id as well as insights_id as an "elevated" id for deduplication. 
RHCLOUD-149
=> Dedup hosts using subscription manager

host_dumper.py, test_api.py
Fixed the E231 Flake8 rule that targets whitespace around operators and control characters. In case of the [removed comma](https://github.com/RedHatInsights/insights-host-inventory/pull/334/files#diff-dc4308fba8c70f6d0b9ab17c57fb8ab2R873), the actual fix would be to add a space, but since this is not a multi-line expression, the trailing comma is redundant.
This is a part of the way to ultimately fixed formatting. #189 #335 Related to #331.
=> Formatting: fix Flake8 whitespace violations

gunicorn.conf.py, test_api.py, test_db_model.py
Fixed missing and redundant newlines triggering Flake8 _E3_ rules.
This is a part of the first step to fix all the formatting. See #335, #189 and #331.
=> Formatting: fix Flake8 newlines

api/__init__.py, api/mgmt.py, app/models.py, host_dumper.py, migrations/env.py, run.py, test_api.py, test_db_model.py, test_host_dedup_logic.py
Fixed the Flake8 rules related to imports:
- [_E402_](https://github.com/RedHatInsights/insights-host-inventory/commit/103d3245228f3b976fc1e788cd67804897ad36c7) for imports not being on top of the file
- [_F401_](https://github.com/RedHatInsights/insights-host-inventory/commit/068c2d7a024189e02ccb1a59e70f66b4a3214d0d) for unused imports
**Внимание, внимание!**
Removing unused imports is potentially risky, because it doesn’t touch only formatting. Imports _can_ have side effects and one such [case](https://github.com/RedHatInsights/insights-host-inventory/blob/c91e5e03d8405f1b73fac8fc81b4aadae45ad066/app/__init__.py#L12) is already documented in the code by a _#noqa_ comment. The API [tests](https://github.com/RedHatInsights/insights-host-inventory/blob/master/test_api.py) are still …
=> Formatting: fix Flake8 imports

migrations/versions/2d951983fa89_.py
Fixed the W291 Flake8 rule complaning about trailing whitespace.
This is a part of a big formatting fix. See #335, #189 and #331.
=> Formatting: fix trailing whitespace

api/host.py
Fixed the _W601_ Flake8 rule complaining about a deprecated method usage. This time resolved by adding a _#noqa_ comment. This is the only valid usage of the linter bypass in the whole repository. The object is not a Python collection, but a SQLAlchemy column. The object does not support using the _in_ keyword. Its _has_key_ method is a userspace method and is not deprecated. It builds a SQL filter on a _JSONB_ column.
This is a part of the first step towards a cleanly formatted codebase. See #189, #335 and #331.
=> Formatting: bypass linter on a non-deprecated method

README.md, dev.yml, migrations/versions/2d951983fa89_.py
Use the [_pre-commit-hooks_](https://github.com/pre-commit/pre-commit-hooks) [_trailing-whitespace-fixer_](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/trailing_whitespace_fixer.py) tool to remove all trailing whitespaces from the textual files in the repository. Another pull request #348 adds the tool as a development dependency.
```bash
for PATTERN in '*.py' '*.ini' 'README' '*.mako' '*.yaml' '.gitignore' '*.yml' '*.groovy' 'Pipfile' 'Pipfile.lock' '*.md'
do
find . -type f -name "$PATTERN" | xargs -L1 trailing-whitespace-fixer
done
``` 
This is a part of the way towards fixed formatting. See #189 and #331.
=> Formatting: trim trailing whitespace

conftest.py, test_db_model.py, test_host_dedup_logic.py, test_utils.py
Moved fixtures from the [_test_utils_](https://github.com/Glutexo/insights-host-inventory/blob/74a7bbbfdc049abcd978ae631d3e73749086a196/test_utils.py) module to a special [_conftest.py_](https://github.com/Glutexo/insights-host-inventory/blob/74a7bbbfdc049abcd978ae631d3e73749086a196/conftest.py) file that is grabbed automatically by pytest. This fixes the _F811_ Flake8 rule complaining about test function argument names clashing with the pytest fixture function name.
This is a part of the first step to fix all the formatting. See #189, #335 and #331.
=> Formatting: move fixtures to conftest.py

api/host.py, app/auth/__init__.py, test_api.py
Fixed the F841 Flake8 rule complaning about unused variables.
This is a part of the first step to fix all the formatting. See #189, #335 and #331.
=> Formatting: remove unused variables

.flake8, api/host.py
Fixed the _E501_ Flake8 rule targetting too long lines. In most places, the code has been only reformatted. Sometimes a variable name has been shortened or another code-aware change has been made. I am not sure whether these changes don’t trigger another Flake8 rule. That should not be a big of an issue, since such cases should be rare and can be easily fixed.
I used a line length of 88 character, which is what Black uses by default.
In the [_app.config_](https://github.com/Glutexo/insights-host-inventory/blob/31ac6a483f9ab2cc33b69ce1e7fa948899d096f9/app/config.py) module I changed the [_import_](https://github.com/Glutexo/insights-host-inventory/blob/31ac6a483f9ab2cc33b69ce1e7fa948899d096f9/app/config.py#L1) statement and replaced _os.environ.get_ with an equivalent _os.getenv_.
In the …
=> Formatting: fix long lines

Pipfile, Pipfile.lock
[Added](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:standalone_hooks?expand=1#diff-1e61a31bf9b94805f869dc4137ec1885R36) the [_pre-commit-hooks_](https://github.com/pre-commit/pre-commit-hooks/tree/master/pre_commit_hooks) package as a development dependency. This installs its bundled executables, making it possible to manually run the hooks like [_trailing-whitespace-fixer_](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/trailing_whitespace_fixer.py) (#347).
This is a part of a way to fix the formatting in the whole repository. See #189 and #331.
=> Formatting: add pre-commit-hooks to dependencies

test_unit.py
The (de)serialization classes and functions have been moved to the [_app.serialization_](https://github.com/Glutexo/insights-host-inventory/blob/7f2e863214ae2fc05860d61e7b2aa86051e2e82d/app/serialization.py) module. Renamed the related tests so they reflect this change.
This is a part of the serialization refactoring and is directly related to #351.
=>  Rename serialization tests

Pipfile, Pipfile.lock, test_api.py
Added [_Pyupgrade_](https://github.com/asottile/pyupgrade/) to development dependencies. This tool search Python scripts for pieces of deprecated code and replaces them with more modern variants. In our codebase, this targetted only the [API tests](https://github.com/Glutexo/insights-host-inventory/blob/pyupgrade/test_api.py), replacing the `%` string-formatting operator with the _str.format_ method. The tests are still passing 🍏 after the automatic fix.
This is a part of the way towards a better formatted code. #189 #331
=> Formatting: use Pyupgrade to remove deprecated code

.flake8, api/metrics.py, app/models.py, test_host_dedup_logic.py
[Removed](https://github.com/RedHatInsights/insights-host-inventory/commit/75ce37aa50cf2308669396f23f0d896cbfda08b2) all the ignored rules from the [_.flake8_](https://github.com/Glutexo/insights-host-inventory/blob/flake8_config/.flake8) configuration file. Almost all of there were successfully fixed by previous pull requests and are no longer needed. All rule violations (except those ignored by default) are going to be reported from now on.
Along with that [fixed](https://github.com/RedHatInsights/insights-host-inventory/commit/3fa57de066fe94fa87091dcb434a9f568a05eee9) all the remaining violations. These either slipped through the previous pull requests, or appeared newly as a result of merges. All of them are either newline or indentation related.
=> Formatting: final Flake8 fixes

api/__init__.py
Explicitly building out the flask.Response broke the status code logging.  This commit explicitly checks to see if the api method is returning a flask.Response and retrieves the status code from the flask.Response.
=> Fix the status code logging

Pipfile, Pipfile.lock, api/__init__.py, api/host.py, api/metrics.py, api/mgmt.py, app/__init__.py, app/auth/__init__.py, app/auth/identity.py, app/events.py, app/logging.py, app/models.py, app/validators.py, host_dumper.py, manage.py, migrations/env.py, migrations/versions/2d1cdfe3208d_add_system_profile_facts_column.py, migrations/versions/2d951983fa89_.py, migrations/versions/5dbbd56ce006_add_modified_on_id_index.py, migrations/versions/76b7bc1d1d12_add_subscription_manager_id_index.py, migrations/versions/a9f0e674cf52_add_ansible_host_column.py, run.py, run_gunicorn.py, tasks/__init__.py, test_api.py, test_host_dedup_logic.py, test_unit.py, test_utils.py, test_validators.py
Added the [_reorder-python-imports_](https://github.com/Glutexo/insights-host-inventory/blob/564c29512a1ac6fb924c049829d328ad85b62dc5/Pipfile#L31) package to the development dependencies. Used it to reorder imports in all Python files.
```bash
find . -type f -name '*.py' | xargs -L1 reorder-python-imports
```
The tool has split the imports into three groups, ordered them alphabetically and split multiple imports into separate lines. This will be later done automatically by a pre-commit hook. #331 
This is a part of the way to having the code cleanly formatted. #189
=> Formatting: reorder python imports

app/exceptions.py, app/logging.py, tasks/__init__.py, test_api.py, test_unit.py
Add newlines between class and function definitions and other pieces of code that need to be visually separated. Also remove excessive newlines. Used [Black](https://github.com/python/black) to fix these cases.
This is a part to fix formatting in the whole codebase to be able to run [Black](https://github.com/python/black), [Flake8](https://gitlab.com/pycqa/flake8) and other tools automatically. #335
=> Formatting: unify newlines by Black’s standards

api/host.py, app/__init__.py, app/auth/identity.py, app/config.py, app/logging.py, app/models.py, tasks/__init__.py, test_api.py
Unified all string interpolations.
- Log messages use the logging module’s native % interpolation, receiving the values as position arguments.
- String literals use f-strings instead of the % operator and the _str.format_ method.
This is a part of making the code clean and nicely formatted. #335
=> Formatting: string interpolation

.pre-commit-config.yaml, README.md
Added a pre-commit configuration file based on that in #331. I made some changes to that:
- Removed the _iqe_ exclusion as such folder is not a part of the repository.
- DRIED the language version.
- Bumped up versions to the most recent ones.
- Reodered the hooks – put [asottile’s](https://github.com/asottile)’s tools together and [_pre-commit-hooks_](https://github.com/pre-commit/pre-commit-hooks) to the end.
- Removed [Black](https://github.com/psf/black) [arguments](https://github.com/diegorafrh/insights-host-inventory/blob/3318b3be4765bceb6160bbe7a4113ed347dcf016/.pre-commit-config.yaml#L12): _safe_ is on by default, _quiet_ is not necessary
- Added a [_py3-plus_](https://github.com/Glutexo/insights-host-inventory/blob/31daba8b51dad20af99469cdde659204a9127f93/.pre-commit-config.yaml#L …
=> Formatting: Add pre-commit configuration

Pipfile, Pipfile.lock
The [_pre-commit-hooks_](https://github.com/Glutexo/insights-host-inventory/blob/032a06089c03ae67dbf2425e3f761e95e1393cb4/Pipfile#L31) is actually a developer tool that is not necessary to run the application. I’ve added (#348) it as a runtime dependency by accident. [Moved](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:pre_commit_hooks?expand=1#diff-1e61a31bf9b94805f869dc4137ec1885R37) to the [_dev-packages_](https://github.com/Glutexo/insights-host-inventory/blob/1fb5eddf7ab385ec29dd3d76cbab62e0001957d8/Pipfile#L32) section instead.
=> Move pre-commit-hooks to dev dependencies

api/host.py, api/metrics.py, app/__init__.py, app/auth/__init__.py, app/events.py, app/exceptions.py, app/logging.py, app/models.py, host_dumper.py, migrations/env.py, migrations/versions/2d951983fa89_.py, tasks/__init__.py, test_api.py, test_db_model.py, test_host_dedup_logic.py, test_validators.py
Used [Black](https://github.com/python/black) to contract expression spanning more than one line into a single line, if it fits into the 119 line-length limit. If the expression is a collection of comma-separated items, the trailing comma has been removed. No other changes to the code has been made.
Expressions, whose line count could be reduced, but would need changing the indentation style, have not been touched. That will be subject of another pull request.
This is a part of an ultimate formatting fix so [Black](https://github.com/python/black) can be run automatically for every commit and pull request. #335
=> Formatting: contract multi-line expressions

test_unit.py
Renamed the remaining tests that still had the models module name in its name. These tests describe functions in the serialization module and other tests follow this naming too. Unified.
A bit related to #374, but not much.
=> Rename serialization tests

test_api.py, test_unit.py
Change class names of unittest test cases so they now follow the same
pattern:
- All end with _TestCase_
- Abstract ones without their own tests end with _BaseTestCase_
I originally wanted to do this for the [_split_inventory_service_](https://github.com/Glutexo/insights-host-inventory/tree/split_inventory_service) branch, but it’s actually a generic problem. Because of that starting here and it can then extend to the changes in [that](https://github.com/Glutexo/insights-host-inventory/tree/split_inventory_service) branch.
=> Unify test case class names

test_api.py
In newer versions of Python, it’s possible to call just super() instead of super(ParentClass, self). Replaced these obsolete calls with their more concise variant. This is what `pyupgrade --py36-plus` would do.
See the [documentation](https://docs.python.org/3.6/library/functions.html?highlight=super#super) for more info.
This is a part of ultimately fixing the code so it can be checked and fixed automatically on commit.
=> Formatting: Simplify super calls

api/host.py, test_api.py, test_unit.py
Added trailing commas to the last item of multiline collections, if the ending parenthesis is not of the same line. Removed the comma if the parenthesis is there. This follows Black’s standard on where to put it. Neither moved the parentheses/brackets in any way, nor changed the line count of the expressions.
This is a part of the way towards a completely fixed formatting. Fixing the code according to [Black](https://github.com/python/black)’s standards will allow to use this tool automatically. #335
=> Formatting: fix trailing commas

Pipfile, Pipfile.lock, pyproject.toml
Added [Black](https://github.com/python/black) to the development packages list. It is [added](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:black?expand=1#diff-1e61a31bf9b94805f869dc4137ec1885R39) with the [specific version](https://github.com/Glutexo/insights-host-inventory/blob/577d10008951cabda7e8a026cb0b41f960e25f49/Pipfile#L39), so it is installed even though it is a pre-release. [Created](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:black?expand=1#diff-522adf759addbd3b193c74ca85243f7d) a [pyproject.toml](https://github.com/Glutexo/insights-host-inventory/blob/577d10008951cabda7e8a026cb0b41f960e25f49/pyproject.toml) configuration file for it. It is the only configuration format …
=> Formatting: Add Black as a development dependency

api/host.py, app/models.py, test_api.py, test_unit.py
Added/removed whitespace around brackets and operators to follow [Black](https://github.com/python/black)’s strict standards. Didn’t touch [trailing commas](#362).
This is a part of the way towards a completely [Black](https://github.com/python/black)-compliant formatting. It will allow to use the tool automatically for any new code. #335
=> Formatting: fix whitespace by Black’s standards

app/models.py
The default values for the [app.models.Host](https://github.com/RedHatInsights/insights-host-inventory/blob/009dbbba4f001ae1c7ea398b15aec110bc48ca49/app/models.py#L38) class arguments [_display_name_](https://github.com/RedHatInsights/insights-host-inventory/blob/009dbbba4f001ae1c7ea398b15aec110bc48ca49/app/models.py#L65)
and [_account_](https://github.com/RedHatInsights/insights-host-inventory/blob/009dbbba4f001ae1c7ea398b15aec110bc48ca49/app/models.py#L67) are bugs. The values are actually _sqlalchemy.sql.schema.Column_ instances. The only reasonable defaults here are _None_. Fixed.
I am going to get completely rid of the constructor nevertheless. Until that happens, I’d rather like to see it not buggy.
1. Create a …
=> Fix host constructor default values 🐛

api/host.py, app/serialization.py, host_dumper.py, lib/host_repository.py, test_db_model.py, test_unit.py
Moved all the [_Host_](https://github.com/Glutexo/insights-host-inventory/blob/c455dafbd4c0ad3a36218c011047b9319ccb1011/app/models.py#L33), [_CanonicalFacts_](https://github.com/Glutexo/insights-hostinventory/blob/c455dafbd4c0ad3a36218c011047b9319ccb1011/app/models.py#L76) and [_Facts_](https://github.com/Glutexo/insights-host-inventory/blob/c455dafbd4c0ad3a36218c011047b9319ccb1011/app/models.py#L93) (de)serialization methods from the classes to bare functions. The _CanonicalFacts_ and _Facts_ were mere containers for static methods. The [_Host_](https://github.com/Glutexo/insights-host-inventory/blob/c455dafbd4c0ad3a36218c011047b9319ccb1011/app/models.py#L119) is a database model, which should not be concerned about serialization.
The new bare methods can be easily extracted to a …
=> Extract (de)serialization methods

Pipfile, Pipfile.lock
Replace broad _*_ version requirements by specific ones. Packages using semantic versioning use _~=_ to enable bugfix upgrades, others are locked to the exact version as we can’t be sure what changes on an upgrade.
The non-semver packages are:
* [_jsonify_](https://github.com/Glutexo/insights-host-inventory/blob/b4f9fdeb5b865250048bfbac374c60bca36d4281/Pipfile#L8) 0.5 – no third place
* [_flask-api_](https://github.com/Glutexo/insights-host-inventory/blob/b4f9fdeb5b865250048bfbac374c60bca36d4281/Pipfile#L13) 1.1 – no third place
* [_request_](https://github.com/Glutexo/insights-host-inventory/blob/b4f9fdeb5b865250048bfbac374c60bca36d4281/Pipfile#L18) 2019.4.13 – uses dates
* [_ujson_](https://github.com/Glutexo/insights-host-inventory/blob/b4f9fdeb5b865250048bfbac374c60bca36d4281/Pipfile#L …
=> Specify versions in Pipfile

Pipfile, Pipfile.lock
Added [_pre-commit_](https://github.com/Glutexo/insights-host-inventory/blob/pre_commit/Pipfile#L41) to development dependencies. This allows to install
and run _pre-commit_ as [described](https://github.com/Glutexo/insights-host-inventory/blob/pre_commit/README.md#contributing) in [README](https://github.com/Glutexo/insights-host-inventory/blob/pre_commit/README.md).
1. Verify that _pre-commit_ is not hooked to the repository.
```
$ pre-commit uninstall
$ pipenv run pre-commit uninstall
```
2. Verify that you don’t have _pre-commit_ installed.
```
$ pre-commit
$ pipenv run pre-commit
```
3. Install _Pipenv_ development dependencies.
```
$ pipenv install --dev --ignore-pipfile
```
4. Hook _pre-commit_ to the repository.
```
$ pipenv run pre-commit install
```
=> Add pre-commit to dev dependencies

Pipfile
[Pytest](https://pypi.org/project/pytest/) is a development [dependency](https://github.com/Glutexo/insights-host-inventory/blob/remove_pytest/Pipfile#L6) and is not required in runtime. It was listed in the [Pipfile](https://github.com/Glutexo/insights-host-inventory/blob/remove_pytest/Pipfile) twice. [Removed](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:remove_pytest?expand=1#diff-1e61a31bf9b94805f869dc4137ec1885L24) the runtime [line](https://github.com/RedHatInsights/insights-host-inventory/blob/4b377d01559b22e374341c9cb15454a3dff61087/Pipfile#L24).
=> Remove pytest from runtime dependencies

Pipfile.lock
Removing pytest from the Pipfile broke the build in the buildfactory environment.  I uninstalled pytest using pipenv uninstall and added it back to just the dev section.  This appears to have resolved the issue in my testing.
=> Synchronized Pipfile.lock with the removal of pytest

Pipfile
Removed double quotes from the package names that contains digits. It is not necessary for them to be there. The TOML file is still valid and the formatting is more unified like that.
This is just a cosmetic change. It does not require recreating the [lock](https://github.com/Glutexo/insights-host-inventory/blob/unify_pipfile_formatting/Pipfile.lock) file.
=> Remove quotes from package names

utils/kafka_producer.py
The correct way to wait for all pending Kafka messages to be produced is to use the blocking method [_KafkaProducer.flush_](https://kafka-python.readthedocs.io/en/1.4.6/apidoc/KafkaProducer.html#kafka.KafkaProducer.flush). Used this method instead of current [_time.sleep_](https://github.com/RedHatInsights/insights-host-inventory/blob/ba8fe915d8c9131c687b0e9b35a3be24d1b2dcdf/utils/kafka_producer.py#L33), which is unreliable and may result in message loss.
Furthermore, the time measurement doesn’t produce a right value. Without the flush, it only measures how long does it take to add the messages to buffer.
=> Replace sleep with flush

Makefile, utils/kafka_consumer.py, utils/kafka_producer.py
Made environment variable names and default values in the producer tool with those in the [_Config_](https://github.com/Glutexo/insights-host-inventory/blob/717cd6e88a5549dc6dcd802c5a149030cb49202f/app/config.py#L7) class. This makes it possible to run the tool with the same environment configuration.
=> Unify producer tool env with config

utils/kafka_producer.py, utils/payloads.py
The [_build_chunk_](https://github.com/RedHatInsights/insights-host-inventory/blob/performance_input/utils/payloads.py#L169) function is not used anywhere and it doesn’t do anything useful. Removed entirely.
=> Remove unused build_chunk function

utils/kafka_consumer.py, utils/kafka_producer.py, utils/payloads.py
Modified the [consumer](https://github.com/Glutexo/insights-host-inventory/blob/ffa80636b8db5eb999e5473933de5e75d0987904/utils/kafka_consumer.py)/[producer](https://github.com/Glutexo/insights-host-inventory/blob/ffa80636b8db5eb999e5473933de5e75d0987904/utils/kafka_producer.py) scripts so they are more module-like. The executive (side-effect) code is encapsulated in a main function. The actual execution is under `__name__ == "__main__"` conditional.
=> Move executive code to main function

Pipfile, Pipfile.lock, utils/kafka_producer.py
[Use](https://github.com/Glutexo/insights-host-inventory/blob/609fb1b18a61fb7f269c824284b44a9aa80f59ff/Pipfile#L41) [TicToc](https://pypi.org/project/ttictoc/) library to measure and print out elapsed time. It makes the code more concise and readable.
1. Install all dependencies from [_Pipfile.lock_](https://github.com/Glutexo/insights-host-inventory/blob/609fb1b18a61fb7f269c824284b44a9aa80f59ff/Pipfile.lock). `pipenv sync`
2. Run [_utils/kafka_producer.py_](https://github.com/Glutexo/insights-host-inventory/blob/609fb1b18a61fb7f269c824284b44a9aa80f59ff/utils/kafka_producer.py).
3. See that TicToc is used to print out the elapsed time.
```
[Build payloads] Elapsed time: 0.000125885009765625 (s)
[Send all hosts to queue] Elapsed time: 0.17499899864196777 (s)
```
=> Add TicToc to measure time

utils/payloads.py
Dried repeating `str(uuid.uuid4())` code snippet to a single [_generate_uuid_](https://github.com/Glutexo/insights-host-inventory/blob/72aede4839294dc87106df5d87ab8fc7bc0bef30/utils/payloads.py#L150) function.
=> Extract random UUID function

utils/kafka_producer.py, utils/payloads.py
For-cycle is a notorious pattern and there is no need to abstract it to the payloads module. Moved to the [_kafka_producer_](https://github.com/Glutexo/insights-host-inventory/blob/83bad6a97493fb05a8f800c945a3dddb7eb8af0c/utils/kafka_producer.py) module, where it is symmetric with the further MQ send iteration. It makes the code cleaner.
=> Remove for abstraction from payloads

utils/payloads.py
Remove the [_build_data_](https://github.com/RedHatInsights/insights-host-inventory/blob/169ef29ee8bb2e86ccfeef020b0a5c4d01d381f4/utils/payloads.py#L169) function that decides what kind of payload is built. Made [_build_payloads_](https://github.com/Glutexo/insights-host-inventory/blob/8b2f7fac010235f35f4168afad18e415d75f8c40/utils/payloads.py#L171) function to directly accept the builder function as an argument. This allows to easier expansion, also prevents dict mutation.
=> Pass payload builder function

app/models.py
Black complains about [one file](https://github.com/Glutexo/insights-host-inventory/blob/d435af4c58fcb31d7de2eb3dc4c58e47c7436839/app/models.py) being invalid because of whitespace. Fixed.
Please don't commit anything without having _pre-commit_ hooks installed. Don’t accept any pull requests that don’t pass the _pre-commit_ checks. Thank you!
=> Fix a little whitespace violation

app/queue/ingress.py, app/queue/metrics.py
Divide this metric by the count to determine the average time spent handling a message from the ingress queue.
=> Adding requested metric to ingress.py

README.md
Fixed the [host deletion](https://github.com/Glutexo/insights-host-inventory/tree/host_deletetion_json_formatting#host-deletion) JSON example in the [_README_](https://github.com/Glutexo/insights-host-inventory/blob/host_deletetion_json_formatting/README.md), so it’s better rendered by GitHub. Quoting the missing values results in them not being painted red and it also adds the information that they are strings. Also changed whitespace not to use hanging indentation and to start right at the beginning of the line.
=> Fix host deletion JSON example formatting

api/host.py
The portion of PR 419 changing how hosts were loaded into the `hosts_to_delete` list has now been moved to this PR upon request.  I now present to you the smallest PR in existence.
=> changed how hosts are loaded into hosts_to_delete list

README.md, api/host.py, app/__init__.py, app/config.py, app/payload_tracker/__init__.py, app/payload_tracker/metrics.py, test_payload_tracker.py
The payload tracker can be disabled by setting the PAYLOAD_TRACKER_ENABLED environment variable to "false".   The payload tracker will also be disabled for add/delete operations that do not include a payload_id.  When the payload tracker is disabled, a NullObject implementation (NullPayloadTracker) of the PayloadTracker interface is used.  The NullPayloadTracker implements the PayloadTracker interface but the methods are "do nothing" methods.
The PayloadTracker purposefully eats all exceptions that it generates.  It does log the exceptions though.  I do not want a failure within the PayloadTracker to cause a request to fail.
The payload status is a bit "different" due to each "payload" potentially containing multiple hosts.  For example, the add_host operation will only log an error for …
=> Adding payload tracker integration to the inventory service

Jenkinsfile, app/models.py
The Jenkinsfile within this PR fires up this job https://jenkins-jenkins.5a9f.insights-dev.openshiftapps.com/job/insights-host-inventory/view/change-requests/ for us and updates back the PR with the status of each stage:
- Env configuration
- Lint (pre-commit checks)
- Unit tests
- Coverage
- Artifacts collecting
This is an effort to keep the code clear and service up and running smoothly and to avoid to send a eventually broken code to the master. If any step fails, the PR get blocked till the issue gets resolved.
It is worth mention that this also follows what other teams are doing, like the Advisor API team, Vmaas, among others.
=> Jenkinsfile - PR acceptance

app/__init__.py, run.py
Provide a way to allow for disabling/enabling the tasks and payload tracker.  This is needed for the automated tests and the db migration script (manage.py)
=> Provide a way to allow for disabling/enabling the tasks and payload tracker.

Jenkinsfile, README.md, api/host.py, app/__init__.py, app/config.py, app/events.py, app/payload_tracker/__init__.py, app/payload_tracker/metrics.py, run.py, test_payload_tracker.py
- add payload tracker to the inventory rest interface (RHCLOUD-1905)
- remove validation from delete event
- provide a way to disable the "tasks" subsystem (manage.py doesn't need to list on the message queue)
=> Stable payload tracker rhcloud 1905

api/host.py
There was a forgotten [_pass_](https://github.com/RedHatInsights/insights-host-inventory/blob/18e3af13fe3477784682887d586ffdd914654c31/api/host.py#L327) clause, not removed after refactoring. Removed to reduce clutter.
=> Remove unnecessary pass

api/host.py
If a race condition occurs during host delete, we [log](https://github.com/RedHatInsights/insights-host-inventory/blob/18e3af13fe3477784682887d586ffdd914654c31/api/host.py#L326) it, but we can’t log the ID of the host that was not deleted. [Added](https://github.com/RedHatInsights/insights-host-inventory/compare/master...Glutexo:host_delete_comment?expand=1#diff-a5c55b46cc9c536070cb56798c97adfaR326) a comment explaining why.
=> Add an explanatory comment for ObjectDeletedError

swagger/api.spec.yaml
Some of the value examples in the OpenAPI [specification](https://github.com/RedHatInsights/insights-host-inventory/blob/47469ae589c2ccfba2ceba58b9cc3575c6091c71/swagger/api.spec.yaml) file didn’t adhere to the [specification](https://swagger.io/specification/). A [Schema Object](https://swagger.io/specification/#schema-object) allows only one unnamed example without metadata, its value being a literal. Simplified examples that attempted to mimic the multi-example schema of [Request Body](https://swagger.io/specification/#request-body-object) or [Media Type](https://swagger.io/specification/#media-type-object).
This caused confusion on the API consumers side, namely @karelhala from the UI. This fix should make it more clear on what values are actually produced.
=> Make examples in API spec compliant

app/models.py, tasks/__init__.py
This fixes an issue where the db.session/transaction for the system profile consumer thread does not get cleaned up if the database goes down during processing.  When this happens, the sql operations for that thread always fail.
I'm not overly happy with where the context manager code lives currently.  Perhaps we need a app/db_utils.py for util methods like this.
=> Explicitly manage the db.session / transaction for the system profile consumer thread.

Jenkinsfile-smoke.groovy
Recently there was some change to Jenkins shared pipeline lib a.k.a insights-pipeline that is causing some errors on inventory-smoke job. 
Temporally pinning this to the previous version till they get it stable again.
more info: https://github.com/RedHatInsights/insights-pipeline-lib/pull/40
=> pin pipeline lib to previous stable version 1.3

test_api.py
Having [a class in a function](https://github.com/RedHatInsights/insights-host-inventory/blob/8d9206814a12418d14922c77e1c0baa6ef763046/test_api.py#L1303) is not necessary here. It just causes Python to redeclare it every time the function is run instead of on the class parse.
This pull request doesn’t change any behavior of the tests. The tests in the [_DeleteHostsTestCase_](https://github.com/Glutexo/insights-host-inventory/blob/e4859bc0aedc1d014510ea042cfea979e867926b/test_api.py#L1261) are still green. 🍏
=> Delete tests refactoring: Move MockEmitEvent to class level

test_api.py
DRY timestamp formatting. Pass it unformatted and call the _isoformat_ method right at the [place](https://github.com/Glutexo/insights-host-inventory/blob/3b6fe3151e89906fd722fa46bdd67bbf199fc2b6/test_api.py#L1319) where the other formatting happens.
This doesn’t change the tests behavior. [_DeleteHostsTestCase_](https://github.com/Glutexo/insights-host-inventory/blob/3b6fe3151e89906fd722fa46bdd67bbf199fc2b6/test_api.py#L1261) is still green. 🍏
=> Delete tests refactoring: Pass unformatted timestamp

test_api.py
A GET [request](https://github.com/RedHatInsights/insights-host-inventory/blob/8d9206814a12418d14922c77e1c0baa6ef763046/test_api.py#L1301) is currently done before [deleting](https://github.com/RedHatInsights/insights-host-inventory/blob/8d9206814a12418d14922c77e1c0baa6ef763046/test_api.py#L1312) records. This request is rather useless though, because _200 OK_ is [returned](https://github.com/RedHatInsights/insights-host-inventory/blob/8d9206814a12418d14922c77e1c0baa6ef763046/swagger/api.spec.yaml#L48) even if no hosts are found. Added an [assert](https://github.com/Glutexo/insights-host-inventory/blob/0d5f03da0bcdaa2ffea7d349d644be6aa8b34592/test_api.py#L1302) verifying that the host is actually found in the database.
=> Delete tests refactoring: Check the host presence on the first GET

Jenkinsfile
There is a few breaking changes in the latest version of the insights-pipeline-lib, so we have to pin it to the last stable version (1.3).
=> Setting insights-pipeline-lib version due breaking changes

test_api.py
_unittest.Mock_ can use a callable (including a class constructor) to create the mock. This is actually better than passing a manually created class instance as we are sure that the instance is not shared anywhere. Use as much from the _Mock_ capabilities as possible.
This doesn’t change any actual behavior of the tests. [_DeleteHostsTestCase_](https://github.com/Glutexo/insights-host-inventory/blob/b753df49432e7a7e44de59b9e1fe28f86d24764b/test_api.py#L1261) is still passing. 🍏
=> Delete tests refactoring: Replace Mock.new with new_callable

test_api.py
The shared [__create_then_delete_host_](https://github.com/Glutexo/insights-host-inventory/blob/39219fba282bd45258fb8d3af83b781e1ef22089/test_api.py#L1299) test method validates a host ID in an emitted event, but it gets the delete URL determining the hosts to delete from outside as an argument. Added a host argument to unify this.
This doesn’t change the tests behavior. [_DeleteHostsTestCase_](https://github.com/Glutexo/insights-host-inventory/blob/39219fba282bd45258fb8d3af83b781e1ef22089/test_api.py#L1261) still passes. 🍏
=> Delete tests refactoring: Pass host to the common test method

test_api.py
The [_DeleteHostsTestCase_](https://github.com/RedHatInsights/insights-host-inventory/blob/8d9206814a12418d14922c77e1c0baa6ef763046/test_api.py#L1261) class contains sets of rather unrelated tests.
- The race condition [tests](https://github.com/Glutexo/insights-host-inventory/blob/1dbcc9247f7026030d97778020b1bb7d4ed04571/test_api.py#L1321) with a special interceptor class.
- The event [tests](https://github.com/Glutexo/insights-host-inventory/blob/1dbcc9247f7026030d97778020b1bb7d4ed04571/test_api.py#L1274) with a special mock class.
- The invalid query [tests](https://github.com/Glutexo/insights-host-inventory/blob/1dbcc9247f7026030d97778020b1bb7d4ed04571/test_api.py#L1261) that don’t require pre-created hosts.
Split into three separate classes.
This doesn’t change the tests behavior. …
=> Delete tests refactoring: Split the delete tests class into three

app/models.py, test_db_model.py
Following the pattern for facts. On an existing host update each namespace without removing any namespaces not listed in the input host.
=> Adding functionality needed to update tags on a host

api/host.py, test_api.py, test_unit.py
To ensure unambiguous record ordering, order by _modified_on_ is not enough. Order by primary key must be there so the same order is really guaranteed. [Added](https://github.com/RedHatInsights/insights-host-inventory/pull/302/files#diff-a5c55b46cc9c536070cb56798c97adfaR232) this _ORDER BY_ clause to the host queries.
The [tests](https://github.com/Glutexo/insights-host-inventory/blob/f0cdd77923091168df59883fd2e0d0d609f4dd8a/test_api.py#L1714) are quite complicated. I could not find a way how to do it better. Tampering with a primary key and with the autofilled timestamps is not a very easy things to do. Hopefully the comments alleviate it a bit.
=> Add ORDER BY id DESC to queries

test_api.py
There were some _unittest_ modules and submodules [imports](https://github.com/RedHatInsights/insights-host-inventory/blob/b0308b020de7c3f5b046a5f971f7aac7280f98cb/test_api.py#L5) in [_test_api_](https://github.com/RedHatInsights/insights-host-inventory/blob/b0308b020de7c3f5b046a5f971f7aac7280f98cb/test_api.py), but they were used quite chaotically. Cleaned that up by always importing and using the specific methods.
Induced by #419.
=> Clean up the unittest imports

Jenkinsfile, Jenkinsfile-smoke.groovy, README.md, api/host.py, test_api.py, test_unit.py
This merges [current](https://github.com/RedHatInsights/insights-host-inventory/commit/bb076fe4108080aa1e444f7a36f23c875d1bfbfd) [_master_](https://github.com/RedHatInsights/insights-host-inventory/tree/master) to the [_split_inventory_service_](https://github.com/RedHatInsights/insights-host-inventory/tree/split_inventory_service) branch. The [merge](https://github.com/RedHatInsights/insights-host-inventory/commit/b7add607be2f1c6eeca380b12038c8645ffaada4) went through cleanly. The last [commit](https://github.com/RedHatInsights/insights-host-inventory/commit/7dce041722267ebfb9e67264823627716214e791) fixes a semantical merge conflict, fixing the only two failing tests.
This is the first step before auditing the feature branch behavior changes. No fixes are included here. For merging, …
=> Merge master into split_inventory_service

Makefile, README.md, api/host.py, api/metrics.py, app/__init__.py, app/config.py, app/events.py, app/exceptions.py, app/logging.py, app/models.py, app/queue/egress.py, app/queue/ingress.py, app/queue/metrics.py, app/serialization.py, host_dumper.py, inv_mq_service.py, lib/host_repository.py, lib/metrics.py, logconfig.ini, test_api.py, test_db_model.py, test_host_dedup_logic.py, test_unit.py, utils/kafka_consumer.py, utils/kafka_producer.py, utils/payloads.py, utils/rest_producer.py
* POC for splitting up the inventory service
Adding a kafka producer script for testing
Start kafka and db using:  docker-compose -f dev.yml up
Run the service using: make run_inv_mq_service
Run the kafka producer script using: make run_inv_mq_service_test
* Start the web service using make
* Adding a kafka based host producer for testing
* Getting app.logging wired into the new inv_mq_service (#311)
* Getting app.logging wired into the new inv_mq_service
* Moved logging messages to config. Refactored threadctx initialization into method.
* Tweaked the order of the db/kafka configuration log messages
* Renamed the host ingress kafka topic env vars to match the others
* Adding a new entry to logconfig.ini to enable logging for anything in the lib directory.
* Add a mq service_specific …
=> release the BIG MERGE to stable

swagger/api.spec.yaml
There is an unwanted backtick in the OpenAPI specification YAML. Removed, so it’s valid again. This was introduced in #484 and is a bug.
=> Remove unwanted char from API spec

api/host.py, test_api.py
Fixed formatting, syntax and import violations that caused pre-commit checks to fail. These also make the CI pipeline checks to fail. Pull requests that don’t pass those checks should never be merged. This was introduced by accident in #484.
=> Fix pre-commit checks violations

test_api.py
The _get_host_list_ operation’s _tag_ [parameter](https://github.com/RedHatInsights/insights-host-inventory/blob/96b016a01de51efe8fa7d653a9040a936025c4e7/swagger/api.spec.yaml#L42) has been renamed to _tags_. It remained in the [tests](https://github.com/RedHatInsights/insights-host-inventory/blob/96b016a01de51efe8fa7d653a9040a936025c4e7/test_api.py#L1607) though making them fail. Fixed. This is a bug introduced by #484.
=> Fix tags param in tests

test_api.py
Added a [test](https://github.com/Glutexo/insights-host-inventory/blob/be9ebf4a2c3f81d85e4fa97d874548dc50955d6f/test_api.py#L1689) for a case when hosts are queried by more tags in a single namespace. Like that hosts with only the last tag in the query would be matched even though they wouldn’t possess the other tags in the namespace. This tests verifies that the bug is no longer present.
Example:
A host has tags _NS1/key1=val1_ and _NS1/key2=val1_. We query hosts with tags _NS1/key1=val2_ and _NS1/key2=val1_. Only the last tag in the _NS1_ namespace was actually used and as a result, the hosts was matched by only _NS1/key2=val1_ even though it doesn’t have the _NS1/key1=val2_ tag.
1. In [_api/host.py:_tags_host_query_](https://github.com/Glutexo/insights-host-inventory …
=> Add tags regression test

app/queue/ingress.py, app/queue/metrics.py
uses labels to distinguish between
* message_handler failures caused by payload failing schema validation vs other errors
* "host added" vs "host updated" events
https://projects.engineering.redhat.com/browse/RHCLOUD-2880
=> improve MQ service metrics

api/host.py, app/queue/ingress.py, app/serialization.py, lib/host_repository.py, test_api.py, test_db_model.py, test_unit.py
Move the schema from the repository host add logic layer to the deserialization one. As a result, every work with an input host dictionary is done after it’s been validated. That includes an account number comparison. Ergo, if the account number is invalid, it’s not being even compared to the one in the identity header.
Fixes [RHCLOUD-3018](https://projects.engineering.redhat.com/browse/RHCLOUD-3018).
Added some tests verifying that the validation actually happens and that it happens in the right place. That required amending all the currently invalid host inputs in tests.
1. Try to add a host with an invalid account number.
```json
[
{
"account": "",
"fqdn": "test"
}
]
```
2. See that a Marshmallow validation exception (_Bad Request) is presented instead of our logic …
=> Validate hosts when deserializing

app/models.py, migrations/versions/c6bfa7ebeaee_add_stale_timestamp_and_reporter_columns.py
Added _stale_timestamp_ (timestamp with time zone) and _reporter_ (varchar 255) to the [database](https://github.com/Glutexo/insights-host-inventory/blob/08abebd01fe8a2b15c6081020322644442545637/migrations/versions/c6bfa7ebeaee_add_stale_timestamp_and_reporter_columns.py) and to the SQLAlchemy [model](https://github.com/Glutexo/insights-host-inventory/blob/08abebd01fe8a2b15c6081020322644442545637/app/models.py#L56). Both are nullable, because they are not filled for the existing records.
The _stale_timestamp_ includes time zone information for it to be aligned with other timestamp columns. Although this is not necessary, it makes it somehow easier to pump the data to the cross join database.
The new fields are not in the [HostWrapper](https://github.com/Glutexo/insights-host-inventory/blob …
=> Add culling columns

test_db_model.py
Added a few database model tests that verify column presence, type and default values.
Triggered by #510 a #489. There are no tests checking that there are correct columns in the database and the model is correctly set.
=> Test basic model properties

utils/payloads.py
Made the [_utils.payloads.build_payloads_](https://github.com/Glutexo/insights-host-inventory/blob/627c2fc5af65b4e3245fec3c01627866bd94df3c/utils/payloads.py#L187) method more readable.
* Used the instance variant of str.encode method
* Explicitly stated the UTF-8 encoding
* Extracted a variable to distinguish a message from a payload
=> Performance input: Refactor build_payloads method

test_api.py
The created/modified timestamps were [converted](https://github.com/RedHatInsights/insights-host-inventory/commit/b2d37d641a43f180c7b8fd0cb55c833020df6cc3) to be time zone aware. This has broken [tests](https://github.com/RedHatInsights/insights-host-inventory/blob/2b4c4c91ba5bff1e7f6652e4025c4539de8393b0/test_api.py#L1835) tampering with those timestamps in a non-aware way. In negative offset time zones, the _modified_on_ timestamp was set incorrectly resulting in a different order than expected. Fixed by using time zone aware _datetime_ objects.
1. Use a time zone with a negative offset, e.g. EST.
2. Verify that without this patch, the [_test_hosts_ordered_by_updated_are_also_ordered_by_id_desc_](https://github.com/RedHatInsights/insights-host-inventory/blob/2b4c4c91b …
=> Fix ORDER BY id tests in <UTC timezones

logconfig.ini, utils/validate_hosts_for_delete.py
Created Validation script to test all hosts in the db and see if the current validations would suffice for ALL hosts currently stored there.  In reference to the `threadctx.request_id = "-1"` I decided to use a global in order to temporarily assign a value since no actual HTTP requests are being called in this script.
=> added validation script to test db in cluster.

README.md
I forgot to update the README to include that the subscription_manager_id is also used in the dedup logic.  Sorry folks...
=> Adding info on using the subscription_manager_id for dedup-ing to the README

app/serialization.py, test_unit.py
Reviewed the style of the (de)serialization methods. Removed redundant or rather cryptic instructions. Leveraged comprehensions, dried a few bits of code. Made the code more concise and expressive. Unified names a bit.
This is a #390 variant rebased to [current](https://github.com/RedHatInsights/insights-host-inventory/tree/fe49fda9e279f4ef971498fdb486812259d2902b) [_master_](https://github.com/RedHatInsights/insights-host-inventory/tree/master).
Added a [TODO](https://github.com/Glutexo/insights-host-inventory/blob/eea172782596b55427330221e2b088323802ff0b/app/serialization.py#L104) for the new [tag transformation](https://github.com/Glutexo/insights-host-inventory/blob/eea172782596b55427330221e2b088323802ff0b/app/utils.py#L156).
=> Serialization: Make serialization methods more concise

api/host.py, app/__init__.py, app/config.py, app/culling.py, app/models.py, app/queue/egress.py, app/queue/ingress.py, app/queue/metrics.py, app/serialization.py, app/utils.py, host_dumper.py, lib/host_repository.py, swagger/api.spec.yaml, test_api.py, test_mq_service.py, test_unit.py, utils/payloads.py
https://projects.engineering.redhat.com/browse/RHCLOUD-2575
* Save stale_timestamp and reporter
Added stale_timestamp and reporter fields to the add_hosts operation.
If one of the fields is present, the other one must be filled in too.
The stale_timestamp gets updated if
* it’s either not set at all
* or if the reporter is the same and the new timestamp is longer
* or if the reporter is different and the new timestamp is shorter
* Save stale_timestamp and reporter
Added stale_timestamp and reporter fields to the add_hosts operation.
If one of the fields is present, the other one must be filled in too.
The stale_timestamp gets updated if
* it’s either not set at all
* or if the reporter is the same and the new timestamp is longer
* or if the reporter is different and the new timestamp is …
=> release culling

api/host.py, swagger/api.spec.yaml, test_api.py
"To help with rollout of system culling we should relax the enforcement on GETs for a single system so they return the system even if it's culled."
=> Dissable staleness check when hosts are requested by id

app/queue/ingress.py, app/queue/metrics.py, inv_mq_service.py, test_mq_service.py
Due to RHCLOUD-3610 we're receiving messages with invalid unicode code points (invalid surrogate pairs).
Python pretty much ignores that but it is not possible to store such strings in the database (db INSERTS blow up)
I added validation logic that looks for such invalid sequences with the intention of marking such messages as invalid (i.e. detect validation error rather than failing later in the db layer)
=> check incoming messages for invalid unicode sequences

app/models.py, swagger/api.spec.yaml, test_api.py
Fixes 500 error when sending string formatted tag instead of structured tag while creating host. Now returns 400
=> Fix 500 error when adding host with tags in string format (RHCLOUD-3342)

app/models.py, swagger/api.spec.yaml, test_api.py, test_mq_service.py, test_utils.py
Implement schema changes, which correspond to `system_profile` changes from https://github.com/RedHatInsights/insights-puptoo/pull/36
- Added local repo-id into `yum_repos` objects
- Added the `dnf_modules` key containing information about modules.
- Fixed swagger doc, schemas and test to reflect these changes.
=> Implement repository changes to system_profile

swagger/api.spec.yaml
Added int64 format specifier for system_memory_bytes. By default, openapi assumes int32, which means, that system profiles with more than 3gb memory weren't parsed by this client: https://github.com/RedHatInsights/patchman-clients, and could not be processed by SPM application
=> Use int64 format for system_memory_bytes

api/host.py, api/host_query.py, api/host_query_db.py, api/host_query_xjoin.py, api/tag.py, app/__init__.py, app/auth/__init__.py, app/culling.py, app/queue/ingress.py, app/serialization.py, app/xjoin.py, host_dumper.py, lib/host_repository.py, test_api.py, test_unit.py
Add [_xjoin-search_](https://github.com/RedHatInsights/xjoin-search) as an alternative data source for the host search query. This is configured by [an environment variable](https://github.com/Glutexo/insights-host-inventory/blob/bd014f0faed3bf7c0d4eef15534ef303c754b984/app/config.py#L67). Extract the _xjoin-search_ GraphQL code from the tags queries. Extract common parts from the database queries.
=> Host query GraphQL integration

api/host.py, api/host_query_db.py, app/config.py, app/culling.py, app/payload_tracker/__init__.py, host_reaper.py, lib/host_delete.py, lib/host_repository.py, tasks/__init__.py, test_api.py
Created a [“reaper”](https://github.com/Glutexo/insights-host-inventory/blob/2b49d29032359cbacf179194379c4ed624f3ef24/host_reaper.py) script that removes all culled hosts. It is intended to be run periodically to clean up the database. For every deleted host a delete event is emitted.
Extracted the common host delete [part](https://github.com/Glutexo/insights-host-inventory/blob/2b49d29032359cbacf179194379c4ed624f3ef24/lib/host_delete.py) that handles the event [emission](https://github.com/Glutexo/insights-host-inventory/blob/2b49d29032359cbacf179194379c4ed624f3ef24/lib/host_delete.py#L32) and race condition [handling](https://github.com/Glutexo/insights-host-inventory/blob/2b49d29032359cbacf179194379c4ed624f3ef24/lib/host_delete.py#L34).
The script uses SQLAlchemy and its models, but …
=> Add host reaper script

test_api.py
[Reuse](https://github.com/Glutexo/insights-host-inventory/blob/8064b16a20953c1bf32e583bcd136367dd85b5c5/test_api.py#L1067) the existing delete tests for the new [Host Reaper](https://github.com/Glutexo/insights-host-inventory/tree/8064b16a20953c1bf32e583bcd136367dd85b5c5). [Test](https://github.com/Glutexo/insights-host-inventory/blob/8064b16a20953c1bf32e583bcd136367dd85b5c5/test_api.py#L1072) the delete [event](https://github.com/Glutexo/insights-host-inventory/blob/8064b16a20953c1bf32e583bcd136367dd85b5c5/app/events.py) [emission](https://github.com/Glutexo/insights-host-inventory/blob/8064b16a20953c1bf32e583bcd136367dd85b5c5/tasks/__init__.py#L49) along with that.
Based on #560. ~~Will un-draft once merged.~~
=> Test Reaper delete event

api/host.py, api/tag.py, app/config.py, test_api.py
We need a way to enable xjoin for only specific users, or in a specific environment. To facilitate this I'm adding a new header:x-rh-cloud-bulk-query-source. I am also adding a behaviour that checks the forwarded referer header and switches the bulk-query-source to xjoin when the URL contains /beta.
When set the header will take priority will override both the BulkQuerySource set by the OpenShift environment variable, and the URL based behaviour.
=> Allow user to enable xjoin with request header (RHCLOUD-3758)

test_api.py
There were a few forgotten logging statements in the [API tests](https://github.com/Glutexo/insights-host-inventory/blob/b27df95ec170282d07a88c4d33bd0dbad5f56e96/test_api.py). Removed.
=> Remove forgotten logging

README.md, api/metrics.py, app/__init__.py, app/config.py, host_reaper.py, inv_mq_service.py, lib/host_delete.py, lib/metrics.py, test_api.py, test_payload_tracker.py, test_unit.py
Use a Prometheus Pushgateway to report metrics from the [Host Reaper](https://github.com/Glutexo/insights-host-inventory/blob/2fc6fd481bd3841d6fa40149f231146a0ae76192/host_reaper.py). A new [configuration value / environment variable](https://github.com/Glutexo/insights-host-inventory/blob/2fc6fd481bd3841d6fa40149f231146a0ae76192/app/config.py#L46) is used for the target.
=> Push Host Reaper metrics

app/xjoin.py, test_api.py
When xjoin-search returns a non 200 status code insights-host-inventory still tries to process it as if the request was successful. This behaviour is part of what cause the bug mentioned in the title of the PR.
This PR adds a check to make sure that the request to xjoin was successful, and if not forwards the status code from xjoin.
=> Check xjoin-search response (RHCLOUD-4272)

README.md, app/queue/egress.py, app/queue/ingress.py, app/serialization.py, lib/host_repository.py, test_mq_service.py
This PR adds tags and system_profile to egress messages. This covers changes to the information we put on egress requested by the Advisor team. I've merged both changes into the one PR since they are very similar changes. The relevant tickets are below:
https://projects.engineering.redhat.com/browse/RHCLOUD-4202
https://projects.engineering.redhat.com/browse/RHCLOUD-3835
=> Add tag data to host output on egress kafka topic (RHCLOUD-4202, RHCLOUD-3835)

Pipfile, Pipfile.lock, api/host.py, test_api.py
[_python-dateutil_](https://pypi.org/project/python-dateutil/) is used to parse the ISO 8601 timestamps. This library is already present as a deep dependency. There are some explicit [uses](https://github.com/Glutexo/insights-host-inventory/blob/db6fa3bc90cadcc403382e4c9f38be1d60cb41aa/test_api.py#L25) of _dateutil_ in the [tests](https://github.com/Glutexo/insights-host-inventory/blob/db6fa3bc90cadcc403382e4c9f38be1d60cb41aa/test_api.py). That could be potentially a problem as n-th level dependency can disappear at any time without notice. Fixed.
There is a bug making _Connexion_ and _Werkzeug_ fail together. [Upgrading](https://github.com/Glutexo/insights-host-inventory/blob/db6fa3bc90cadcc403382e4c9f38be1d60cb41aa/Pipfile#L20) _Connexion_ to 2.6.0 fixes the issue, but brings some …
=> Add dateutil to Pipfile

app/models.py, app/serialization.py, swagger/api.spec.yaml, test_api.py, test_db_model.py, test_mq_service.py, test_unit.py
Make _stale_timestamp_ and _reporter_ required fields for new hosts. That makes all hosts without either of the field rejected. Both null values and empty strings are rejected. This applies both to the HTTP REST and to the Message Queue API.
- For the HTTP API, the fields are [required](https://github.com/Glutexo/insights-host-inventory/blob/8aca13f864858a73b08b256258a219fdd1f7b486/swagger/api.spec.yaml#L589) on the [OpenAPI Specification](https://github.com/Glutexo/insights-host-inventory/blob/8aca13f864858a73b08b256258a219fdd1f7b486/swagger/api.spec.yaml) level. If the field is not present, the whole add host request fails with _400 Bad Request_. If it’s there, but is invalid, the request itself succeeds wth _207 Multi-Status_, but the host is not saved _400 Bad Request_.
- For the MQ …
=> Require culling fields in API specification

Jenkinsfile-smoke.groovy
This change is necessary because the platform set was split into multiple sets:
- ingress -- contains upload service, pup, storage broker, etc.
- inventory -- any app related to inventory (including reaper and host-delete)
- engine -- the shared engine app
- buck-it -- buck-it
- payload-tracker -- payload-tracker front-end/back-end/db
=> Updated the smoke tests jenkins file

migrations/helpers.py, migrations/versions/f48f739902ed_alter_stale_timestamp_and_reporter_to_.py, migrations/versions/ff39a83abac3_fill_in_stale_timestamp_and_reporter.py
Added migrations that
* [fill](https://github.com/Glutexo/insights-host-inventory/blob/08689b9e27528b239293f79659b876fb0fa7ad3c/migrations/versions/ff39a83abac3_fill_in_stale_timestamp_and_reporter.py) the missing stale timestamp a reporter.
* [alter](https://github.com/Glutexo/insights-host-inventory/blob/08689b9e27528b239293f79659b876fb0fa7ad3c/migrations/versions/f48f739902ed_alter_stale_timestamp_and_reporter_to_.py) the columns to not accept a NULL value.
The [downgrade](https://github.com/Glutexo/insights-host-inventory/blob/08689b9e27528b239293f79659b876fb0fa7ad3c/migrations/versions/ff39a83abac3_fill_in_stale_timestamp_and_reporter.py#L53) is not 100% symmetric: the values are cleared for all records marked as migrated. It shouldn’t have been ever possible though to add hosts with …
=> Fill in stale_timestamp and reporter

app/models.py, swagger/api.spec.yaml, test_utils.py, utils/payloads.py
This commit adds a "captured_date" field to the system profile. This
date records when the system profile was captured on the client
system.
For example, if a system upload was created on a Monday but uploaded
on Tuesday, this date would be Monday. PUP will populate this from the
system time in the uploaded tarball.
=> add "captured_date" to system profile

README.md, migrations/versions/5544cd265053_set_replica_identity_to_full_on_hosts_.py
This is required to prevent truncated messages from being sent through the xjoin pipeline. See https://debezium.io/blog/2019/10/08/handling-unchanged-postgres-toast-values/
=> Replica identity full

api/host_query_db.py, lib/host_repository.py, test_api.py
A direct equal comparison (=) used instead of subset matching (@>, <@) when querying host by a single (elevated) canonical fact. Used when
- matching a host by Insights ID or Subscription Manager ID on add
- and matching a host by FQDN or Insights ID on list get.
The tests are only checking that the right query method is called. The only other option would be to examine the composed SQLAlchemy Host query, which I think is not a good way.
=> Use direct comparison for host matching

app/queue/ingress.py, lib/host_repository.py, test_mq_service.py
To help with debugging, log more data about the host during ingress.
=> RHCLOUD-4217: Add reporter to find existing host log statements

app/models.py, test_api.py
If a host is stale, use the next reporter's stale_timestamp no matter what.
=> RHCLOUD-5016 - IPP hotfix

app/queue/ingress.py
To help with Kibana storage limitations, change this one log statement to DEBUG so it doesn't end up in Kibana.
=> Change chatty log stmt from INFO to DEBUG to ease prod log surfing

app/queue/egress.py, app/queue/ingress.py, inv_mq_service.py, test_mq_service.py
Jira: [Here](https://projects.engineering.redhat.com/browse/RHCLOUD-2766)
Current approach: _I am extending the Kafka Consumer class to add a graceful shutdown method and some flags to check and halt shutdown when an in-flight operation is in progress_
There is a failing test that still needs to be addressed. But, please let me know if this approach can be improved or needs to be changed entirely. :slightly_smiling_face:
=> RHCLOUD-2766 - Graceful shutdown

host_reaper.py
On failure, the Host Reaper now [exits](https://github.com/Glutexo/insights-host-inventory/blob/8652f0f568fa9ece9e179e557938355891c8f801/host_reaper.py#L81) with a status code 1. Just as if the exception wasn’t caught at all.
No tests at the Reaper script scaffold is not tested.
=> Add exit code for Host Reaper exception

host_reaper.py, test_api.py
A little follow-up to #617. This slipped through my finger.
The logger is now [created right after](https://github.com/Glutexo/insights-host-inventory/blob/f6c5bd1853415f204aabf11c34bc220526b227f0/host_reaper.py#L93) logging configuration. Use this logger instance and pass it down to the functions instead of creating a new one.
=> Create logger only once

api/tag.py, test_api.py
With RHCLOUD-5665 we're removing the need to urlencode the search string when making the request.
This is related to:
https://projects.engineering.redhat.com/browse/RHCLOUD-5656
https://projects.engineering.redhat.com/browse/RHCLOUD-5668
=> Remove percent encoding of the search string in /tags

api/host.py, app/models.py, lib/host_repository.py, test_db_model.py, test_mq_service.py
Summary of changes:
- change guard to not update display name for specific reporter == "yupana" (instead of only allowing display name updates for puptoo, which might have been too restrictive)
- remove the `from_REST_API` bool in favor of the change above
- add test an MQ test
=> cleanup Sat 6.7 hotfix

api/host.py, app/payload_tracker/__init__.py, app/queue/ingress.py, test_payload_tracker.py
The Payload Tracker is transitioning to using the new "request_id" terminology instead of the legacy "payload_id." This renames that field.
=> Use request_id instead of payload_id

test_api.py
Custom emit event mock class has been [removed](https://github.com/RedHatInsights/insights-host-inventory/pull/633). As a result, _emit_event_ is a plain _MagicMock_ and so is _emit_event.events_. Nothing is stored there in the events attribute, but _len_ returns 0. That makes the [test](https://github.com/Glutexo/insights-host-inventory/blob/f97ea599d6e5e4e4aa61264f551e5c83334360f1/test_api.py#L1332) pass, but the actual not emitting remains untested. Fixed by replacing with assert_not_called.
This is a follow-up to #633.
=> Fix mock test assertion

app/queue/egress.py, test_api.py, test_mq_service.py
There is concern that adding the new metadata field at the same time as the patch event will be too much for consumers. This PR simply removes the metadata fields from the messages and updates some tests to expect that. I did not however go through and remove all of the supporting logic so that when we eventually add the field back it should be simple.
=> remove metadata field from events

app/logging.py
In AppSRE configurations, apps do not have permissions to create the log group in cloudwatch. It is already created for them. This PR adds an env var (default: False) that allows the `create_log_group` option to be set to True or False on the `CloudWatchLogHandler`
=> Add env var for creating log group, default to False

app/queue/egress.py, test_api.py, test_mq_service.py
Reverts RedHatInsights/insights-host-inventory#643
Now that https://github.com/RedHatInsights/insights-host-inventory/commit/57a17c9fd26d350b43eba7acb0491e2f9716f642 has been released this is a second phase of RHCLOUD-1102 rollout where the new "metadata" top-level field is added to host events.
=> Add "metadata" back to host events

app/__init__.py, app/auth/identity.py, app/config.py, app/environment.py, app/logging.py, conftest.py, host_dumper.py, host_reaper.py, inv_mq_service.py, manage.py, run.py, test_api.py, test_mq_service.py, test_payload_tracker.py, test_unit.py, utils/validate_hosts_for_delete.py
There were two ways of configuring the application runtime.
- _APP_SETTINGS_ environment variable, which is not used anywhere. Even in production, its value is `"development"`. It is assigned various values across the codebase, but only "testing" value actually does something.
- _RuntimeEnvironment_ enumerable that was intended to control what subsystems are used, but was only used for configuration logging.
Replaced the _APP_SETTINGS_ value and the boolean application parameters with an extended version of _RuntimeEnviroment_ enumerable. Its value determines what subsystems are launched.
- _SERVER_: Connexion/Flask HTTP server, uses Event Producer and Payload Tracker and exposes Prometheus metrics. Handles everything inside the app.
- _SERVICE_: Kafka Ingress/Egress service, uses Payload …
=> Consolidate APP_SETTINGS and RuntimeEnvironment

api/host.py, api/metrics.py
To prepare to deprecate host creation through the REST API we want to have some metrics to know how many people are still using it. This PR adds a new counter `rest_post_request_counter` to Prometheus.
=> Add a metric to track POST requests on the REST API [RHCLOUD-5004]

app/queue/event_producer.py
The issue was with using a variable that was no longer defined. Updated it to fit in with the new variables.
Verified that the PATCH produces a message and produces the info log message in the `message_produced` function.
Log output below: 
> [2020-06-23 22:37:12,360] [3985] [140457689134784] [inventory.api] [DEBUG] Leaving patch_by_id
> [2020-06-23 22:37:12,368] [3985] [140457413465856] [inventory.app.queue.event_producer] [INFO] Message PRODUCED offset=95 timestamp=1592966232358 topic=platform.inventory.events, key=358e5aff-8ee1-45cc-80e7-fc8ff7277903, headers={'event_type': 'updated'}
=> fixed event producer throwing error when event is successfully produced

app/queue/events.py, test_api.py
`created` and `updated` events already has it.
=> Add metadata to delete events (RHCLOUD-5224)

app/instrumentation.py, app/queue/event_producer.py
Fixed error handling and instrumentation in the event producer.
- If the message production fails, it is no longer logged as success. Moved the instrumentation to the callback.
1. Add a sleep before the actual production.
2. Make the Inventory produce an event.
3. Shutdown Kafka or somehow block its port.
4. See that the event is **not immediately** logged as produced.
5. See that the success count is **not immediately** incremented.
6. Wait until the production timeouts.
7. See that the event is **then** logged as not produced.
8. See that the falure cound is **then** incremented.
9. See that the success count is still not incremented.
- If there is an immediate error and the future is not even created, this logged as a failure too. No other exception is caught.
Steps …
=> Event metrics fix

swagger/api.spec.yaml
As part of the deprecation of the host update/create functionality on the REST API we want to make sure users know about the deprecation. This PR marks the POST operation as deprecated in the swagger docs. Below is a preview of the change.
=> Add deprecation notice to host create/update in API spec

app/queue/events.py, app/queue/metrics.py
- Add's `event_type` label to the ~`egress_event_serialization_time`~ `event_serialization_time` metric so that we can compare the serialization times between the different event types. 
- Renames the prometheus metric from `inventory_egress_event_serialization_time` to `inventory_event_serialization_time` to reflect the broader role the metric now serves. It felt inappropriate to have egress in the name when it's also monitoring events built for the `events` topic.
~Dependent on the [event refactor PR](https://github.com/RedHatInsights/insights-host-inventory/pull/651).~
=> Split event metrics [RHCLOUD-5645]

tests/test_api_hosts_create.py, tests/test_api_hosts_delete.py, tests/test_api_hosts_get.py, tests/test_api_management.py, tests/test_api_utils.py, tests/test_culling.py, tests/test_culling_utils.py, tests/test_delete_utils.py, tests/test_xjoin.py
Two little follow-up changes to #655.
- Consolidated abstract test names, so they all end with _BaseTestCase_.
- Extracted the Management test case from the Utils file.
The database locking should not be a problem. When an exception is raised, Pytest still tears down the fixtures gracefully. The problems happens only if the process is killed unconditionally before it even manages to do the teardown. Nothing we should care about.
Resolves [RHCLOUD-7870](https://projects.engineering.redhat.com/browse/RHCLOUD-7870), a subtask of [RHCLOUD-7076](https://projects.engineering.redhat.com/browse/RHCLOUD-7076).
=> Final touches to unit test refactor step 1

app/__init__.py, swagger/api.spec.yaml
With the system profile schema separation we adopted a new lib to parse the swagger specification.
This new lib messed up the internal references on the generated openapi spec: https://qa.cloud.redhat.com/api/inventory/v1/openapi.json
To avoid this internal reference problem, let's make the lib explicitly only resolve references from files.
=> Internal openapi references resolution

tests/test_utils.py, utils/deploy.py
Follow up to #693.
Added _-s/--stage_ and _-p/--prod_ switches to limit deployment only to the specified targets. If none is provided, no change is done. Provide both to deploy to both environments.
How to test:
1. `$ pipenv run python utils/deploy.py abc1234  < ../app-interface/data/services/insights/host-inventory/deploy.yml`
2. See that nothing changed.
3. `$ pipenv run python utils/deploy.py -s abc1234  < ../app-interface/data/services/insights/host-inventory/deploy.yml`
4. See that only staging deployments image tags changed.
5. `$ pipenv run python utils/deploy.py -p abc1234  < ../app-interface/data/services/insights/host-inventory/deploy.yml`
6. See that only production deployments image tags changed.
7. `$ pipenv run python utils/deploy.py -s -p abc1234  < …
=> Deploy to stage and/or production environments

utils/kafka_producer.py, utils/payloads.py
This makes a few adjustments to the Kafka producer to generate hosts to be created in the inventory.
It allows to set the number of hosts as well as the account they should be created for.
It also uses the random uuid to not have them all be named the same.
=> Kafka producer additions

app/__init__.py, app/models.py, swagger/system_profile.spec.yaml, tests/test_api_hosts_create.py, tests/test_mq_service.py, tests/test_unit.py, utils/payloads.py
Message Queue API Ingress uses externalized System Profile schema for validation. The schema has been updated to the [current version](https://github.com/RedHatInsights/inventory-schemas/blob/b4436190454610e93e2d73815d2510e15e817196/schemas/system_profile/v1.yaml) with all Marshmallow constrains included.
There are however some changes, so the schema can be easily used:
* Schema version downgraded to Draft 4 so it is compatible with Connexion that uses the file too.
* The recursive _NestedObject_ definition has been removed. It is not compatible with JSON Schema Draft 4. Empty key validation is done manually.
* Object types are explicitly defined, so Connexion’s type coercion used by our custom validation works properly. There is already a PR to fix this.
=> Use externalized schema for system profile validation

lib/middleware.py, tests/helpers/api_utils.py, utils/rbac-mock-data/inv-star-read.json, utils/rbac-mock-data/inv-star-write.json
[Companion change to config](https://github.com/RedHatInsights/rbac-config/pull/95)
This adds support for permissions like `inventory:*:read`
=> Expand the rbac permissions

app/queue/queue.py
I'd like to open this up for discussion. In the Kibana instance of the crcp01ue1  cluster, a large quantity (Kibana is showing 8400 / 11000) of the field mappings are being taken up by the input.* fields. By swapping to a json string, we can keep the data and limit the fields that are being created. Let me know your thoughts on the change here. I'll include the ticket below. 
https://issues.redhat.com/browse/RHCLOUD-9488
=> Make tags into json string

README.md
Replace reference to individual mergers `@Glutexo and @jharting` with team `@RedHatInsights/host-based-inventory-committers`.
=> Updated README.md with committers team reference.

swagger/system_profile.spec.yaml
Bring local `system_profile.spec.yaml`  in closer alignment with https://github.com/RedHatInsights/inventory-schemas/blob/master/schemas/system_profile/v1.yaml.
This PR is only updating the `description` and `example` properties.
=> Update description and example properties to match schema repo

api/host.py, app/config.py, app/culling.py, lib/host_repository.py, swagger/api.spec.yaml, tests/helpers/api_utils.py, tests/helpers/mq_utils.py, tests/test_api_hosts_update.py, tests/test_culling.py, tests/test_unit.py
This PR is meant to address [RHCLOUD-9412](https://issues.redhat.com/browse/RHCLOUD-9412).
This adds a PUT endpoint that accepts a list of canonical facts and a time offset (in minutes). Given the list of canonical facts, it should find one specific host, and update its staleness timestamp using the supplied time offset.
=> Ultra-Light Check-In

tests/test_system_profile.py
Since RBAC is getting enabled outside of CI I thought it'd be a good idea to add some tests making sure it works right for the new endpoint
=> Add RBAC tests for system_profile

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
Updates the namespace in the Grafana to "host-inventory-{env}" instead of "platform-{env}". I'm guessing this one wasn't working for Stage before.
=> Update namespace in the Grafana dashboard

api/host_query_xjoin.py, app/xjoin.py, tests/test_xjoin.py
Modified xjoin filter to allow for case insensitive Inventory name search.
JIRA:  https://issues.redhat.com/browse/RHCLOUD-10247
=> RHCLOUD-10247: Allow for case insensitivity on Inventory name search

api/system_profile.py, api/tag.py, swagger/api.spec.yaml, tests/test_xjoin.py
Hooks up inventory to the new xjoin-search feature allowing users to search for sap_sids with partial matching. Because it's reliant on xjoin-search to work I cannot create a full integration test, please test manually to check that it's working (it does on my machine)
=> Add search to system profile /sap_sids endpoint

swagger/api.spec.yaml
Addresses @Glutexo 's final comment in this Jira: https://issues.redhat.com/browse/RHCLOUD-10385
It just updates the API spec to expect a 404 instead of a 400.
=> Fix HTTP status for /checkin endpoint in API spec

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
Adds a section highlighting metrics related to our service level objectives.
Service Level Indicators
- Latency of HTTP requests
- Number of HTTP 5xx responses
- Consumer lag on ingress topics
- Number of ingress processing errors
- Not processing any messages over a given period of time (current: 5mins)
=> Add SLI section to grafana [RHCLOUD-10103]

tests/test_xjoin.py
Python 3.7 changed _re.escape_ to escape only regular expression control characters. See the note [here](https://docs.python.org/3.8/library/re.html#re.escape). That means that non-ASCII characters and some special ASCII characters like ! or / are no longer escaped. In one test, the escaped string was passed as a literal, not itself using the re.escape function. Fixed by reusing re.escape in the test.
This is still not 100% correct, because we are using Python _re.escape_ to escape a regular expression that is passed to Crossjoin. The Inventory does not know what regex engine does Crossjoin use and it should not matter at all. Crossjoin should describe its regex engine including what characters need to be escaped. The current behavior incorrectly assumes that whatever engine Crossjoin …
=> Fix Xjoin test on Python >=3.7

Pipfile.lock
Pytest uses _importlib_metadata_ that got moved to _importlib.metadata_ in newer Python versions. importlib-metadata has been added as a dependency, but it is not included in Pipfile.lock. Regenerated the lock file so that it works with Python 3.8 as well as with Python 3.6.
=> Regenerate lockfile

app/models.py, swagger/system_profile.spec.yaml
The os major/minor/name PR [0] just merged in puptoo and ci is having issues with it.  We suspect it's due to the use of List not Dict in the Marshmallow portion of the schema.  Could replace with fields.Dict or omit entirely.  Any feedback on this is appreciated, we'd like to get a fix out rather quickly.  Thanks!
Update: it appears to be due to the use of a bare reference instead of inline definition
[0] https://github.com/RedHatInsights/insights-puptoo/pull/82
=> operating_system fact should be dict not list

swagger/api.spec.yaml
The missing attribute is causing exceptions when generating JS clients.
cc @Glutexo @kruai
=> Add missing items type to NonNullableStringArray definition.

app/models.py, tests/helpers/test_utils.py, tests/test_system_profile.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-8583).
This adds the owner_id into event output, and adds test to check it's present in API responses.
=> add owner_id to event output [RHCLOUD-8583]

api/host.py, tests/test_api_hosts_update.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-9545).
Currently the patch event emitted when a host is updated is contains the previous `updated` timestamp instead of the current value. This PR fixes that and adds a test to verify that the new `updated` timestamp in the event is up to date.
=> Fix patch timestamp [RHC-9545]

host_synchronizer.py
@jharting, to get some idea of how many hosts are updated in 20 minutes with 100 chunk size, the host_synchronizer script has been updated to log count after each host is synchronized.  
You can approve this PR and submit an MR against app-interface using `fb671e6e566c4ec1b513c3dbbd153320d5eb61ae` for the `inventory-host-synchronizer` saas template.   It will attempt to run the job once for 20 minutes.  The pod log should show "Number of hosts synchronized".  Stopping the job normally may yield some useful info.
I watched the pod log and it synchronized 1322 hosts in 8 minutes when console stopped the watch even the pod was running.  This very likely was caused by xterm running out of resources.
FWIIW, in my dev environment, I have successfully processed 3115 hosts with local DB and Kafka …
=> rhc-10807: record count when a host is synchronized

app/models.py, swagger/system_profile.spec.yaml
Even though SAP installs cannot have 98 or 99 as their instance number, these are valid coming from diagnostic tools so we need to relax our schema validation and the regex in our model to allow these values.
https://issues.redhat.com/browse/HBISPSC-37
=> Relax regex for sap_instance_number to allow 98/99

swagger/api.spec.yaml, tests/test_api_hosts_get.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11693).
Right now HBI is responding with 500 errors when it receives improperly formatted UUIDs. It appears that the inbuilt UUID format is not strict enough. This PR introduces a stricter regex pattern that will make the inventory properly reject requests with improper UUID formats and respond with a 400 status. 
I also included a test that verifies that the improper ids that QA identified are now properly rejected.
Here is a link to a regex checker with the pattern for easy verification
https://regex101.com/r/oCLpe8/1
=> Fix bad id 500

build_deploy.sh
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11665).
To ensure that the ci, qa, and smoke envs have the newest images, we need to push those to quay. We will be updating e2e deploy soon after this merge once we can verify the tags exist.
=> Always push qa and latest tags for v3 and Clowder compatibility

build_deploy.sh
Reverts RedHatInsights/insights-host-inventory#786
We don't want every PR check to push to `latest` and `qa`, so we'll need to figure out a different approach (or the same approach, but with additional changes).
=> Revert "Always push qa and latest tags for v3 and Clowder compatibility"

app/instrumentation.py, app/queue/metrics.py, app/queue/queue.py, tests/test_mq_service.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-7979).  As host-inventory consumes messages from Kafka and updates the DB and produce events, the `inventory-mq` containers may be find RDS inaccessible for any reason.  When that happens, the mq container should exit and the pod be restarted. 
=> rhc-7979: Restart POD when DB is not accessible by inventory-mq

api/host_query_xjoin.py, api/system_profile.py, api/tag.py, tests/helpers/api_utils.py, tests/test_xjoin.py
This PR is to fix the issue where the insights classic identity cause 500 errors when xjoin is the data source by expanding our workaround.
=> Add insight classic workaround to xjoin

api/host_query_xjoin.py, api/system_profile.py, api/tag.py, tests/helpers/test_utils.py
Changing the logic to short circuit and avoid a 50 error from classic identity since it actually has not cert type. Updated identity used in tests to reflect that there is not cert_type in classic identity. I want to verify that the system field even exists in these identities before we merge this since it seems odd that they would send us an empty field, and it's emptyness could lead to more problems.
=> short circuit to avoid 500 when no cert type. 

api/host_query_xjoin.py, api/system_profile.py, api/tag.py, lib/host_repository.py, tests/test_xjoin.py
This PR disables filtering based on `owner_id`.  It will remain disabled until all existing hosts in Prod have been updated with system_profile containing owner_id.
=> disable filtering based on owner_id

api/host_query_xjoin.py, api/system_profile.py, api/tag.py, lib/host_repository.py, tests/test_xjoin.py, utils/payloads.py
This PR reenables hosts filtering based on `owner_id`.  The work involved uncommenting the code commented in https://github.com/RedHatInsights/insights-host-inventory/pull/803.
Executed tests using pytests and all passed.   Yet to verify in the xjoin integrated environment.
@ryandillinfelton, if you have a moment, can you please verify that the xjoin is working.  Thanks.
=> re-enable owner_id based filtering

app/models.py, swagger/system_profile.spec.yaml, tests/helpers/system_profile_utils.py, tests/helpers/test_utils.py, utils/payloads.py
Add cpu model name as cpu_model to system profile as requested:
https://issues.redhat.com/browse/HBISPSC-39
Related PRs:
https://github.com/RedHatInsights/inventory-schemas/pull/44
https://github.com/RedHatInsights/insights-puptoo/pull/117
=> Add model name as cpu_model to system profile

api/system_profile.py, lib/system_profile_validate.py, system_profile_validator.py, tests/test_system_profile.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-11720).
`system_profile_validator.py` is a script that checks, validates, and comments on PRs opened to the inventory-schemas repo. If you set `GIT_USER` and `GIT_TOKEN`, it will log in as that user (preferably a bot account) and validate. I intend to set this up as a CronJob in Prod using the NachoBot account, unless there's a better bot to use.
The script looks all open PRs in the repo. If the PR modifies the System Profile spec file, and either the supplied account has not yet commented on the PR, or the PR has a commit more recent than its most recent comment, it will run validation. It uses a KafkaConsumer to parse host data from the past 3 days of Kafka messages. Then, it runs validation against …
=> Add github bot that validates SP schemas

api/system_profile.py, lib/system_profile_validate.py, system_profile_validator.py, tests/test_system_profile.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12307).
Some issues remain that can't be seen in local testing environments. This PR aims to fix the following issues:
- Many messages are being read by the validator, but most of them fail to match the OperationSchema format. This leads me to believe that messages from other topics were getting read. I've added code to force the validator to only read from the configured ingress topic.
- For some reason, the total message count works locally, but does not work consistently in Prod. I've changed the way this value is tracked to make it more consistent.
- When dippy-bot wasn't posting comments to PRs, all we would know was the response code (403). Now it logs the specific error, which can help us to …
=> Always force ingress topic; fix total message count; log POST errors

swagger/system_profile.spec.yaml, utils/payloads.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12582).
This just adds the boolean `is_marketplace` field to the system profile.
The corresponding inventory-schemas PR [is here](https://github.com/RedHatInsights/inventory-schemas/pull/52).
=> Add is_marketplace boolean field to system profile

api/system_profile.py, app/config.py, lib/system_profile_validate.py, swagger/api.spec.yaml, system_profile_validator.py, tests/helpers/mq_utils.py, tests/test_api_auth.py, tests/test_system_profile.py, utils/kafka_producer.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12307) (again).
After discussing with Jozef and Chris Mitchell, I found out that the validator needs a slightly different approach. Here is a summary of changes I made in this PR:
- Changed the validator's consumer_group_id to be distinct from the standard inventory-mq one.
- Added the ability to limit the number of messages the validator processes (for performance reasons).
- Added support for 2 new env vars to make deployment configuration easier and faster.
- Made the validator subscribe to both the host-ingress and host-ingress-p1 topics, by default.
- Changed the validator's behavior to poll repeatedly until there are no new messages, the message limit is reached, or the offset has caught up to …
=> SP Validator: fixes, enhancements, performance improvements, tests

app/config.py, lib/system_profile_validate.py
This PR will make it easier to debug, and may possibly address, [this Jira](https://issues.redhat.com/browse/RHCLOUD-12982).
First and foremost, this PR greatly reduces the number of messages returned by the poll (down to 100). I had overestimated how well the pods would be able to churn through the data, so this will make it easier for them. It also reduces the default maximum number of hosts to 10,000 (configurable through env vars).
Secondly, this will improve the logging experience. I removed the stacktrace from the expected validation error logs, and moved the informational "Polled x hosts from queue" to right after the poll occurs (for easier Prod troubleshooting).
=> Reduce max records per poll; improve log-browsing experience

utils/payloads.py
Using `"test"` as the `account_number` in `payloads.py` allows us to keep using the header we have been using all along and also makes it easier to integrate with `xjoin-search`.
=> Use test for account_number

swagger/system_profile.spec.yaml, tests/helpers/test_utils.py, utils/payloads.py
This PR is being created to address [RHCLOUD-11879](https://issues.redhat.com/browse/RHCLOUD-11879).
> Issue on HBI to process the yupana request "System profile does not conform to schema" - SELinux with "Inappropriate ioctl for device"
The corresponding inventory-schemas PR is https://github.com/RedHatInsights/inventory-schemas/pull/54
=> Change selinux_config_file from enum to allow a string

app/models.py, tests/test_models.py
This PR is being created to address [RHCLOUD-13105](https://issues.redhat.com/browse/RHCLOUD-13105).
It allows reporters to update a Host's `display_name` if the Insights ID hasn't been set.
This functionality is required to support rhsm-conduit's hypervisor/vsphere implementation.
=> Allow reporters to update display_name if insights_id isn't set

api/host.py, api/host_query.py, api/host_query_db.py, api/host_query_xjoin.py, app/__init__.py, app/serialization.py, swagger/api.spec.yaml, tests/helpers/graphql_utils.py, tests/test_api_hosts_get.py, tests/test_xjoin.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12849).
The goal of this PR is to enable fetching of some system_profile fields from the `/hosts` endpoint using sparse fields.
This PR does not intend on  changing the current response in `host_list` endpoint. Users will need to mention the `fields` query parameter if they want to fetch system_profile data through the `host_list` endpoint. If HBI is using the `db` and/or the user does not mention the `fields` query parameter, the response should remain same as it is today.
=> Host List Sparse System Profile Response - RHCLOUD-12849

swagger/system_profile.spec.yaml, tests/helpers/system_profile_utils.py, tests/helpers/test_utils.py
This PR is being created to address https://issues.redhat.com/browse/HBISPSC-51 to split out the gpg_pubkey from the rpms in installed_packages or installed_packages_delta and still keep them as a separate fact.
=> Add gpg_pubkey array to system profile

app/queue/queue.py, tests/fixtures/mq_fixtures.py, tests/test_mq_service.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-12813).
Adds dashes to the value of subscription_manager_id when we set that to `system.cn` or `system_profile.owner_id` for hosts reported by `rhsm-conduit`.
=> Transform subscription_manager_id to have dashes when setting it to owner_id [RHCLOUD-12813]

app/models.py, app/queue/queue.py, app/serialization.py, lib/host_repository.py, tests/helpers/system_profile_utils.py, tests/test_models.py, tests/test_mq_service.py, tests/test_unit.py
This PR is being created to address [RHCLOUD-13461](https://issues.redhat.com/browse/RHCLOUD-13461), [RHCLOUD-13466](https://issues.redhat.com/browse/RHCLOUD-13466), and [RHCLOUD-13505](https://issues.redhat.com/browse/RHCLOUD-13505).
Separates out a functionality-restricted version of the Host schema and model, named LimitedHost. LimitedHost acts as a bean of sorts, and cannot be added/updated in the DB. Host extends LimitedHost, but requires the reporter and stale_timestamp fields, and has all the usual access.
I created `model_builder()` in LimitedHostSchema and HostSchema so that we could keep our generic Host-deserialization functionality, while having it generate the correct model type.
=> Schema changes to support system-profile MQ service

app/queue/queue.py, tests/test_mq_service.py
This is a fix addressing rhsm-conduit's issues regarding not sending platform_metadata.
They weren't made aware that we were making platform_metadata a requirement, and we need to not break our support for them.
=> platform_metadata fix for rhsm-conduit

app/queue/queue.py
This PR is being created to address [RHCLOUD-13580](https://issues.redhat.com/browse/RHCLOUD-13580).
This just adds `host.reporter` to the extra data in the log, which supports our Kibana queries.
=> Add host.reporter to extra data in ValidationException logs

app/models.py, tests/test_models.py, tests/test_mq_service.py
This PR is being created to address [RHCLOUD-13330](https://issues.redhat.com/browse/RHCLOUD-13330).
This removes the workarounds we implemented for `display_name`, due to the various restrictions that ended up being required. [RHCLOUD-5954](https://issues.redhat.com/browse/RHCLOUD-5954) added the first workaround because Yupana kept overwriting the `display_name` field. Later, we completed [RHCLOUD-13105](https://issues.redhat.com/browse/RHCLOUD-13105), which allowed some reporters to set the field if they didn't have an Insights ID. We eventually decided that this logic should not be owned by HBI, and that the offending reporter (Yupana) should just stop constantly overwriting that field.
The Yupana team has already merged [their PR](https://github.com/quipucords/yupana/pull/346), which …
=> Remove display_name workaround

app/auth/identity.py, app/queue/queue.py
This PR is being created to add details to our logging, which will help us debug issues in Stage/Prod.
It adds the input values for invalid cert_type and auth_type, and re-adds the "host.reporter" structure to validation error logs.
Omitted the rest of the description this time, as it's kind of a hotfix.
=> Add details to Identity errors, and re-add host.reporter structure

app/instrumentation.py
This should avoid some `KeyError` I was seeing during the prod outage this past weekend. This also makes the log message more meaningful.
=> Improve logging of db access failures

app/queue/queue.py
No Jira for this one. Just adds the reporter to the log we create when we get a value error (like cert_type) while trying to create/update a host. This is specifically to help figure out the cert type bug.
=> log reporter with cert type value errors (and other value errors)

app/queue/queue.py
Labeling validation exceptions as `Exceptions` increments a different metrics. I think using `InventoryException` should increment the correct one and hopefully the alerts will stop. :pray: 
cc: https://github.com/RedHatInsights/insights-host-inventory/pull/868
=> Increment correct metrics for ValidationException

app/auth/__init__.py, app/auth/identity.py, app/queue/queue.py, tests/test_unit.py
This PR is being created to address [RHCLOUD-13572](https://issues.redhat.com/browse/RHCLOUD-13572).
It adds checks to the Identity constructor so that we raise ValueErrors instead of KeyErrors. It also simplifies/organizes the logic to make it easier to read.
=> Add checks to Identity constructor

app/auth/identity.py
This PR is being created to address [RHCLOUD-13924](https://issues.redhat.com/browse/RHCLOUD-13924).
I originally opened this as a hotfix for [RHCLOUD-13572](https://issues.redhat.com/browse/RHCLOUD-13572), as I had mistakenly changed `auth_type` to be required for all Identities instead of only for system-type Identities. However, @lphiri informed us that "auth_type" shouldn't be a required field, so I'm removing that requirement from the Identity class.
=> Remove Identity.auth_type requirement

app/auth/identity.py, tests/test_unit.py
This PR is being created to address [RHCLOUD-13951](https://issues.redhat.com/browse/RHCLOUD-13951).
Insights Classic sends a number of identities that don't adhere to the agreed-upon structure. This change makes it so HBI doesn't complain if it receives a user-type Identity that doesn't provide a "user" object in the Identity.
=> Remove user requirement from Identity

app/auth/identity.py, tests/test_unit.py
This PR is being created to address [RHCLOUD-13959](https://issues.redhat.com/browse/RHCLOUD-13959).
Changes:
- Raise ValueError when Identity.auth_type is a blank string
- Raise ValueError when Identity.cert_type isn't one of the Enum values
- Add unit tests to validate these cases
=> Identity: Disallow blank string for auth_type; re-add cert_type check

app/auth/identity.py, app/queue/queue.py, tests/test_mq_service.py
This PR is being created to address [RHCLOUD-13840](https://issues.redhat.com/browse/RHCLOUD-13840).
Changes:
- Verify Identity within `add_host` rather than `handle_message`
- Update `update_system_profile` to generate a mock Identity based on the host data
- Remove unnecessary mocks from some MQ tests
=> Don't require Identity for messages from system-profile topic

api/host_query_xjoin.py, docs/_index.md, tests/test_xjoin.py
This PR is being created to address [this Jira](https://issues.redhat.com/browse/RHCLOUD-13856).
This PR enables filtering of `system_profile.host_type` filter. There isn't much difference between this filter and the ones we have for `rhc_client_id` and `owner_id`.
This functionality won't work until the [xjoin-search PR](https://github.com/RedHatInsights/xjoin-search/pull/97) is merged.
=> Adding host_type filter

app/auth/identity.py
This PR is being created to address [RHCLOUD-14158](https://issues.redhat.com/browse/RHCLOUD-14158).
Removes Identity restrictions for classic-proxy API requests. Now, if auth_type is provided and set to "classic-proxy", the Identity only needs to have an account number, Identity type, and auth_type (obviously). 
This also removes the "Insights_Classic_System" value from possible IdentityTypes.
=> Remove restrictions from classic-proxy requests; remove unused type

app/config.py, deployment.yaml, tests/fixtures/api_fixtures.py
This PR is just for cleanup, so no Jira this time. I'm just removing the `REST_POST_ENABLED` environment variable, since we don't use it anymore.
=> Remove unused REST_POST_ENABLED env var

deployment.yaml
For testing in ephemeral envs, rbac needs to be present to do anything useful with the inventory API.
Listing rbac as an optional dependency will cause bonfire to deploy it unless `--no-get-dependencies` is specified.
=> List the rbac ClowdApp as a dependency

.pre-commit-config.yaml
Since we are now using Python 3.8.
_reorder-python-imports_ supports _--py37-plus_ as its maximum.
```
--py37-plus           Remove obsolete future imports (generator_stop). implies: --py22-plus, --py23-plus, --py26-plus, --py3-plus
```
_pyupgrade_’s most recent support is still _--py36-plus_, so no change there.
```
--py36-plus
```
=> ⬆️ Bump reorder-python-imports pre-commit hook to use --py37-plus

app/auth/identity.py, tests/test_unit.py
This PR is being created to address [RHCLOUD-14391](https://issues.redhat.com/browse/RHCLOUD-14391).
Some host-ingress messages are failing because the `cert_type` is set to "RHUI", while Identity allows only lowercase values. This PR changes `cert_type` and `auth_type` to be case-insensitive.
=> Make cert_type and auth_type case-insensitive

app/auth/identity.py, tests/test_unit.py
This PR fixes a bug that I introduced in #914. When an Identity has `auth_type == None`, the app hits an AttributeError.
This resolves that issue, and adds a test that verifies as much.
=> Fix AttributeError when `auth_type` is None

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR removes a single comma to fix the JSON syntax on the dashboard. My brain must have still been in python mode when I made this change.
=> Grafana syntax fix

deployment.yaml
This seems to fix the certifi import issues when running in kubernetes. I'm not sure why but I suspect there's an issue with the virtual environment when `python` is called directly.
=> Use /bin/sh -c on container startup commands

swagger/system_profile.spec.yaml
Signed-off-by: Christopher Sams <csams@redhat.com>
This PR is being created to address [RHELPLAN-80227](https://issues.redhat.com/browse/RHELPLAN-80227).
Adding a boolean that indicates whether greenboot detected an OS update that was rolled back.
See also:
- [Schema update](https://github.com/RedHatInsights/inventory-schemas/pull/66)
- [puptoo update](https://github.com/RedHatInsights/insights-puptoo/pull/161)
=> Add greenboot fallback detected bool to system profile.

swagger/system_profile.spec.yaml
This PR is being created to address [RHCLOUD-14535](https://issues.redhat.com/browse/RHCLOUD-14535).
It adds min/max values to System Profile int fields, since exceeding these values can lead to 5xx on our end.
inventory-schemas PR here: https://github.com/RedHatInsights/inventory-schemas/pull/67
=> Set min/max for System Profile integers

swagger/system_profile.spec.yaml
This PR is being created to address [RHCLOUD-14537](https://issues.redhat.com/browse/RHCLOUD-14537).
Adds regex escapes to the `sap_version` field, which currently allows any 22-number string.
inventory-schemas PR here: https://github.com/RedHatInsights/inventory-schemas/pull/68
=> Add regex escapes to sap_version field

app/models.py, tests/test_mq_service.py
This PR is being created to address [RHCLOUD-14532](https://issues.redhat.com/browse/RHCLOUD-14532).
It changes the functionality to stop allowing the "tags" field to be set to null/None. We used to allow it to be set to null, and would just replace it with `{}` if it was. However, this was planned to be phased out, and the time has come.
=> Don't allow "tags" field to be null

deployment.yaml
This PR is being created to address [ESSNTL-790](https://issues.redhat.com/browse/ESSNTL-790).
Our Clowder-based deployments and services have "inventory" in them twice, e.g. "host-inventory-inventory-mq-p1". This PR fixes that.
=> Fix clowder-based service/deployment naming

deployment.yaml
These won't probably resolve the ongoing partial outage in stage. I am adding these for safety, atm. There are other kafka ssl configs, but those won't get checked unless we use the `sasl_ssl` kafka security protocol.
N.B. just adding an empty directory for the `kafka-cacert`. If the `KAFKA_SECURITY_PROTOCOL` environment variable is set to `PLAINTEXT`, it shouldn't try to read it.
=> Adding optional kafka ssl config vars

app/models.py, tests/test_models.py
This PR is being created to address [ESSNTL-824](https://issues.redhat.com/browse/ESSNTL-824).
If we update a Host and its old display_name is set to its ID, we should set the display_name to the FQDN.
This is one of the features that was discussed after a bunch of email exchanges. Without this change, the display_name is saved to the ID upon a Host's creation, so if the FQDN isn't specified at that time, it will never default.
=> Set display_name to FQDN on update, if it's set to the ID

app/__init__.py, app/config.py, inv_mq_service.py
This PR is being created as part of [ESSNTL-761](https://issues.redhat.com/browse/ESSNTL-761).
It makes it so the metrics endpoint is separate from the other API traffic, and is configurable via Clowder.
I also added a small update to the MQ service's config to make its metrics path configurable as well (only the port was configured before).
=> Add separate metrics server for API

inv_mq_service.py
The MQ config was busted by my last PR: https://github.com/RedHatInsights/insights-host-inventory/pull/945
I incorrectly assumed that both `start_http_server()` calls would take the same params. I'm reverting that change here.
=> Hotfix: Remove endopint param from MQ metrics server command

app/config.py, app/payload_tracker/__init__.py, deployment.yaml
This PR allows the loading of Kafka SSL credentials the preffered way for clowderized apps and also does some refactoring around it.
For Reference:
* The `BrokerConfig` for clowderapps: [here](https://github.com/RedHatInsights/app-common-python/blob/master/schema.json#L155-L176)
* Example from `insights-ingress-go`: [here](https://github.com/RedHatInsights/insights-ingress-go/blob/master/config/config.go#L136-L153)
=> Loading kafka ssl creds the correct way for clowder + refactoring

deployment.yaml
This PR is being created to address [this Jira](https://issues.redhat.com/browse/ESSNTL-623).
PR to add the deployment config for the new `pendo-syncher` cronjob.
=> Adding pendo-syncher deployment config

deployment.yaml
This PR is being created to address issues brought up in CoreOS Slack ([this thread](https://coreos.slack.com/archives/C022YV4E0NA/p1626684947407900), for instance). This will suspend jobs in all envs by default, including the ephemeral cluster; I'll make an MR afterwards to set these to "true" for Stage and Prod.
=> Suspend jobs by default (reaper/sp-validator)

app/config.py
This PR is being created to address [ESSNTL-949](https://issues.redhat.com/browse/ESSNTL-949).
This changes how we access our kafka broker_config attributes to be more pythonic. In turn, this should fix the error we're seeing every time Reaper runs in the Stage environment.
=> Handle broker_config attributes in a pythonic way

deployment.yaml
This PR is being created to address [ESSNTL-959](https://issues.redhat.com/browse/ESSNTL-959).
It changes our SUSPEND variables to use `${{}}` instead of `${}`, which should coerce the data into the appropriate type (instead of leaving it as a string). This should fix the clowder deployment issue we're running into.
For reference, the latest build failure is [here](https://console-openshift-console.apps.app-sre-prod-01.i7w5.p1.openshiftapps.com/k8s/ns/crc-pipelines/tekton.dev~v1beta1~PipelineRun/host-inventory-clowder-insights-stage-202107222003).
=> Fix data types for SUSPEND vars

lib/host_repository.py, tests/helpers/db_utils.py, tests/test_api_hosts_get.py, tests/test_deduplication.py
This PR is being created to address [ESSNTL-773](https://issues.redhat.com/browse/ESSNTL-773).
Our contains/contained_by logic in our canonical-fact-based Host search was inadequate, and led to deduplication when the provided elevated ID wasn't the same type as what was in the DB (insights_id vs subscription_manager_id, for instance). This PR changes that logic so these types of records get merged, so long as they don't have conflicting canonical facts.
=> Canonical-fact-based deduplication

app/serialization.py
Should fix the error caused by xjoin not returning `per_reporter_staleness` data.
=> Hotfix: Set PRS to {} if None or key doesn't exist

lib/host_repository.py, tests/test_deduplication.py
This PR is being created to address [ESSNTL-1059](https://issues.redhat.com/browse/ESSNTL-1059).
It further tweaks the dedup logic to be more precise. Once it's determined that it can't find the host by elevated ID, the basic logic will now match INPUT_HOST to EXISTING_HOST if:
- EXISTING_HOST is in the user's account, AND
- none of INPUT_HOST's canonical facts have different values than EXISTING_HOST's
- at least one of INPUT_HOST's canonical facts is the same on EXISTING_HOST
=> Host dedup logic fix

lib/host_repository.py, tests/test_deduplication.py
This PR is being created to address a bug introduced by [ESSNTL-555](https://issues.redhat.com/browse/ESSNTL-555).
I messed up my original `test_elevated_id_priority_order_match` test, so I didn't realize the dedup logic was faulty. This PR fixes the test and the elevated-id dedup logic.
Here's the original PR that this one's trying to fix: https://github.com/RedHatInsights/insights-host-inventory/pull/978
=> De-duplication bugfix

app/queue/queue.py, lib/host_repository.py, tests/test_deduplication.py
This PR is being created to address [ESSNTL-1146](https://issues.redhat.com/browse/ESSNTL-1146).
One of my previous dedup changes introduced a bug specific to the rhsm-conduit reporter.  The PR that introduced this bug is here: https://github.com/RedHatInsights/insights-host-inventory/pull/983
This PR fixes the bug, which was caused by an incorrect call to `update_query_for_owner_id`. Because of how `owner_id` is set for rhsm-conduit hosts, HBI had not been finding matches.
I added a test for the exact scenario that was failing, because it was caused by our rhsm-specific workaround. I also made a minor change to `get_identity` to allow for better exception handling, because that threw me for a loop while debugging this.  …
=> Fix rhsm-conduit dedup bug

lib/host_repository.py, tests/test_deduplication.py
This PR is being created to fix the issue created by our latest Prod deploy. The PRs that led to this issue are #978 and #983.
This changes the elevated ID search so that it explicitly looks for the best possible match. It first searches for a record that matches all 3 of its elevated IDs, if applicable, and then searches with 2, then just 1. It also adds ordering to these searches, so it always gets the most recent record.
Finally, I added a test which reproduces what we saw in Prod. The issue was that it was finding a basic canonical fact match with a different host, but then rejecting that record because the highest-prio elevated IDs didn't match. 
=> Dedup: Fix Elevated ID matching

deployment.yaml, host_delete_duplicates.py, utils/duplicate_remover_clowd_job_invocation.yaml
This PR fixes the duplicate-hosts-remover job name, which currently has underscores (which aren't allowed).
=> Fix job name

lib/host_remove_duplicates.py, tests/test_duplicate_hosts.py
This PR just changes the duplicate-delete script to use List instead of Set. While Set is faster at identifying whether it already contains a value or not, it uses much more memory when storing a large number of values. List and Deque use similar amounts of memory, but List is faster at checking whether it contains an element. I'm still investigating using Trie in Python, since the implementations I've seen don't appear to have much if any improvement over List, as far as memory/speed
=> Dedup: Use List instead of Set

deployment.yaml
This just adds a new deployment parameter that controls the dedup job's memory limit, separate from the other pods.
=> Add memory limit specific to dedup job

swagger/api.spec.yaml
This PR is being created to address [ESSNTL-1032](https://issues.redhat.com/browse/ESSNTL-1032).
It updates the API schema for the per-reporter staleness field to be more precise. Instead of just defining a general object, it specifies the dictionary structure along with the 3 fields in the "value" part of the key-value pair.
=> Update per-reporter staleness schema to be more precise

host_reaper.py, lib/host_repository.py, tests/test_culling.py
This PR is being created to address [ESSNTL-1237](https://issues.redhat.com/browse/ESSNTL-1237).
Puts an additional filter on Reaper's query so that it excludes Edge hosts. All functionality remains the same, except that hosts with `host.system_profile_facts.host_type = "edge"` are excluded from the query, meaning they don't get deleted.
=> Prevent Reaper from deleting Edge hosts

app/config.py, rebuild_events_topic.py, tests/test_event_rebuilder.py
Changes the `run()` call to use the correct number of arguments, and simplifies KafkaConsumer's implementation (regarding partitions, specifically)
=> Event rebuilder fix

.gitignore, .pre-commit-config.yaml, app/__init__.py, check_schemas.py, swagger/api.spec.yaml, swagger/openapi.json, swagger/pagination.yaml
this helps the codegen and api compat
in this pr we implement bundling of the api specs using a alternate bunlder to avoid the bugs in the native bundlers
related https://issues.redhat.com/browse/RHCLOUD-11860
also related 
* https://github.com/jfinkhaeuser/prance/pull/82
* https://github.com/jfinkhaeuser/prance/issues/76
* https://github.com/jfinkhaeuser/prance/issues/77
=> ESSNTL-746: prepare a alternate normalized openapi spec

api/host_query_xjoin.py, swagger/api.spec.yaml, swagger/openapi.json, tests/test_xjoin.py
This PR is being created to address [ESSNTL-1440](https://issues.redhat.com/browse/ESSNTL-1440).
This is the change required to support the work done in this [xjoin PR](https://github.com/RedHatInsights/xjoin-search/pull/123). Allows the user to sort by the `operating_system` field.
=> Allow sorting by operating_system

Dockerfile
This PR is being created to address the issue discussed in [this Slack thread](https://coreos.slack.com/archives/CCRND57FW/p1637087808474000). They don't know how to fix the issue on their end yet, so they're recommending we pin our UBI8 version until they get it resolved.
After this gets merged, I'll create a follow-up PR to revert this change, which will be placed on hold until the issue is fixed.
=> Temporarily pin the ubi8 version

app/__init__.py, tests/test_unit.py
_TranslatingParser_ does parsing automatically on initialization. Calling it again manually is not only unnecessary, but also inefficient. Removed the call from the _create_app_ function.
Loading, parsing and validating the specification is one of the heavier steps in the app initialization process. Doing it once instead of twice should measurably improve its boot time.
Does not relate to any JIRA ticket. This is a part of my Hackathon work on the Prance library.
=> Remove redundant spec parsing

app/__init__.py, tests/test_unit.py
Reverts RedHatInsights/insights-host-inventory#1041.
The last merge is causing pr_check failures for other services e.g compliance and advisor
=> Revert "Remove redundant spec parsing"

deployment.yaml
There are two CJIs which fail to run correctly when this template is deployed
One fails due to a bad cpu request/limit ratio:
```
Warning  FailedCreate  9m1s   job-controller  Error creating: pods "host-inventory-events-topic-rebuilder-3n4ep5b--1-7pmj8" is forbidden: memory max limit to request ratio per Pod is 2, but provided ratio is 8.000000
```
so I am changing the template to use the CPU_REQUEST/MEMORY_REQUEST parameter everywhere. The values seemed to be set to `200m` and `256Mi` everywhere, which should still be the case since that will match the default values of the parameters.
The other fails because no 'job' exists on the ClowdApp anymore:
```
Conditions:
Last Transition Time:  2021-12-14T18:22:50Z
Message:               Some Jobs are still incomplete
Reason:                No …
```
=> Fix CJIs in template

deployment.yaml
Use separate variable for setting memory request for reaper instead of using the same request as for the service.
This is a followup to [PR1048](https://github.com/RedHatInsights/insights-host-inventory/pull/1048) and [PR1050](https://github.com/RedHatInsights/insights-host-inventory/pull/1050). Since we use a separate variable for reaper memory limit, we should also use a separate variable for reaper memory request.
=> Change reaper memory request

api/host.py, api/host_query_xjoin.py, swagger/api.spec.yaml, swagger/openapi.json, tests/fixtures/api_fixtures.py, tests/helpers/graphql_utils.py, tests/test_api_hosts_delete.py, tests/test_xjoin.py
Reverts RedHatInsights/insights-host-inventory#1011.  Reverting it per standup decision for not having time for testing for prod deployment before the holidays.
=> Revert "Add API endpoint for deleting filtered hosts"

Dockerfile
This PR is being created to address [ESSNTL-1961](https://issues.redhat.com/browse/ESSNTL-1961), which progresses work on the issue discussed in this [Slack thread](https://coreos.slack.com/archives/CCRND57FW/p1637087808474000). It unpins the UBI8 version, and disables a couple of beta RPM repos. 
The issues we saw were caused by newer versions of the UBI8 image using Beta RPM repos, which subscription-manager did not like.
=> Unpin version and disable beta RPMs

api/host.py, api/host_query_xjoin.py, swagger/api.spec.yaml, swagger/openapi.json, tests/fixtures/api_fixtures.py, tests/helpers/graphql_utils.py, tests/test_api_hosts_delete.py, tests/test_xjoin.py
Reverts RedHatInsights/insights-host-inventory#1055
It implements [ESSNTL-1913](https://issues.redhat.com/browse/ESSNTL-1913)
=> essntl-1913: Re-add filtered host-deletion endpoint

Dockerfile, Pipfile, Pipfile.lock, README.md, dev.dockerfile
This PR is being created to address [ESSNTL-2022](https://issues.redhat.com/browse/ESSNTL-2022) and [ESSNTL-2030](https://issues.redhat.com/browse/ESSNTL-2030). It re-fixes the dependency issue we had, adds Snappy support, and adds a constraint restricting the watchtower version to pre-2.0 (so we don't break it).
I originally opened and merged #1066 to address the dependency issue, but when it hit Stage, it was clear that the watchtower and boto3 versions were incompatible. It's unclear why the error did not show up in local testing, or on the ephemeral node in the pr_check.
=> Fix dependencies (again)

docs/_index.md
This PR simply updates the links in our docs folder to point to the updated docs repo (consoledot.pages.redhat.com).
=> Update docs links

api/filtering/filtering.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-2042](https://issues.redhat.com/browse/ESSNTL-2042).
The bug was that `insights_client_version` doesn't return hosts with empy `insights_client_version` fields when queried with an empty string. The behavior was a byproduct of wildcard enabled string fields always using the `matches` when querying xjoin.
We really only need to use `matches` when a `*` is present in the filter value, so this PR conditionally switches between the two operations depending on if a `*` is present in the field value.
=> Make wildcard strings use eq/matches conditionally

api/filtering/filtering.py, api/filtering/filtering_common.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-2039](https://issues.redhat.com/browse/ESSNTL-2039).
The bug was caused by a lack of support for integer fields in system profile. According to past Ryan in a comment xjoin didn't support ints at the time.
I've simply added in a new filter constructor for integers and updated a few enums. I also added tests for integer type fields created by generic filtering in the style of the existing ones for strings, booleans, etc.
This doesn't expand the field to allow for range operations [gt, gte, lt, lte]. I've created a [follow up task](https://issues.redhat.com/browse/ESSNTL-2084) to add that in since there are no existing generic filtering types that support range operations and the implementation could be more complex than I expect. I'd rather keep …
=> Fix 500 when using system profile filter on integer fields

api/filtering/filtering.py, api/filtering/filtering_common.py, app/__init__.py, deployment.yaml, tests/test_api_hosts_get.py
This PR is being created to address [ESSNTL-2069](https://issues.redhat.com/browse/ESSNTL-2069).
This PR makes it so [contains] is no longer considered a valid operand on non-array fields. This was considered misleading because the [contains] operand is intended to be used on array fields to filter on if those fields contain a specific string, so using it on a single string, object, etc, though functionally equivalent to [eq], doesn't make much sense.
Now [contains] is only a valid operand on string and wildcard-string arrays. I figure boolean arrays are unlikely to exist. Adding a contains operand to range queries probably wouldn't make a lot of sense either.
=> Only allow [contains] operand on array fields [ESSNTL-2069]

api/filtering/filtering.py, app/__init__.py, tests/test_api_hosts_get.py
This PR is being created to address [ESSNTL-2136](https://issues.redhat.com/browse/ESSNTL-2136).
Added a specific handling for timestamps. Since they're ultimately a specialized form of string I've added logic dependent on the format property in the system profile schema rather than changing the filter. I think this will be more flexible down the line for other specialized strings with formats (ipv6, ipv4, UUID, etc). Same for specialized numbers like longs. 
I added a test checking that using a non-timestamp string results in a 400 error from the API. Existing happy path tests cover the valid cases.
It came to my attention while working on this that timestamps need support for range operations, but that will be a follow up. …
=> Validate timestamp values for SPF filters

api/filtering/filtering.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-2172](https://issues.redhat.com/browse/ESSNTL-2172).
Until now, we've had to prioritize when filtering on more than 1 of the following:
- fqdn
- display_name
- hostname_or_id
- insights_id
This was likely due to the front-end never sending one of these at a time. This PR makes it so it errors out if you provide more than 1 of these at once, and modifies one of the xjoin tests to validate the new expected output.
=> Handle ID filter combinations

migrations/versions/268debe6db17_add_org_id_column_and_index.py
Add migration to add org_id column, and its associated index to the hosts table.
This PR is being created to address [ESSNTL-2522](https://issues.redhat.com/browse/ESSNTL-2522).
=> Migration to add org_id column, and its associated index to hosts/

.pre-commit-config.yaml, Pipfile, Pipfile.lock, api/parsing.py, app/queue/queue.py, rebuild_events_topic.py, tests/helpers/api_utils.py, tests/test_api_hosts_get.py, tests/test_culling.py, tests/test_mq_service.py, tests/test_unit.py
* autoupdate
* bump to python38 minimals ofr pyupgrade/reorder
* update black url to the new home
=> fix ESSNTL-573: update pre-commit hooks

README.md, docs/pull_request_template.md
This simply adds a reminder about type hinting to the PR checklist, and updates the User identities in our README to include the required `auth_type` field.
=> Add type hinting to PR checklist, add auth_type to user identity in README

api/filtering/filtering.py, api/system_profile.py, swagger/api.spec.yaml, swagger/openapi.json, tests/helpers/graphql_utils.py, tests/test_api_hosts_delete.py, tests/test_api_hosts_get.py, tests/test_unit.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-2448](https://issues.redhat.com/browse/ESSNTL-2448).
The PR updates "registered_with" to accept all reporters in addition to "insights" and add filters for per_reporter_staleness.
This PR should be on hold until "per_reporter_staleness" filters are implemented in "xjoin-search".  
=> Update registered_with to accept all reporters and add per_reporter_staleness filters

app/xjoin.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-2166](https://issues.redhat.com/browse/ESSNTL-2166).
Filtering on "staleness=unknown" returns all hosts, when going through xjoin. This is because the xjoin-specific section ignores the "unknown" staleness filter.
This PR implements this filter.
=> Fixed "staleness=unknown" xjoin search

api/host.py, swagger/api.spec.yaml, swagger/openapi.json
This PR is being created to address [ESSNTL-1969](https://issues.redhat.com/browse/ESSNTL-1969).
- Renames `delete_host_list` to `delete_hosts_by_filter`, since the params are filters rather than a list of host IDs
- Renames `_delete_filtered_hosts` to `_delete_host_list`, since the param is a list of host IDs
=> Rename delete_host_list and _delete_filtered_hosts

api/filtering/filtering.py, swagger/api.spec.yaml, swagger/openapi.json, tests/test_api_hosts_get.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-2797](https://issues.redhat.com/browse/ESSNTL-2797).
Adds the ability to filter on inverse registered_with values. For instance, `?registered_with=!puptoo` would mean "only show me hosts that are not actively being reported by puptoo. `?registered_with=puptoo&registered_with=!puptoo` would mean "show me hosts that are either being reported to by puptoo or _not_ being reported by puptoo, which should be all hosts.
I also verified that the graphql queries this generates work as expected in xjoin-search.
=> Add negative values to registered_with; update tests

Pipfile, Pipfile.lock
This PR is being created to bump our ujson version. Dependabot tried to do that with #1132, but it's having issues with the PR check, so I'm gonna try to do it manually with this one.
=> Bump ujson version from 1.35 to 5.2.0

api/host_query_xjoin.py, tests/test_xjoin.py
HBI returns 500 on /hosts request, through xjoin, if there are no hosts in the database. This is because xjoin returns None in this situation and we try to index that return value.
This PR is being created to address [ESSNTL-1158](https://issues.redhat.com/browse/ESSNTL-1158).
In get_host_list_using_filters(), check response for None before indexing.
=> Check response for None before indexing

api/host.py, tests/test_api_facts.py, tests/test_api_hosts_update.py
This PR is being created to address [ESSNTL-2863](https://issues.redhat.com/browse/ESSNTL-2863).
Adds a event emitter when host facts are updated by namespace.
=> ESSNTL-2863: Inventory doesn't send update event messages after updating facts

api/host.py, swagger/api.spec.yaml, swagger/openapi.json
This PR adds the temporary endpoint `/orgid/{account}`. It takes the account number in the path and translates it to the Org ID. This is needed to help debug the translator issue in Prod.
=> Add temporary OrgID translator endpoint

deployment.yaml
This PR adds the translator-related env vars to the API service deployment. This is to support my previous PR: https://github.com/RedHatInsights/insights-host-inventory/pull/1149
=> Add translator env vars to API service

app/config.py, deployment.yaml
This PR is being created to address [ESSNTL-3090](https://issues.redhat.com/browse/ESSNTL-3090).
Increases `max.partition.fetch.bytes` on the events-topic consumer. This will allow the host-synchronizer job to consume messages on the events topic that are larger than 1 MB.
=> Increase max.partition.fetch.bytes on events-topic consumer

app/config.py
The managed kafka environment does not use a CAFile, but fedramp does.
We need this to be more forgivable so we can still connect without it
if we don't have it.
Signed-off-by: Stephen Adams <stephen.adams@redhat.com>
Working the managed kafka switch and we noticed that this zeroes out the username and password if the cert doesn't exist. This is just a first pass and more might be needed but this seems like it could be part of the problem.
Thanks!
=> [fix] check for the kafka_ssl_file independently

app/config.py
Do not fail with KeyError when we configure other than default value
=> Make it possible to use other than platform.inventory.events topic

deployment.yaml
If we have configured other than default `platform.inventory.host-ingress-p1` in ClowdApp and the code runs through app/config.py, there is:
```
self.additional_validation_topic = topic(
os.environ.get("KAFKA_ADDITIONAL_VALIDATION_TOPIC", "platform.inventory.host-ingress-p1")
)
```
So we need a way how to specify this variable for every app so this cod is happy even if we have this in the ClowdApp:
```
kafkaTopics:
- topicName: platform.inventory.system-profile
partitions: 1
- topicName: platform.payload-status
partitions: 1
- topicName: platform.inventory.events-devel
partitions: 1
- topicName: platform.inventory.host-ingress-devel
partitions: 1
- topicName: platform.inventory.host-ingress-p1-devel
partitions: 1
```
=> Avoid KeyError if we do not have platform.inventory.host-ingress-p1 and app/config.py is used

app/config.py, deployment.yaml
This PR is being created to resolve the KeyError issues we're running into in the perf environment. Since we're allowing for different topic names to be defined in the `kafkaTopics` config in our deployment, it does not make sense to use default/fallback values in `config.py`. Instead, if the topic name is not provided, it simply won't create the topic.
FYI, it's still OK to use default/fallback values in `deployment.yaml`; the main thing is that the topic name in `kafkaTopics` has to be equal to the topic name that `config.py` uses to create the topic.
=> Don't try to create a topic if it isn't used

app/config.py
This PR is being created to address [ESSNTL-3199](https://issues.redhat.com/browse/ESSNTL-3199).
This changes our config class so that, when using Clowder, it will get the security protocol from `broker_cfg.authtype`. When not using Clowder, it will continue to get the value from the `KAFKA_SECURITY_PROTOCOL` environment variable.
=> Get Kafka security protocol from Clowder when using it

swagger/openapi.json, swagger/pagination.yaml, tests/test_xjoin.py
This PR is being created to address [ESSNTL-371](https://issues.redhat.com/browse/ESSNTL-371).
After investigating the xjoin logs for the failing requests, it became clear that the value of the "offset" variable in the query was larger than a 32-bit signed int's max value, which is what graphql is using. 
The offset for our queries is calculated as `(page - 1) * per_page`, and it cannot go higher than 2,147,483,647 (int32 max). Because we don't allow values over 100 for per_page, we can simply restrict the value of `page` to a maximum of 21,474,837.
=> Fix window size limit error

deploy/cji.yml, deploy/clowdapp.yml
This PR is being created to remove the org_id populator job, which was only needed in the Org ID transition period. It removes the job definition from the clowdapp, and the CJI, and the relevant parameters.
=> Remove org-id-populator job

app/config.py
This just re-adds `"group_id": "inventory-events-rebuild"` to the events-topic consumer config. I was hoping that removing it would fix the issue in Stage, but it didn't. It's safer to have a discrete group ID when doing things like `seek_to_beginning()` and setting auto-offset config.
=> Re-add "group_id" to events-topic consumer config

app/__init__.py, pytest.ini, tests/conftest.py
This PR is being created to address [ESSNTL-1915](https://issues.redhat.com/browse/ESSNTL-1915).
Removes the handlers for the loggers when a pytest session is finished to prevent log messages after all the tests pass.
Upon running all the tests, `test_duplicate_hosts.py` still prints a log message. As discussed, it is not to be run regularly since it tests a temporary script.
=> ESSNTL-1915: Tests raise an error after running

api/host.py, api/sparse_host_list_system_profile.py, api/validate_fields.py, tests/helpers/api_utils.py, tests/helpers/graphql_utils.py, tests/test_api_hosts_get.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-629](https://issues.redhat.com/browse/ESSNTL-629).
This PR adds the ability to throw a 400 if a request for a system profile sparse field is a field that is not in our schema for the system profile.
=> [ESSNTL-629] Throw 400 sparse field not in schema

app/queue/notifications.py, app/queue/queue.py, app/serialization.py, tests/test_unit.py
This PR is being created to further address [ESSNTL-2739](https://issues.redhat.com/browse/ESSNTL-2739).
Adds all the canonical facts and request id to the payload sent for the notifications.
=> Adds canonical_facts and request_id to the payload

app/config.py, deploy/clowdapp.yml
This PR is being created to address [ESSNTL-3367](https://issues.redhat.com/browse/ESSNTL-3367).
Since this is probably an issue related to the broker, I'm giving this a shot. This was added in September, and there's a chance this could be the difference that's stopping this particular consumer from consuming messages, from some reason.
=> Remove max_partition_fetch_bytes from events consumer

app/auth/identity.py, tests/test_identity_schema.py
This PR is being created to address [ESSNTL-3493](https://issues.redhat.com/browse/ESSNTL-3493).
Hosts were being rejected when account_number was empty string, but account_number should be allowed to be zero length, as it is not required, and this is reflected in the model but our identity validation did not account for this until now with this PR.
=> [ESSNTL-3493] account_number can be empty string

app/queue/queue.py, tests/fixtures/mq_fixtures.py, tests/test_deduplication.py, tests/test_mq_service.py
This PR is being created to address [ESSNTL-3492](https://issues.redhat.com/browse/ESSNTL-3492).
It fixes the final bullet point on the Jira, which is the null account issue when the account is not set on either the host or the identity for rhsm-conduit payloads.
=> Fix null account issue

api/host_query_xjoin.py, tests/test_api_hosts_delete.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-2212](https://issues.redhat.com/browse/ESSNTL-2212).
Since xjoin can only return 100 hosts at a time, this updates the bulk deletion endpoint to loop through xjoin calls until all desired host IDs are collected, and then returns that list for deletion. The unit test I wrote for this is relatively short but potentially confusing, so I heavily commented it for clarity.
=> Enable deleting over 100 hosts

pytest.ini
This PR is being created to address [ESSNTL-3380](https://issues.redhat.com/browse/ESSNTL-3380).
This PR disables unit tests for `host_delete_duplicates` script. It was just a one-time script that is no longer needed nor developed, so testing it doesn't make sense. However, we don't want to delete the tests completely, so that we can run them in case that we will need to run the script in the future.
=> Disable delete_duplicates tests

deploy/clowdapp.yml
This PR increases the memory request and memory limit for the host-synchronizer job. This is needed because the latest job I ran yesterday was OOMKilled in Stage.
=> Increase memory limit for host synchronizer job

app/config.py, deploy/clowdapp.yml
This PR is being created to address the OOMKill failures that the host-sync job is running into. I'm hoping that decreasing the number of hosts that get loaded into memory at once will make it take up less memory. I think there may still be a memory leak hiding in the code somewhere, but I haven't found it yet.
=> Decrease script chunk size, add env var

rebuild_events_topic.py
This PR just adds some more debug logs to the event-rebuilder job. It also removes the shutdown handler, in case that's what's causing the entire loop to be skipped.
=> Add more debug statements to event-rebuilder job

app/queue/queue.py
This PR is being created to address [ESSNTL-3589](https://issues.redhat.com/browse/ESSNTL-3589).
This fixes the path for the host ID on Delete messages in the events-topic rebuilder. The job works right now, but it outputs stack traces instead of the logging I expected; this PR fixes it so we get cleaner output.
=> Use the correct ID path for Delete events

api/parsing.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-1675](https://issues.redhat.com/browse/ESSNTL-1675).
Overrides the URIParser's query param resolver in order to distinguish between an encoded comma and a non-encoded one. Like with #1208, this also removes support for comma-delimited query params, so I've updated some tests.
=> Allow commas in tag query params

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [ESSNTL-3603](https://issues.redhat.com/browse/ESSNTL-3603). It turns out the data source ID we were using works in Stage, but not Prod. Since Prod is more important, I've updated the data source ID to the one that works in Prod. This will result in a blank panel for Stage, but a working one for Prod.
=> Fix datasource ID for production

tests/helpers/api_utils.py, tests/test_unit.py
This PR is being created to address [ESSNTL-620](https://issues.redhat.com/browse/ESSNTL-620).
The solution for the problem of the hard coded timestamps was already in `test_utils` so I updated the tests that were not using it.
=> ESSNTL-630: Replace hard coded timestamps

app/queue/queue.py
This PR is being created to address [ESSNTL-3503](https://issues.redhat.com/browse/ESSNTL-3503).
This PR fixes the last cases in which a notification should be produced but isn't.
- Checks if `insights_id` is a string before sending it as key for the message
- Raises a ValidationException if `org_id` is not provided
=> ESSNTL-3503: Notification messages bugs

app/models.py, app/serialization.py, tests/test_models.py
This PR is being created to address [ESSNTL-3785](https://issues.redhat.com/browse/ESSNTL-3785).
Throughout the code, our own `ValidationException` has been used to refer to incorrect values received from the customers or reporters, so this PR changes the exception raised by the missing canonical facts and related fields in the same block of code to a `ValidationException`.
=> ESSNTL-3785: missing canonical facts raise different error

swagger/api.spec.yaml, swagger/openapi.json, tests/test_xjoin.py
This PR is being created to address [ESSNTL-728](https://issues.redhat.com/browse/ESSNTL-728).
It defaults the staleness filter to all 4 values, since that's the direction people want to move in. It also removes tests that explicitly test that those default values are applied.
I've tried to remove the need for the defaults entirely, but that requires a fair amount of rework to all of our queries.
=> Make staleness param default to all 4 values

app/queue/queue.py
This PR is being opened because the host-synchronizer produces a ton of logs in Prod, which can cause issues for Kibana.
=> Remove excess host-synchronizer logs

app/config.py
This PR is being created to address [ESSNTL-4077](https://issues.redhat.com/browse/ESSNTL-4077).
In the [migration to confluent-kafka](https://github.com/RedHatInsights/insights-host-inventory/pull/1193), the `group-id` field wasn't changed to `group.id`, and the host-synchronizer and sp-validator jobs are failing as a result. This PR fixes those configs, which should allow the jobs to run again.
=> fix(ESSNTL-4077): Fix the group.id field in Kafka consumer configs

deploy/clowdapp.yml
PMs were requesting the ability to access our three system_profile fields used to determine workload (ansible, mssql, sap) in AWS S3 buckets.  Floorist is not currently adding these three fields; this PR addresses that.
=> Add workloads to floorplan

iqe_tests.sh
This PR is being created to address [ESSNTL-3986](https://issues.redhat.com/browse/ESSNTL-3986).
This is a temporary workaround for the bonfire CICD script issue: https://github.com/RedHatInsights/bonfire/issues/283
In short, the issue is that `oc logs -f` stops reacting after 1 hour and then after another 30 mins of inactivity the job gets aborted and fails. This PR basically just kills the `oc logs -f` after 1 hour and starts it again.
=> ESSNTL-3986: Fix "all tests" PR check pipeline

swagger/api.spec.yaml, swagger/openapi.json
This PR is being created to address [ESSNTL-4070](https://issues.redhat.com/browse/ESSNTL-4070).
Adds `[not implemented]` to group paths to prevent the paths being used by customers. 
=> ESSNTL-4070: add '[not implemented]' to group paths

Dockerfile, Pipfile, Pipfile.lock, unit_test.sh
host-inventory fails to connect to the DB in a FIPS-enabled environment:
```
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL error: disabled for FIPS
```
After doing some research, this is due to the `psycopg2-binary` using an SSL library that was compiled without FIPS support.
Switching away from the binary and building `psycopg2` from source resolves the problem.
This change breaks the unit tests since they were running directly on the jenkins agent VM which does not have the 'devel' packages present on it that would allow `pipenv install` to work when using `psycopg2` instead of `psycopg2-binary`. I have changed them to run using containers. The tests run inside the host-inventory image after it is built during the pr_check. This is a similar approach to how advisor …
=> Build psycopg2 from source

app/__init__.py
This PR is a hotfix for the Unleash code. It updates a config field to the correct name and switches to using `hasattr` to check whether the value is set.
=> Fix config field name

app/__init__.py
This PR is a quick hotfix to address the authorization issue we're running into with Unleash. It looks like I forgot to prepend "Bearer " to the Unleash token in the authorization header. The Slack conversation is [here](https://redhat-internal.slack.com/archives/C022YV4E0NA/p1675782353563019), for context.
=> Hotfix: Prepend "Bearer " to Unleash authorization

swagger/api.spec.yaml, swagger/openapi.json
This commit edits the OpenAPI schema for HBI: 1) use the same UUID pattern for host and group IDs, 2) fix incorrect reference to PerReporterStaleness.
This is a quick patch and it is not linked to any Jiras.
=> chore: Use the same pattern for host and group id

swagger/api.spec.yaml, swagger/openapi.json, tests/fixtures/api_fixtures.py
This PR is being created to address [ESSNTL-4376](https://issues.redhat.com/browse/ESSNTL-4376).
Based on our group discussions, we've had to make some changes to the endpoints we planned. For removing host-group associations, we're going with `DELETE /groups/{group-id}/hosts/{host-id1},{host-id2}`. Notes on this decision:
- The request body is not allowed for DELETE methods. Because of this, we need to specify the host IDs in the request path.
- In the future, groups may need to contain other objects besides hosts. Because of this, we need to specify `/hosts/` in-between the group and host IDs.
The original PR implementing this endpoint is #1277.
=> feat(ESSNTL-4376): Rename DELETE host-groups endpoint

app/config.py, lib/middleware.py
Part of https://issues.redhat.com/browse/RHINENG-80
It turns out that setting the ca cert path globally breaks cloud watch which makes an https call.  This change narrows the scope to just the call needed.
For the time being ephemeral/stage/prod  `LoadedConfig.tlsCAPath` will be `None`
In our IT-less environments it will be `/cdapp/certs/service-ca.crt`
=> Fix Cloudwatch when using clowder TLS

lib/host_delete.py, tests/test_api_hosts_delete.py
This PR is being created to address [ESSNTL-4518](https://issues.redhat.com/browse/ESSNTL-4518).
Currently, if you try to delete a host that's associated with a group, it will hit an exception and return HTTP 500.
This PR fixes that issue, and removes the host from the group before deleting it. It also adds a test to validate this, and a test that verifies that the entire thing rolls back if something goes wrong with the deletion.
=> fix(ESSNTL-4518) Remove host from its group before deletion

api/group.py, app/models.py, lib/group_repository.py, migrations/versions/0f2fb89499ce_make_group_name_constraint_case_.py, tests/test_api_groups_update.py
This PR is being created to address [ESSNTL-4519](https://issues.redhat.com/browse/ESSNTL-4519).
Implements these fixes:
- PATCHing a group without providing a name is now allowed
- Updating a group's name with the name of a different group now returns HTTP 400 with additional data in the message
- This also applies to case-insensitive naming; if a group named "test-group" already exists, renaming a different group to "Test-Group" is no longer allowed
- If the user attempts to add a host to their group but the host already exists in a different group, it returns 400 with a message explaining as much (including the offending Host ID)
=> fix(ESSNTL-4519): PATCH /groups/<group-id> fixes

app/models.py, app/serialization.py, migrations/versions/b48ad9e4c8c5_add_groups_jsonb_to_hosts_table.py, tests/test_unit.py
This PR is being created to address [ESSNTL-4615](https://issues.redhat.com/browse/ESSNTL-4615).
It adds the "groups" JSONB column to the hosts table, implementation for the models & schemas, and serialization/deserialization. This will be populated with the data of the host's associated group(s) in a follow-up PR.
=> feat(ESSNTL-4615): Add "groups" column to hosts table

swagger/api.spec.yaml, swagger/openapi.json, tests/test_api_hosts_update.py
This PR is being created to address [ESSNTL-4398](https://issues.redhat.com/browse/ESSNTL-4398).
Some of the schema descriptions for host update endpoints incorrectly used the singular "host" when a list of "hosts" is what is actually provided as a parameter.  In future, we may revisit this as the primary user (the UI) only ever uses a single host at a time, and if we update the code to no longer use a list, we will update the API schema version to v2, but for now, we are only updating the language used in the descriptions to accurately reflect the code and updating the unit test to check for updating multiple hosts instead of a single host.
=> [ESSNTL-4398] Update schema to reference list of hosts

app/logging.py
This PR is being created to address pods missing in stage after dependabot updating watchtower dependencies.
Alerts informed us pods were down. Logs show that the issue was an unexpected keyword argument "boto3_session". Changelog for watchtower indicate as of v2.0.0 `boto3_session` support has been removed and replaced with `boto3_client`.
This PR updates the cloudwatch handler to use the `boto3_client` and also updates `log_group` to `log_group_name` and `stream_name` to `log_stream_name`.
=> Update cloudwatch handler

api/host_query_xjoin.py, app/serialization.py
This PR is being created to fix a bug we just discovered. It makes it so we retrieve the "groups" field from the xjoin host query. This was added in a previous PR, but I think it got removed by a merge conflict.
=> Add groups field to xjoin-search hosts query

api/host_group.py, lib/group_repository.py, swagger/api.spec.yaml, swagger/openapi.json, tests/fixtures/api_fixtures.py, tests/test_api_host_group.py
This PR is being created to address ESSNTL-4375.
Adds the POST `/groups/{group_id}/hosts` endpoint. The post doc looks like the following:
```
[
"host_id_1",
"host_id_2",
"host_id_3"
]
```
If the list is empty, it fails validation and returns 400. If "host_ids" is provided, the list of hosts will be associate to the group.
=> feat(ESSNTL-4375) - Create POST /groups/<group-id>/hosts endpoint

api/host.py, api/host_query.py, app/queue/event_producer.py, app/queue/queue.py, app/serialization.py, lib/group_repository.py, lib/host_repository.py, lib/host_synchronize.py, tests/helpers/db_utils.py, tests/test_api_groups_update.py, tests/test_unit.py
This PR is being created to address [ESSNTL-4695](https://issues.redhat.com/browse/ESSNTL-4695).
This PR does the following:
- Removes host.groups[].host_count from produced MQ messages. We're doing this because if we want to keep that value in sync, we'd have to send a message for each host on the group every time a host is added or removed from the group (huge overhead)
- Simplifies serialization calls. You no longer need to specify the list of fields to send, since it was always either `DEFAULT_FIELDS` or `EGRESS_HOST_FIELDS`. Now you just optionally specify if you're not serializing it for MQ, or if there are any additional fields you'd like to include. 
- Removes the last references to the egress topic (we don't use that anymore)
- Removes an unused DB util function
You can find …
=> fix(ESSNTL-4695): Remove host_count from MQ serialization

api/group_query.py, tests/test_api_groups_get.py
This PR is being created to address the bug reported at [ESSNTL-4769](https://issues.redhat.com/browse/ESSNTL-4769) .
It adds another `.order_by` to the group's query.
With this, the data that is being returned is fixed and correctly ordered.
Data is preserved when using `per_page` and `page` query parameters.
Related: ESSNTL-4769
=> fix(ESSNTL-4769): Ordering groups by host_ids is random if groups have same amount of hosts

api/filtering/filtering.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-4766](https://issues.redhat.com/browse/ESSNTL-4766) and [ESSNTL-4767](https://issues.redhat.com/browse/ESSNTL-4767).
It changes the group-name filter to use "matches_lc" instead of "eq". This makes it so that the filter is case-insensitive, and also matches inclusively (instead of a strict equals). In other words, if you search for "ROUP", it will now find "Group1".
=> feat(ESSNTL-4766, ESSNTL-4767): Make group-name filter case-insensitive and inclusive

migrations/versions/8277117fa057_correct_empty_string_groups_value_on_.py
This PR is being created to address an issue where some hosts created in the early stages of Inventory Groups have host.groups set to `""`. If a host isn't associated with a group, its default value should be `[]`.
This just creates a new alembic migration to update the existing errant data.
=> Replace empty-string host.groups values with empty arrays instead

app/serialization.py, tests/test_unit.py
This PR is being created to address the issue we saw in Prod yesterday. If the service attempts to serialize a host for MQ when host.groups does not exist, it raises [an exception](https://kibana.apps.crcp01ue1.o9m8.p1.openshiftapps.com/app/kibana#/discover?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-06-08T17:01:01.175Z',to:'2023-06-08T18:50:36.349Z'))&_a=(columns:!(exc_text),filters:!(),index:'43c5fed0-d5ce-11ea-b58c-a7c95afd7a5d',interval:auto,query:(language:lucene,query:'@log_stream:%20%22host-inventory-mq%22%20AND%20levelname:%20ERROR%20AND%20msg:%20%22Unable%20to%20process%20message%22'),sort:!(!('@timestamp',desc)))); this PR fixes that, and adds some thorough testing to make sure it doesn't happen again. …
=> Fix host serialization when host.groups is undefined; add tests

app/queue/queue.py, rebuild_events_topic.py, tests/test_event_rebuilder.py
This PR is being created to reduce the memory usage of the events-topic-rebuilder part of the host synchronizer.
The rebuilder does not make any DB changes, so having a Session is unnecessary. In fact, having a session_guard around the entire process may have been eating up way more memory than it needed. I'm removing all of that in favor of simple SQLAlchemy ORM queries.
=> Remove DB session from events-topic-rebuilder

app/config.py, rebuild_events_topic.py
This PR is being created to address some performance issues with events-topic-rebuilder. It sets the maximum messages in the background consumer queue, tells the consumer to consume based on the batch size, and routinely flushes the producer to reduce its memory usage.
=> Improve events-topic-rebuilder memory usage

app/utils.py, tests/test_unit.py
This PR is being created to address [ESSNTL-3097](https://issues.redhat.com/browse/ESSNTL-3097).
This makes the `search` param on the `GET /hosts/<host_id>/tags` endpoint case-insensitive.
=> feat(ESSNTL-3097): Make tags search case-insensitive

deploy/clowdapp.yml
This PR is being created to address [ESSNTL-4991](https://issues.redhat.com/browse/ESSNTL-4991).
The original issue this is addressing is located [here](https://github.com/RedHatInsights/ansible-collections-insights/issues/48). Sometimes a request comes in that has a lot of filters, and gunicorn blocks it because the line is too long. In order to mitigate this in the medium-term, I'm increasing that limit to its max value (without setting it to unlimited, which could be a security risk without additional measures).
=> fix(ESSNTL-4991): Increase gunicorn's limit-request-line from 4094 to 8190

api/filtering/filtering.py, tests/test_api_hosts_get.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-4458](https://issues.redhat.com/browse/ESSNTL-4458).
Elastic Search doesn't allow date before 1970, returned message from ES:
```
date[0199-03-04T04:56:02Z] is before the epoch in 1970 and cannot be stored in nanosecond resolution
```
so,  If the date args is before 1970, remove from filters query.
=> fix(ESSNTL-4458): Fix too old date on filter

api/group.py, api/host.py, api/sparse_host_list_system_profile.py, lib/middleware.py, tests/test_api_groups_create.py, tests/test_api_hosts_update.py, tests/test_rbac.py, tests/test_xjoin.py
This PR is being created to address [ESSNTL-5049](https://issues.redhat.com/browse/ESSNTL-5049), and follows up on #1371. Fixes a number of bugs with the current resource-level RBAC implementation, including:
- Users are no longer allowed to create a group if their groups:write access is limited to specific groups
- Granular RBAC now works on GET /hosts/<host_id>/system_profile
- Added a more specific "not found" message when PATCHing a group that the user doesn't have access to
- Errors with informative hints whenever the RBAC config does not conform to requirements
It also adds tests for each of these scenarios.
=> fix(ESSNTL-5049): Fix various resource-level RBAC issues

lib/host_synchronize.py, tests/test_synchronizer.py
This PR is being created to address the hosts that have `groups=NULL` instead of `groups=[]`, leftover from the original design change. With this update, the next host-synchronizer run should fix the values, allowing us to next mark that column as NOT NULL.
=> Update host-sync to fix null host.groups values

api/group.py, lib/host_repository.py, lib/middleware.py, tests/test_api_hosts_update.py, tests/test_rbac.py
This PR is being created to address the new bugs found in the comments of [ESSNTL-5049](https://issues.redhat.com/browse/ESSNTL-5049):
- Creating groups with inventory:groups:write permission with attributeFilter now returns HTTP 403 with a more descriptive message.
- Fixed the DB-specific RBAC group ID filter so that it works when the attributeFilter contains a null (None).
- Putting a value that's neither a UUID nor None now results in error 503, because that implies the RBAC service has populated the permissions with invalid values. 
=> fix(ESSNTL-5049): Resolve more granular RBAC issues

api/filtering/filtering.py, swagger/api.spec.yaml, swagger/openapi.json, tests/test_xjoin.py
This PR is being created to address an oversight we noticed in [this comment thread of the onboarding doc](https://docs.google.com/document/d/1O87MHvKlPEoH_DHwZw4htvwYlkGMiS-LwLQ_qKsZ5J0/edit?disco=AAAA0srgq8A). Right now, we only allow filtering on one `group_name`, but we need to allow multiple values for it to work correctly. The UI is already set up to send multiple values for this field, so there shouldn't be any compatibility risk if this is executed correctly.
Basically, if we do `GET /hosts?group_name=group1&group_name=group2`, then it should return hosts that are in either group1 or group2.
=> Allow multiple values for group_name filter param

api/group.py, lib/middleware.py
This PR is being created to address the last couple of issues in the comments of [ESSNTL-5049](https://issues.redhat.com/browse/ESSNTL-5049).
It puts a `.` in one of the error strings, and switches out a `Response()` in favor of `abort()` for one of the RBAC errors.
=> fix(ESSNTL-5049): Minor RBAC follow-ups

api/filtering/filtering.py, tests/test_xjoin.py
This PR is being created to allow filtering on ungrouped hosts.
By sending a blank value for the `group_name` param, you can filter on ungrouped hosts. For instance:
- `GET /hosts?group_name=` will return only ungrouped hosts
- `GET /hosts?group_name=testgroup&group_name=` will return hosts that are either ungrouped or in "testgroup"
=> Allow filtering on ungrouped hosts

api/resource_type.py, lib/middleware.py, swagger/api.spec.yaml, swagger/openapi.json, tests/helpers/api_utils.py, tests/helpers/rbac-mock-data/rbac-admin.json, tests/test_api_resource_types_get.py
This PR is being created to address [RHINENG-1436](https://issues.redhat.com/browse/RHINENG-1436).
Adds the `name` filter to the `GET /resource-types/inventory-groups` endpoint. This supports the RBAC UI so that RBAC admins can more easily find groups to grant access to.
I also added an RBAC test to make sure RBAC admins could access the appropriate endpoints. That's more related to [RHINENG-1427](https://issues.redhat.com/browse/RHINENG-1427), but we should have the test, and I haven't yet been able to reproduce the issue described in that Jira.
Edit: I also included a fix to address [RHINENG-1427](https://issues.redhat.com/browse/RHINENG-1427), which is passing the app name through to the rbac request. It's only used when the user needs RBAC admin permission
You can find documentation …
=> feat(RHINENG-1436, RHINENG-1427): Add group name filter to /resource-types/inventory-groups endpoint

lib/middleware.py, tests/test_rbac.py
This PR is being created to address [RHINENG-1492](https://issues.redhat.com/browse/RHINENG-1492).
This PR removes the RBAC is_admin workaround set up in RHINENG-1427.
=> fix(RHINENG-1492): Remove RBAC admin workaround

swagger/api.spec.yaml, swagger/openapi.json
The OpenAPI codegen is generating some weird stuff with the current implementation of AssignmentRuleOut. I'm not sure why, but anyway, the `allOf` field is not needed if we don't import fields from other objects and removing it fixes the issue.
=> Fix AssignmentRuleOut in API spec

swagger/api.spec.yaml, swagger/openapi.json
This PR is being created to address [ESSNTL-5937](https://issues.redhat.com/browse/ESSNTL-5937).
Adding back BearerAuth on staleness endpoint
=> fix(ESSNTL-5937): Adding back basic auth on staleness endpoint

deploy/clowdapp.yml
Reverts RedHatInsights/insights-host-inventory#1467
We started seeing some Floorist-related issues at around the time this PR went in, so we're going to see if reverting this somehow fixes the problem.
=> Revert "Add rhc_client_id to floorist query"

api/host.py, app/queue/events.py, app/queue/queue.py, lib/group_repository.py, lib/host_delete.py, lib/host_remove_duplicates.py, lib/host_synchronize.py, tests/helpers/mq_utils.py, tests/test_mq_service.py, tests/test_unit.py
This PR is being created to address [RHINENG-1789](https://issues.redhat.com/browse/RHINENG-1789).
We need some additional headers for the emitted kafka messages upon database changes for a more fine-grained filtering in cyndi. Vulnerability and patch require the `reporter` field to be exposed as a header, other apps need additinally the OS name and whether the host is an edge host or not.
=> feat(events): RHINENG-1789 push additional headers with kafka events

app/config.py, deploy/clowdapp.yml, rebuild_events_topic.py
This PR is being created to address [RHINGENG-1751](https://issues.redhat.com/browse/RHINGENG-1751).  It enables the `rebuild_events_topic` script to stop after some specified time.
=> RHINGENG-1751: Enable rebuild_events_topic script to stop after speicified time

api/account_staleness_query.py, app/serialization.py
Return N/A for created and updated field of sys default response
This PR is being created to address [ESSNTL-5038](https://issues.redhat.com/browse/ESSNTL-5038).
=> fix(ESSNTL-5038): Return N/A for created and updated

api/account_staleness.py, api/account_staleness_query.py, swagger/api.spec.yaml, swagger/openapi.json, tests/helpers/api_utils.py, tests/test_api_account_staleness_get.py, tests/test_api_account_staleness_update.py
This PR is being created to address [ESSNTL-5424](https://issues.redhat.com/browse/ESSNTL-5424).
This PR adds a simple API resource that returns the system defaults staleness values.
=> [ESSNTL-5424] Create GET /api/inventory/v1/account/staleness/defaults endpoint

tests/fixtures/app_fixtures.py, tests/test_api_staleness_get.py
@jpramos123, this PR fixes the `clean_g()` fixture, which is used by only one test.  Without this fix the tests in `tests/test_unit.py` fail.  This bug was discovered while reviewing the [segmentio PR ](https://github.com/RedHatInsights/insights-host-inventory/pull/1472)
=> Fix fixture to let test_unit.py be tested by itself

api/__init__.py, api/group.py, lib/group_repository.py, swagger/api.spec.yaml, swagger/openapi.json, tests/fixtures/api_fixtures.py, tests/test_api_groups_delete.py
This PR is being created to address [RHINENG-1653](https://issues.redhat.com/browse/RHINENG-1653).
It implements the DELETE `/groups/hosts/{host_id_list}` endpoint. The api spec was updated and tests were added for the new functionality.
I also did extracted the code for checking feature flags on the groups file to its own function since it is used multiple times in the code.
=> RHINENG-1653: Create DELETE /groups/hosts endpoint

api/filtering/filtering.py, tests/test_api_hosts_get.py
This PR is being created to address [ESSNTL-5465](https://issues.redhat.com/browse/ESSNTL-5465). It fixes a bug that occurs when the feature flag to hide Edge hosts is turned on, and the user makes a request with an invalid filter key. For instance, if the user filters using `?filter[bad_key]`, it would error and return 500 instead of 400.
=> fix(ESSNTL-5465): Fix filter key check when hide-edge-hosts flag is enabled

.github/dependabot.yml
This patch decreases the maximum number of open pull requests for version updates from 10 to 3.
Note that the scheduling was already on a weekly basis.
=> ci(dependabot): Limit open pull requests

api/segmentio.py, tests/test_segmentio.py
API requests with no User-Agent header fail with a response code of 500.
This change ensures we don't try to reference a header that doesn't exist (the cause of the error).
And it doesn't attempt to track such requests, as we filter on User-Agent.
=> Fixed bug caused when User-Agent header is missing.

api/group.py, app/instrumentation.py, lib/group_repository.py, lib/middleware.py
This PR is being created to address [RHINENG-2320](https://issues.redhat.com/browse/RHINENG-2320).
This PR adds logs to abort functions in `groups.py` and also to `rbac_group_id_check` in `middleware.py` which is used vastly in groups.
=> perf(RHINENG-2320): Use logger for logging Groups' API actions

api/staleness.py, tests/test_api_staleness_update.py
This PR is being created to address [ESSNTL-5406](https://issues.redhat.com/browse/ESSNTL-5406).
When api receives a wrong data in `patch` or `post` we need to return `400` and the validation error instead `500`
=> fix(ESSNTL-5406): Fix wrong 500 http response

app/queue/queue.py
This PR is being created to address an issue the headers used by Cyndi apps. The "host_type" and "os_name" message headers were being populated from the incoming host data rather than the updated host data, so they would often be blank (as not every reporter provides these values). I've updated it so the values come from `output_host`, which has the full host data, so these fields will always be populated when they exist on the host record in the DB.
=> Fix: Use output_host data for SP message headers

api/group.py
This PR is being created to address [RHINENG-2470](https://issues.redhat.com/browse/RHINENG-2470).
It changes the error message for the DELETE /groups/hosts/<host_ids> endpoint.
=> fix(RHINENG-2470): change error message for DELETE endpoint

app/config.py, tests/test_api_staleness_get.py
This PR is being created to address [ESSNTL-5555](https://issues.redhat.com/browse/ESSNTL-5555).
We recently changed the conventional_staleness_delta default from 86400 to 104400, this commit fix that.
=> fix(ESSNTL-5555): Fixing right return on default api

app/models.py, tests/test_api_groups_create.py
This PR is being created to address [ESSNTL-3085](https://issues.redhat.com/browse/RHINENG-3085).
It strips whitespace from the beginning and end of the group name input, so that you can't have 3 separate groups named (for instance) "testGroup", " testGroup", and "testGroup ". I baked this into the pre-load of the input validator so that it happens automatically, as long as the data is loaded into the schema (InputGroupSchema).
=> fix(ESSNTL-3085): Strip whitespace from group name input

deploy/testing-integration.yml
* add `volume` and `volumeMount` needed for storing insights-qa ssh key
We need the SSH key for running our integration tests on Ibutsu. Currently, it is not possible
to connect to the provisioned machines due to missing SSH key.
This PR is connected to this one: https://gitlab.cee.redhat.com/service/app-interface/-/merge_requests/86391
=> Add ssh key volume to the testing-integration.yml

migrations/versions/cc3494db47ea_add_indexes_for_reporter_host_type_os_.py
This PR is being created to address [RHINENG-3099](https://issues.redhat.com/browse/RHINENG-3099).
It adds indexes for `reporter` and `system_profile_facts.host_type`, which will speed up queries that use these fields.
=> chore(RHINENG-3099): Add indexes for reporter and host_type

docs/pull_request_template.md
This PR is being created simply to update the Jira link template in our PR template. It changes the project in the link from ESSNTL to RHINENG, since we're supposed to be using that project for all new tickets.
=> Change Jira link template to reflect new project

migrations/versions/3ecc428e69cb_add_coalesce_to_operating_system_gin.py
This PR is being created to address [RHINENG-3099](https://issues.redhat.com/browse/RHINENG-3099).
Adds a COALESCE statement to the `operating_system` GIN; I overlooked it in #1541.
I left the migration's downgrade function empty because IMO there's no point reverting to an incorrect index; if the intent is the remove the index, it can just be downgraded to the one before that.
=> fix(RHINENG-3099) Add COALESCE to operating_system GIN

api/filtering/filtering.py, app/xjoin.py, tests/helpers/graphql_utils.py, tests/test_tags.py, tests/test_xjoin.py
This PR is being created to fix [RHINENG-3425](https://issues.redhat.com/browse/RHINENG-3425), an issue introduced by #1516. It changes some of the dicts back to tuples, and simplifies some of the xjoin logic (so it's not wrapping multiple `OR`s in more `OR`s, for instance).
I wanted to figure out how to further simplify `staleness_conditions` in `staleness_filter`, but I wasn't able to figure out how to correctly do this kind of tuple comprehension in a reasonable amount of time. If you have any suggestions, please let me know.
=> fix(RHINENG-3425) Fix dict & tuple mismatches

lib/host_synchronize.py
This PR is being created to address [RHINENG-4856](https://issues.redhat.com/browse/RHINENG-4856).
This is a workaround for us to be able to run host-synchronizer successfully in prod.
Details in Jira ticket
=> hot-fix(RHINENG-4856): Skip specific host on being synchronized

api/filtering/filtering.py, app/models.py, tests/test_models.py, tests/test_xjoin.py
This PR is being created to address [RHINENG-2631](https://issues.redhat.com/browse/RHINENG-2631).
In addition to "yupana", HBI must start supporting "satellite" and "discovery" for the reporter field. In order to transition smoothly to the new values, a few extra steps are needed.
When filtering on "registered_with=yupana", also include hosts that have been updated recently with the "satellite" or "discovery" reporter.
When updating per_reporter_staleness (PRS), if the reporter is "satellite" or "discovery", remove the "yupana" entry afterwards.
=> feat(RHINENG-2631): Support new reporter values for yupana

app/culling.py, swagger/api.spec.yaml, swagger/openapi.json, tests/test_xjoin.py
This PR is being created to address [RHINENG-5892](https://issues.redhat.com/browse/RHINENG-5892).
#1569 removed the "unknown" staleness filter value; we made sure UIs weren't explicitly sending this value, but it turns out that the ansible-collections-insights Inventory plugin was still sending it, so it broke. I opened [CCT-196](https://issues.redhat.com/browse/CCT-196) requesting that they stop sending that value (and explicit values for that filter in general), and we'll remove the value ([RHINENG-5893](https://issues.redhat.com/browse/RHINENG-5893)) after that goes in.
=> feat(RHINENG-5892) Re-allow "unknown" value for staleness filter

README.md
This PR is being created to address [RHINENG-5460](https://issues.redhat.com/browse/RHINENG-5460).
It adds a note to our Contributing section instructing users to install rh-pre-commit before contributing. I specified that this only applies if you're on the RH network, because rh-pre-commit only works when you're on the VPN.
=> feat(RHINENG-5460): Add rh-pre-commit installation instructions to README

lib/host_kafka.py, tests/test_unit.py
This PR is being created to address [RHINENG-6099](https://issues.redhat.com/browse/RHINENG-6099).  Previously a string was expected for a single broker.  Now a list is expected as multiple brokers are used now.
=> RHINENG-6099: use list when checking for kafka brokers

lib/feature_flags.py, lib/middleware.py, tests/test_rbac.py
This PR is being created to address [RHINENG-6136](https://issues.redhat.com/browse/RHINENG-6136).
In order to complete the Edge Parity migration, the Edge team will need to bypass rbac to create inventory groups (to replace their corresponding edge groups). This PR makes it so that requests bypass RBAC if all 3 conditions are met:
- identity.identity_type is "User"
- identity.user.is_org_admin is True
- The "edgeParity.groups-migration" feature flag  is True
We will remove this code after the migration is complete ([RHINENG-5446](https://issues.redhat.com/browse/RHINENG-5446)).
=> feat(RHINENG-6136) Bypass RBAC for org-admin users during Edge Parity migration

api/staleness.py, tests/helpers/api_utils.py, tests/helpers/rbac-mock-data/inv-staleness-read-only.json, tests/test_api_staleness_get.py
This PR is being created to address [RHINENG-4565](https://issues.redhat.com/browse/RHINENG-4565).
- Make sure we test RBAC permissions to GET staleness endpoint
- Refactor staleness GET endpoint
=> fix(RHINENG-4565): Refactor staleness GET endpoint and add permission tests

api/filtering/filtering.py, api/group_query.py, api/host.py, api/host_query.py, api/resource_type.py, api/staleness_query.py, app/__init__.py, app/common.py, app/queue/queue.py, app/serialization.py, host_dumper.py, lib/group_repository.py, lib/middleware.py, tests/fixtures/db_fixtures.py, tests/test_api_host_group.py
This PR is being created to address [RHINENG-6037](https://issues.redhat.com/browse/RHINENG-6037).
It fixes the group `host_count` to reflect culled hosts correctly.
=> [RHINENG-6037] - Inventory group's host count reflects host that is culled

api/staleness.py, api/staleness_query.py
This PR is being created to address [RHINENG-6185](https://issues.redhat.com/browse/RHINENG-6185).
GET `default` endpoint now returns current org_id
=> fix(RHINENG-6185) Return current org_id

app/serialization.py, tests/fixtures/mq_fixtures.py, tests/test_xjoin.py
It fixes the wrong stale_timestamp in the per_reporter_staleness
=> [RHINENG-6095] - Use custom staleness in per_reporter_staleness

api/filtering/filtering.py, tests/helpers/graphql_utils.py, tests/test_xjoin.py
This PR is being created to address [RHINENG-4810](https://issues.redhat.com/browse/RHINENG-4810).
It changes the logic to always use OR when filtering for multiple values in the same system_profile field.
=> fix(RHINENG-4810): filtering logic for multiple  values for the same SP field

app/auth/identity.py, tests/fixtures/api_fixtures.py, tests/helpers/api_utils.py, tests/test_rbac.py
This PR is being created to address concerns that were [raised on Slack](https://redhat-internal.slack.com/archives/CQFKM031T/p1704444852691029). Although the `is_org_admin` field in the x-rh-identity header is a boolean value, it's safer for us to validate the types for these fields, so this PR enforces that. It also adds a test to make sure that various falsy/invalid values for `is_org_admin` are not interpreted as truthy in our rbac bypass.
Follows up on #1580.
=> Enforce validation of User Identity field types

iqe_tests.sh, pr_check.sh
This PR is being created to address [RHINENG-4100](https://issues.redhat.com/browse/RHINENG-4100).
I found out that the restarts are caused by SIGKILL signals, which are being sent because host-inventory-service is running out of memory. Bonfire is not giving us the resources mentioned in app-sre deployment file. Instead, it only gives us half of that. With the changes in this PR, bonfire should respect the config and give us enough resources.
I wrote a detailed description of what is the root cause of this problem in [this comment of RHINENG-4100](https://issues.redhat.com/browse/RHINENG-4100?focusedId=23718000&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23718000). …
=> RHINENG-4100: Fix Host Inventory Service random restarts

app/auth/identity.py, tests/helpers/test_utils.py, tests/test_identity_schema.py
This PR is being created to address [RHINENG-5479](https://issues.redhat.com/browse/RHINENG-5479).
The [previous PR](https://github.com/RedHatInsights/insights-host-inventory/pull/1588) introduced an error regarding the validation for the fields in the Service Account Identity Schema, this PR fixes it.
=> fix(RHINENG-5479): Update fields for Service Account Identity

deploy/clowdapp.yml
Separates CPU/mem requests & limits into separate parameters for each app component -- allowing us to tune them for better resource utilization in ephemeral environments.
=> Define separate resource params, remove unused floorist params

api/host.py, tests/test_tags.py
This PR is being created to address [RHINENG-7073](https://issues.redhat.com/browse/RHINENG-7073).
Convert GET /hosts/{host_id_list}/tags endpoint from XJoin to DB
* Use feature flag to determine postgres or xjoin flow
* Add test cases for postgres flow of querying tags
=> [RHIENG-7073] Convert GET /hosts/{host_id_list}/tags endpoint from XJoin to DB

deploy/testing-integration.yml
Running the integration tests hits the limit of
memory usage that causes tests to fail. We need to increase the requested memory.
=> Increase sel-container memory request

deploy/testing-integration.yml
We are having issues with proper displaying of elements in the browser. Add the `VNC_GEOMETRY` to set the default size of the browser window.
=> Add VNC geometry to testing-integration.yml

api/host.py, api/host_query_db.py, app/models.py, tests/helpers/api_utils.py, tests/test_api_hosts_get.py
This PR is being created to address the first part of [RHINENG-7070](https://issues.redhat.com/browse/RHINENG-7070).
It implements most of the DB implementation for the GET /hosts endpoint. The 3 remaining filters are more complex, and this PR was already getting large, so I'm going to do those in a follow-up PR. 
For this PR, the DB version of the endpoint should function the same way as the XJoin version, minus the use of these params:
- `staleness`
- `registered_with`
- `filter` (i.e. System Profile filter)
- `fields` (i.e. sparse System Profile fields)
=> feat(RHINENG-7070) GET /hosts DB implementation (Part 1)

swagger/api.spec.yaml, swagger/openapi.json, tests/test_xjoin.py
This PR reverts an bug that was introduced on #1603 
It reintroduce `stalenessNoDefaultsParam`  to `DELETE /hosts`
=> fix(RHINENG-6095): Fix DELETE /hosts endpoint 

app/serialization.py, swagger/api.spec.yaml, swagger/openapi.json, tests/test_xjoin.py
This PR is being created to address [RHINENG-6096](https://issues.redhat.com/browse/RHINENG-6096).
It adds `stale_warning_timestamp` and `culled_timestamp` to `per_reporter_staleness` using custom staleness
=> [RHINENG-6096] - Return all dynamically calculated staleness timestamps in per_reporter_staleness

host_reaper.py
After #1569 was merged, the create_app() function is now being run whenever reaper launches. create_app() configures the logger itself, so the host_reaper.py logging configuration call is redundant. It also causes the reaper to hang in certain environments.
This commit removes the redundant call to configure_logging()
=> fix: Remove configure_logging() from host_reaper.py

.unleash/flags.json, api/filtering/db_filters.py, api/host_query_db.py
This PR is being created to move the DB filtering functions to their own file (`db_filters.py`). It also enables the "hbi.group-assignment-rules" and "hbi.custom-staleness" feature flags in the local unleash config.
=> Move DB filters to their own file; enable 2 feature flags in local cfg

api/host.py, api/host_query_db.py, api/system_profile.py, tests/helpers/api_utils.py, tests/test_system_profile.py
This PR is being created to address [RHINENG-7075](https://issues.redhat.com/browse/RHINENG-7075).
* Add feature flag call in system profile API to call DB method
* Add DB method to aggregate on operating systems
* Enable get_host_list_by_id_list_from_db to only filter on the host list if provided
* Add test case to check aggregation function
* Add api util helper since no test case existed for this endpoint before
* Clean up limit and offset to reuse pagination_params method
* Clean up host query db usage to pass limit offset
=> Convert GET /system_profile/operating_system endpoint from XJoin to DB (Part 1)

app/instrumentation.py, app/queue/event_producer.py, tests/test_api_hosts_delete.py
Related: RHINENG-5451
This PR is being created to address [RHINENG-5451](https://issues.redhat.com/browse/RHINENG-5451).
Logs large messages to kibana if the message can not be produced.
=> perf(RHINENG-5451): log large messages to kibana

api/filtering/filtering.py, app/xjoin.py, tests/test_xjoin.py
It fixes a issue found when filtering hosts with `registered_with=`, before the it was not able to identify the correct staleness for each of the reporters. Now it is able to filter the hosts by the reporter_staleness correctly.
=> [RHINENG-6095] - fix staleness filter

app/queue/event_producer.py, app/queue/metrics.py, app/queue/queue.py
This PR is being created to address [RHINENG-5449](https://issues.redhat.com/browse/RHINENG-5449).
This PR adds the following metrics to HBI: `consumed_message_size`, `produced_message_size` and `produce_large_message_failure`.
Since I'll be away, please feel free to merge commits with fixes if needed, so this PR can be merged as soon as possible.
=> feat(RHINENG-5449): add new prometheus metrics

Makefile, Pipfile, Pipfile.lock, README.md, api/__init__.py, api/assignment_rule.py, api/group.py, api/host.py, api/host_group.py, api/staleness.py, app/__init__.py, app/models.py, deploy/clowdapp.yml, host_dumper.py, host_reaper.py, host_synchronizer.py, inv_mq_service.py, lib/middleware.py, manage.py, rebuild_events_topic.py, run.py, tests/fixtures/app_fixtures.py, tests/test_unit.py, unit_test.sh, utils/validate_hosts_for_delete.py
This PR is being created to address [RHINENG-8106](https://issues.redhat.com/browse/RHINENG-8106).
* Update of Flask to 2.2.5
* Update of Connexion to 2.14.2 for Flask 2.x support
* Removed flask-api and replaced status with HttpStatus values
* Removed flask-script
* Now creating and returning a FlaskApp from the create_app function
* Update of manage.py to remove flask-script usage
* Update all calls to create_app to dereference the app value returned from the FlaskApp
=> Update Flask to version 2.2.5 and associated dependecies

api/filtering/filtering.py, app/xjoin.py, tests/test_xjoin.py
It fixes the issue with the `registered_with=!reporter` and also the issue @msager27 found when retrieving a host with two reporters. Before if the custom staleness was just set for the `conventional` hosts, the graphql was ignoring the host_type and returning all systems independently.
=> [RHINENG-6095] Fix per reporter staleness filters

.pre-commit-config.yaml, api/spec.py, app/__init__.py, swagger/openapi.dev.json
This PR is being created to address [RHINENG-8613](https://issues.redhat.com/browse/RHINENG-8613).
* Duplicate existing openapi spec for development use with connexion
* Update cutomer facing openapi spec to remove assignment-rules endpoints
* Add new blueprint for serving customer facing spec
* Alter connexion to load from the development spec
* Update pre-commit check to update the development spec now
* In order to make API visible you will need to update the customer facing spec
=> Enable development openapi spec and customer facing spec

swagger/api.spec.yaml, swagger/openapi.dev.json
This PR is being created to address [RHINENG-7661](https://issues.redhat.com/browse/RHINENG-7661).
Mentioning "feature flag" in api call did not look right, so I did not included it.  If we think that it should be included, then the description in swagger/api doc should be:
`Read the entire list of all hosts available to the account, except "edge" hosts, which are hidden by default.  To get "edge" hosts, either use "?filter[system_profile][host_type][eq]=edge" or set the feature flag, "hbi.api.hide-edge-by-default", to "false"`
=> RHINENG-7661: Document "edge" hosts hidden by default

api/filtering/filtering.py, api/system_profile.py, api/tag.py, tests/fixtures/graphql_fixtures.py, tests/test_xjoin.py
It fixes a reported issue that was found in production where the hosts were being marked as stale and it was not able to query hosts using `registered_with` and `staleness` filters together.
Also, it standardize the Tags and System profile graphQL query filters to match the same structure of Hosts query.
=> [RHINENG-6095] - Fix registered_with and staleness filters

app/models.py
This PR is being created to address [RHINENG-8730](https://issues.redhat.com/browse/RHINENG-8730).
Change the max value of `time_to_delete` to 2 years. It fixes an issue where xjoin-search was not accepting values larger than 54 years.
=> fix(RHINENG-8730): Change max values of time_to_delete to 2 years

api/spec.py, app/__init__.py
* Altered the dev spec path of the connexion openapi spec to avoid conflicts
* Corrected file loading
=> feat(RHINENG-8613): Fix blueprint serving customer facing openapi spec

deploy/testing-integration.yml
Update the selenium standalone image to the latest image in quay.io/redhatqe/.
I also att a new value `IQE_PARALLEL_ENABLED` to false. The default value was true but we are not using parallel testing right now.
=> Update selenium image and disable parallel testing in integration testing

lib/feature_flags.py, lib/middleware.py, tests/test_rbac.py
This PR is being created to address [RHINENG-5842](https://issues.redhat.com/browse/RHINENG-5842).
Removes the RBAC bypass that was introduced in #1580, along with the feature flag it was using. It was originally introduced to facilitate the migration to Inventory Groups for the Edge Parity project. 
=> chore(RHINENG-5842): Remove Edge-Parity RBAC bypass

api/host_group.py
This PR is being created to address [RHINENG-8436](https://issues.redhat.com/browse/RHINENG-8436).
When getting a 400 error message on /groups/{group_id}/hosts, the text mentions 'Body content must be an array with **groups** UUIDs' when the expected list should be the an array with **system** UUIDs'.
=> Fixed typo in error message in add_host_list_to_group().

host_reaper.py
This PR is being created to address a Reaper issue. The job runs for a long time, and then when it hits an error, it rolls back _all_ of its changes. With these changes, it will instead only roll back up to a max defined by `host_delete_chunk_size` (default 1000).
=> Move Reaper's session_guard for smaller rollbacks

deploy/clowdapp.yml
This PR is being created to address [RHINENG-9031](https://issues.redhat.com/browse/RHINENG-9031
Paths to some python scripts were not updated to work with dumb-init.  Now they have been.
=> RHINENG-9031: Fix paths to python scripts

migrations/versions/7c97d8464b6b_add_indexes_for_display_name_and_system_.py
This PR is being created to address an issue with the latest DB upgrade. This change should make all the index creation and deletion concurrent, so nothing should be locking the DB.
=> Make all index create/drop calls concurrent

api/host_query_db.py, tests/test_tags.py
* All of the search and filtering converts tag items to text creating "null" strings
* Naively convert "null" strings back to null values
* Assume edge case of intended "null" string is not necessary and could be documented
=> bug(rhineng-9037): Naively handle null string conversion in tags

api/filtering/db_custom_filters.py, tests/test_api_hosts_get.py
* escape values with percents and colons to avoid unintended SQL interaction.
=> bug(rhineng-9037): Handle embedded percents and colons values

api/filtering/db_custom_filters.py, tests/test_api_hosts_get.py
* Update escape character set
* Add test case for these query parameters
=> bug(rhineng-9037): Fix 500s when values have SQL chars that need escaping

pg_repack.dockerfile
This PR is being created so that the pg_repack job uses pg_repack v 1.4.6 specifically. This is required because the job will not run unless the version installed on the DB exactly matches the version installed on the client.
=> fix(RHINENG-6139) Use pg_repack 1.4.6 specifically

run_pg_repack.py
This PR is being created to address an issue that's visible in the [latest pg_repack job run](https://console-openshift-console.apps.crcs02ue1.urby.p1.openshiftapps.com/k8s/ns/host-inventory-stage/pods/host-inventory-pg-repack-28553429-p6kct/logs). [The docs](https://reorg.github.io/pg_repack/#installation) say to use multiple `-t` switches to make it run on multiple tables, so that's what this PR does.
=> Fix: Specify the tables on which to run pg_repack

api/host_query_db.py, tests/test_tags.py
It fixes a bug which was preventing tags with null values to be returned by API endpoints. It also refactors the relevant code a bit, and adds a unit test.
=> fix(RHINENG-9037) Return tags with null values & refactor

deploy/clowdapp.yml
This PR is being created to rename `minReplicas` to `replicas` in our deployment config. Currently, reducing minReplicas has no effect; this appears to be because the actual field we need to modify is `replicas`.
=> Change minReplicas to replicas

deploy/testing-integration.yml
I updated a few variables in this PR https://github.com/RedHatInsights/insights-host-inventory/pull/1719 and it seems our pipelines don't accept integers so I'm updating the value to a string.
=> Change deploy integration template value from int to str

api/host.py
* Allow queries that are filtering on bootc to use disable xjoin path for /hosts endpoint
* Allow queries that are filtering on bootc to use disable xjoin path for /hosts/{id}/system_profile endpoint
=> feat(bootc): Use disable xjoin flow when bootc queries are made

api/filtering/db_custom_filters.py, tests/test_api_hosts_get.py
This PR is being created to address [RHINENG-9699](https://issues.redhat.com/browse/RHINENG-9699).
* ignore_nodes flow was errantly adding entire system profile filter instead of only the isolated operating_system component causing bad processing
=> bugfix(rhineng-9699): Resolve 500 when os query is combined with other system profile query

api/host.py, api/tag.py
This PR is being created to address [RHINENG-9706](https://issues.redhat.com/browse/RHINENG-9706).
* when a bootc system_profile filter is applied using the tags endpoint use the disable.xjoin flow
=> bugfix(rhineng-9706): Use disable.xjoin flow for bootc on tags endpoint

api/host.py, api/system_profile.py
This PR is being created to address [RHINENG-9706](https://issues.redhat.com/browse/RHINENG-9706).
Enable bootc to use disable xjoin flow for:
* DELETE /hosts
* GET /system_profile/sap_sids
* GET /system_profile/sap_system
* GET /system_profile/operating_system
=> bug(rhineng-9706): Enable bootc workaround for addl endpoints

app/auth/identity.py
This PR is being created to address [RHINENG-9619](https://issues.redhat.com/browse/RHINENG-9619).
Hello! Random drive by commit by your friendly neighborhood pipeline QE. We are currently blocked by this on RHCLOUD-30362, and from what we can tell what's missing are the SAML/X509[1] Auth types and the X509/Associate[2] Identity types.
1 - [Here](https://github.com/RedHatInsights/turnpike/blob/master/turnpike/plugins/x509.py#L14) and [Here](https://github.com/RedHatInsights/turnpike/blob/master/turnpike/plugins/saml.py#L139)
2 - [Here](https://github.com/RedHatInsights/turnpike/blob/master/turnpike/plugins/x509.py#L15) and [Here](https://github.com/RedHatInsights/turnpike/blob/master/turnpike/plugins/saml.py#L140)
You can see more context in the slack thread title `Question about Turnpike …
=> [RHINENG-9619] Add missing turnpike auth/identity types

migrations/versions/90879eb18c66_remove_unused_indexes.py
This PR is being created to address [RHINENG-9788](https://issues.redhat.com/browse/RHINENG-9788). Removes 4 unused indexes (hosts_subscription_manager_id_index, idx_reporter, idxdisplay_name, idxsap_sids).
There were 2 more considered for deletion that I'm not removing yet:
- idxinsightsid: Unused in Stage, but is used in Prod.
- idx_operating_system: This isn't used in either env, but we still need an index for this. I'll work with David Halasz to figure out why it's not used and determine whether we can update a WHERE or if we have to replace the index.
=> perf(RHINENG-9788): Remove unused indexes

api/host_query_db.py
Removes a duplicate filter, which nearly doubles the length of the operating_system query.
=> perf(RHINENG-9788): Remove double-filter on OS query

migrations/versions/3d4efbc9da4f_remove_os_index.py, run_pg_repack.py
This PR is being created to remove the OS index, because our stats in both Stage and Prod show that it has never been used. It also sets the replica identity to "FULL" for the groups and hosts_groups tables, which is required for pg_repack to work correctly.
=> chore: Remove OS index, set replica identity for tables

api/filtering/db_filters.py, api/host_query_db.py
It changes our queries so that they join on HostGroupAssoc and Group only when required by the query. Joining on HostGroupAssoc is required when filtering on group ID or applying an RBAC filter; joining on Group is only required when filtering on, or ordering by, group ID.
=> perf(RHINENG-9788) Only perform the joins that are required by the query

api/filtering/db_custom_filters.py, api/filtering/db_filters.py
The `staleness` and `per_reporter_staleness` generate a group of WHERE clauses for each host type (one for "edge", one for None) even if the user is filtering hosts by a specific host type. This PR makes it so that if you're filtering on host_type, it only adds the staleness filters specific to that host_type.
Additionally, when filtering on only one host_type, it gets rid of the redundant `host_type` filters added in the `staleness` and `per_reporter_staleness` filters.
=> perf(RHINENG-9788) Remove duplicate host-type WHERE clauses

dashboards/grafana-dashboard-insights-inventory-general.configmap.yaml
This PR is being created to address [RHINENG-5450](https://issues.redhat.com/browse/RHINENG-5450).
The intent of the Message size panel was to see the the maximum size of the consumed/produced messages, so one more change was made to the query.
=> fix(RHINENG-5450): Change intent of grafana dashboard

app/__init__.py, app/config.py, deploy/clowdapp.yml
* Introduce a connection option for the flask API app that sets a statement timeout for the engine
* The default will be 30 seconds as any API request over 30 seconds will receive a gateway timeout
* This value can be set to a negative value to avoid the setting being applied altogether
https://docs.sqlalchemy.org/en/20/core/engines.html#use-the-connect-args-dictionary-parameter
=> Add a default statement timeout for API server queries

api/cache.py, api/host.py, app/queue/queue.py, deploy/clowdapp.yml, host_reaper.py, inv_mq_service.py, lib/host_delete.py
* Add mechanism to remove cached keys by prefix using the org_id prefix
* Add decorator to get/list host APIs
* Add delete keys step to host APIs that alter/delete host data for cache invalidation
* Add delete keys step to MQ processing flow for cache invalidation
* Add delete keys step to host reaper flow for cache invalidation
=> feat(api): Enable caching of host APIs with associated cache invalidation

api/group.py
* Need to invalidate cache on create group API call
=> bugfix(api): Add cache invalidation on create group

app/queue/queue.py
This PR is being created to address [RHINENG-10660](https://issues.redhat.com/browse/RHINENG-10660).
It turns off auto-flush during the MQ batch operation.
=> fix(RHINENG-10660): Turn off autoflush during MQ batch operation

app/payload_tracker/__init__.py, app/queue/queue.py, tests/test_mq_service.py
This PR is being created to address [RHINENG-10773](https://issues.redhat.com/browse/RHINENG-10773).
After the MQ batch update, the request ID was effectively being cached in the produced messages within a batch, which was due to `threadctx.request_id` not being set in the correct places. This PR fixes that, and also simplifies our payload tracker usage a bit (which is related).
For reference, [PR 1778](https://github.com/RedHatInsights/insights-host-inventory/pull/1778) is the change that batched our MQ processing.
=> fix(RHINENG-10773) Fix request ID in produced message headers

api/filtering/db_custom_filters.py, tests/helpers/test_utils.py, tests/test_api_hosts_get.py
This PR is being created to address [RHINENG-10790](https://issues.redhat.com/browse/RHINENG-10790).
The Postgres implementation currently breaks when filtering by multiple operating systems. This was caused by the conditions inside the OS filtering code to not be grouped together. This fixes the issue and adds a test to make sure that other filters (like org_id and host_type) do not get ignored.
=> fix(RHINENG-10790) Fix filtering by multiple operating_system values

app/config.py, deploy/clowdapp.yml
* Define nginx config file and proxy in clowdapp.yml
* Define a reads and writes API service
* Mount the read only db connection secret to the reads service
* Update the clowder config flow to connect to the read replica DB if enabled and connection data is present
=> feat(api): split read traffic to read replica db using nginx proxy

api/filtering/db_custom_filters.py, api/filtering/filtering_common.py, tests/test_api_hosts_get.py
This PR is being created to address [RHINENG-10816](https://issues.redhat.com/browse/RHINENG-10816).
It enables the use of "nil" and "not_nil" values on the operating_system system profile filter. For instance, these work:
- `?filter[system_profile][operating_system]=nil`
- `?filter[system_profile][operating_system][]=nil`
- `?filter[system_profile][operating_system][]=nil&filter[system_profile][operating_system][]=not_nil`
Note that you cannot combine a nil/not_nil filter with a filter on a specific OS version due to a technical limitation (the deep-object query param structure). So queries like this will not work:
- `?filter[system_profile][operating_system][]=nil&filter[system_profile][operating_system][RHEL][version][gt][]=8` …
=> fix(RHINENG-10816) Handle nil/not_nil values for operating_system filter

api/cache.py
* Key off the cache config cache type value to call the correct deletion mechanism.
Used local flow to test MQ deletes that caused previous issue.
Added the following the the compose file:
```
redis:
image: redis:latest
restart: always
ports:
- "6379:6379"
volumes:
- ./cache:/root/redis
environment:
- REDIS_PORT=6379
- REDIS_DATABASES=2
```
Added the following to the environment:
```
INVENTORY_API_CACHE_TIMEOUT_SECONDS=30
INVENTORY_API_CACHE_TYPE="RedisCache"
```
Run the following to populate the Cache:
```
make run_inv_web_service reload=--reload
```
And hit a cached endpoint with curl or Postman
```
curl --location 'http://localhost:8080/api/inventory/v1/hosts/' \
--header 'x-rh-identity: eyJpZGVudGl0eSI6eyJvcmdfaWQiOiI1ODk0MzAwIiwidHlwZSI6IlVzZXIiLCJhdXRoX3R5cGUiOiJiYXNpYy1hdXRoIiwidXNl …
```
=> bugfix(api): Correct delete_keys flow using CACHE_CONFIG type

api/group.py, api/host.py, api/staleness.py, lib/middleware.py
This PR is being created to address [RHINENG-10859](https://issues.redhat.com/browse/RHINENG-10859).
* Create a decorator that process the response of API calls and validates that it only contains data for the current org
* Apply decorator to APIs
=> feat(rhineng-10859): Add decorator to ensure org_id integrity

tests/helpers/sql_dump.py
A utility to dump formatted SQL statements within tests. It hooks into SQLAlchemy events, so there's no need to isolate the query in the code so it can be printed.
Simple use case, within your test code:
```python
from tests.helpers.sql_dump import SQLDump
: 
: 
with SQLDump():
assert_host_exists_in_db(created_host.id, subset_canonical_facts)
```
All the SQL that is executed as the result of the `assert_host_exists_in_db()` call will be dumped, along with a formatted list of parameters.
There's also a decorator that makes it easy to dump all the SQL executed by a given function:
```python
from tests.helpers.sql_dump import dumps_sql
:
:
@dumps_sql
def test_find_host_using_superset_canonical_fact_match(db_create_host):
```
Will dump all the SQL executed by the …
=> Added SQL dump facility to aid in testing, debugging and reviewing.

api/host_group.py
* Update host_group.py to call delete keys for these two APIs that were missed.
=> bugfix(api): Invalidate cache on add and remove hosts from groups

app/queue/notifications.py
This PR is being created to address [RHINENG-10853](https://issues.redhat.com/browse/RHINENG-10853).
I broke down [RHINENG-7833](https://issues.redhat.com/browse/RHINENG-7833) into 2 sub-tasks to make everyone's life easier, so this is the first one, addressing just the creation of the notification without the code to send it.
=> feat(RHINENG-10853): creates structure for the stale host notification

api/cache_key.py
This PR is being created to address [RHINENG-10815](https://issues.redhat.com/browse/RHINENG-10815).
* Add a fix to collect and hash all request args avoiding them being flatten if a key has multiple values
I found the following [blog](https://www.geeksforgeeks.org/multi-value-query-parameters-with-flask/) that lead me to the fix, which called out the following that the original code didn't do:
```
request.args.to_dict(flat=False)
```
=> bugfix(rhineng-10815): Fix make_key to avoid args being flattened causing cache collisions

Makefile, README.md
This PR adds a new Makefile entry to run the `inv_export_service.py` script.
This PR is being created to address [RHINENG-11403](https://issues.redhat.com/browse/RHINENG-11403).
=> [RHINENG-11403] Create a new Makefile entry to run the inv_export_service.py

swagger/api.spec.yaml, swagger/openapi.dev.json, swagger/openapi.json
This PR is being created to address [RHINENG-9245](https://issues.redhat.com/browse/RHINENG-9245).
Fix API doc with correct permissions for the staleness resources
=> fix(RHINENG-9245): Fix API doc permissions for staleness

app/config.py, deploy/clowdapp.yml, tests/helpers/api_utils.py, tests/test_api_hosts_get.py, tests/test_unit.py
This PR is being created to address [RHINENG-11457](https://issues.redhat.com/browse/RHINENG-11457).
The Connexion & Flask upgrade in PR #1822 broke the legacy API. It turns out this was due to how trailing slashes are handled in the framework; removing the trailing slash from the API path fixed the issue.
I also added a test to make sure the basic `GET /hosts` request works on both the new and legacy endpoints.
=> fix(RHINENG-11457): Correct legacy API path

api/cache.py, api/cache_key.py, api/group.py, api/host.py, api/host_group.py, api/staleness.py, app/queue/queue.py, app/serialization.py
* Define key deletion types and abstract them out
* Add cached system key deletion to group and staleness flows
* Define method for cached system key
* Add cache opportunity on cached system miss
You can reuse testing instructions from here: https://github.com/RedHatInsights/insights-host-inventory/pull/1841
However now if you alter staleness or groups in the org cached systems will be removed. 
=> feat(api): Invalidate cached systems in groups and staleness apis

deploy/clowdapp.yml
* Enable an empty metrics endpoint instead of pass through to the read services
This PR is related to: https://github.com/RedHatInsights/insights-host-inventory/pull/1815
=> bugfix(metrics): revert nginx metrics pass through

api/group.py, api/host.py, api/staleness.py, app/__init__.py, app/queue/queue.py, lib/check_org.py, lib/middleware.py
* Use Flask's after_request feature to perform the check_org_id check on defined endpoints
* Remove decorator that didn't execute when caching was performed
=> feat(api): Ensure org_id checking including cached responses

app/models.py, tests/test_models.py
This PR is being created to address [RHINENG-11698](https://issues.redhat.com/browse/RHINENG-11698).
It appears that some reporters are sending  00:00:00:00:00:00 as one of the reported mac_addresses in the canonical facts. It also seems there are instances where this value is the only reported mac address. Given this is not a unique value, this can lead to duplication issues.
The CanonicalFactsSchema has been updated to check for this. In all cases, the offending reporter is logged, so it can be identified and fixed. The values are removed when they are received, so they won't be saved to the database.
=> Detect and filter zero mac addresses in canonical facts.

api/host_query_xjoin.py, tests/test_xjoin.py
This PR is being created to address [RHINENG-11882](https://issues.redhat.com/browse/RHINENG-11882).
It coerces a map to type `list`, which is needed in python 3. It also updates exception handling and a unit test.
=> fix(RHINENG-11882): Convert map to list in xjoin implementation

app/queue/events.py, app/queue/notifications.py, app/queue/queue.py, app/serialization.py, tests/fixtures/mq_fixtures.py, tests/helpers/mq_utils.py, tests/helpers/test_utils.py, tests/test_deduplication.py, tests/test_duplicate_hosts.py, tests/test_mq_service.py, tests/test_notifications.py, tests/test_unit.py
This PR is being created to address [RHINENG-7840](https://issues.redhat.com/browse/RHINENG-7840).
- add the logic necessary to send the notifications for newly registered hosts.
- add a few changes to `notifications.py` that will be overwritten by the [refactoring PR](https://github.com/RedHatInsights/insights-host-inventory/pull/1825)
=> feat(RHINENG-7840): add logic to newly registered system notifications

deploy/clowdapp.yml
This PR is being created to address [RHINENG-12085](https://issues.redhat.com/browse/RHINENG-12085).
* Add environment variables to allow tweaking of probe timeouts
=> bugfix(rhineng-12085): Enable variable alteration of probe timeouts on API pods

api/group.py, api/host.py, api/host_group.py, api/staleness.py, lib/group_repository.py
This PR is being created to address [RHINENG-12147](https://issues.redhat.com/browse/RHINENG-12147).
* Optimize cache key deletion to avoid search and delete cases
* Allow thread spawning for staleness APIs
=> bugfix(rhineng-12147): Perform finer grain key deletions from cache

deploy/clowdapp.yml
The `restartPolicy` is currently placed under the `podSpec` but it should be under the job at the same level as `podSpec`, see here: 
https://github.com/RedHatInsights/clowder/blob/master/apis/cloud.redhat.com/v1alpha1/clowdapp_types.go#L108
The `restartPolicy` was added 2 years ago but @thearifismail was running into an issue deploying this template to minikube:
```
error: error validating "host-inventory.yaml": error validating data: [
ValidationError(ClowdApp.spec.jobs[0].podSpec): unknown field "restartPolicy" in com.redhat.cloud.v1alpha1.ClowdApp.spec.jobs.podSpec, 
ValidationError(ClowdApp.spec.jobs[1].podSpec): unknown field "restartPolicy" in com.redhat.cloud.v1alpha1.ClowdApp.spec.jobs.podSpec, 
ValidationError(ClowdApp.spec.jobs[2].podSpec): unknown field "restartPolicy" in …
```
=> Move restartPolicy to correct location

api/host.py, app/queue/queue.py, lib/group_repository.py
This PR is being created to address [RHINENG-12147](https://issues.redhat.com/browse/RHINENG-12147).
* Add guards for systems without owner_id
* Move code from the produce events code as requested
=> bugfix(rhineng-12147): Handle systems without owner_id to avoid spurious wildcard deletion

.unleash/flags.json, api/staleness.py, lib/feature_flags.py
This PR is being created to address [RHINENG-10515](https://issues.redhat.com/browse/RHINENG-10515).
It removes the usage of custom staleness feature flag from HBI backend
=> feat(RHINENG-10515): remove custom staleness feature flag

app/queue/queue.py
This PR is being created to address [RHINENG-12407](https://issues.redhat.com/browse/RHINENG-12407).
It fixes the batch MQ logging issue. The logger automatically pulls its org_id and account from threadctx, so even though these fields were correct on the logged host, they weren't correct on the top level of the log. This is fixed by setting the org_id and account on threadctx each time we produce an add/update message.
The reason I don't pass org_id and account to `initialize_thread_local_storage` during `handle_message` is that the incoming message hasn't been loaded in yet.
=> fix(RHINENG-12407) Add org_id and account to threadctx, if available

api/filtering/db_filters.py, api/host_query_db.py
This PR is being created to address [RHINENG-12047](https://issues.redhat.com/browse/RHINENG-12047).
Turns off counting within `paginate()`, and does the count query separately. This results in a simpler and more efficient query used for counting, which should improve DB performance. This change necessitated the removal of some "GROUP BY" statements, so here are examples of the differences in the queries:
```
SELECT count(*) AS count_1 
FROM (SELECT hosts.canonical_facts AS hosts_canonical_facts, hosts.id AS hosts_id, hosts.account AS hosts_account, hosts.org_id AS hosts_org_id, hosts.display_name AS hosts_display_name, hosts.ansible_host AS hosts_ansible_host, hosts.facts AS hosts_facts, hosts.reporter AS hosts_reporter, hosts.per_reporter_staleness AS hosts_per_reporter_staleness, …
```
=> perf(RHINENG-12047): Improve host-counting efficiency

swagger/api.spec.yaml, swagger/openapi.dev.json, swagger/openapi.json
This PR is being created to put the GET /host_exists endpoint inside the `hosts` group in the API docs.
=> Put the host_exists endpoint in the "hosts" APIdocs group

api/system_profile.py
This PR is being created to follow up #1922. It removes the `_db` import aliases in `system_profile.py`, since we no longer have to distinguish between the xjoin and DB integration.
=> Remove db import aliases

deploy/testing-integration.yml
After the plugin rename I did in https://github.com/RedHatInsights/insights-host-inventory/pull/1923 the integration test pipeline is failing. After asking around looks like I was missing a argument for the container. In this PR I add that parameter.
=> Add IQE_IMAGE_TAG parameter to integration testing image

app/queue/export_service_mq.py, app/queue/host_mq.py, app/queue/mq_common.py, inv_export_service.py, inv_mq_service.py, lib/host_delete.py, lib/system_profile_validate.py, rebuild_events_topic.py, tests/fixtures/mq_fixtures.py, tests/test_export_service.py, tests/test_host_mq_service.py
This PR is being created to address [RHINENG-10672](https://issues.redhat.com/browse/RHINENG-10672).
It split the export service MQ and host MQ services into their files. Also create a common mq file to hold the common code used between both services. It also updates the tests required tests.
Creates the following files:
- host_mq.py
- export_service_mq.py
- mq_common.py
=> refact(RHINENG-10672): Refact app/queue/queue.py

api/filtering/db_custom_filters.py, tests/test_api_hosts_get.py
This PR is being created to address [RHINENG-12591](https://issues.redhat.com/browse/RHINENG-12591).
It improves the "invalid filter field" error message by making it clearer and adding more context. 
For the example request "GET /hosts?filter[system_profile][owner_id][not_eq]=123"...
- Before: "invalid filter field: not_eq"
- After: "Invalid operation or child node for owner_id: not_eq"
=> fix(RHINENG-12591): Fix message for unsupported filter field/operation

api/filtering/db_custom_filters.py, tests/test_api_hosts_get.py
This PR is being created to address [RHINENG-11200](https://issues.redhat.com/browse/RHINENG-11200).
Prior to this change, we adequately handled `?filter[system_profile][host_type]=` (with no value), but `?filter[system_profile][host_type][eq]=` resulted in HTTP 500. This PR adds handling for that scenario so it works the same way; it also adds a test case to validate.
=> fix(RHINENG-11200): Handle filtering on [host_type][eq]=

swagger/api.spec.yaml, swagger/openapi.dev.json, swagger/openapi.json
This PR is being created to address [RHINENG-13652](https://issues.redhat.com/browse/RHINENG-13652).
It adds `system_profile` field to `HostOut` object in the OpenAPI spec
=> fix(RHINENG-13652): Add system profile field to HostOut

lib/middleware.py
Currently, if you try to run the unit tests for one specific file or test suite, it will fail due to an initialization failure of a Prometheus metric within `middleware.py`. This PR moves the metric definition within the RBAC function, which gets bypassed during tests.
=> fix: Define RBAC metric inside RBAC call

app/instrumentation.py, app/queue/host_mq.py
This PR is being created to address [RHINENG-13858](https://issues.redhat.com/browse/RHINENG-13858).
It moves some things around so that we can have the request ID along with the message partition & offset in the same log. In order to do this, we unfortunately need to decode the message twice; the alternative would be to restructure `handle_message` to accept a raw MQ message rather than its value.
If you all think it's worth changing all that for the sake of this log, let me know and I can do so.
=> fix(RHINENG-13858): Fix request_id in "host message consumed" log

tests/test_custom_staleness.py, tests/test_export_service.py
This PR is being created to address [RHINENG-3408](https://issues.redhat.com/browse/RHINENG-3408).
It removes calls to `sleep()` within our unit tests and replaces them with datetime mocks. This will speed up our unit test runs by at least 5 seconds.
=> chore(RHINENG-3408): Replace calls to sleep()

app/instrumentation.py, app/queue/host_mq.py
This PR is being created to remove the "Host message consumed" log. This log was useful in one specific instance, but has also misled some folks and guided them to the wrong conclusion. So, unless we really need this log, I think we should remove it.
=> Remove "Host message consumed" log

README.md, app/config.py, app/instrumentation.py, app/queue/host_mq.py, lib/host_delete.py, logconfig.yaml, tests/test_api_hosts_delete.py, tests/test_host_mq_service.py, utils/system_profile_log.py
This PR is being created to address [RHINENG-13314](https://issues.redhat.com/browse/RHINENG-13314).
It implements the new env var called `SP_FIELDS_TO_LOG`, that is used to print the specified system profile fields in our logs. The logs were added to: add host, update host and delete host methods.
=> feat(RHINENG-13314): Log specific SP fields defined in env config

.pre-commit-config.yaml, swagger/redocly.yml
This PR is being created to address a pre-commit redocly issue. For some reason redocly started interpreting the paths in the redocly.yml config as relative paths (I guess it's the right way, but it probably interpreted them as full paths from the project root in the past), so when we had `swagger/openapi.dev.json` there it was trying to find `swagger/swagger/openapi.dev.json` file, which didn't exist. This PR should fix the issue.
I verified that the paths are correct now by commenting out `- api.assignment_rule.get_assignment_rules_by_id` from the redocly config and running pre-commit. It correctly recognized the change and copied the endpoint from the `openapi.dev.json` to the `openapi.json`. When I uncommented that line, it correctly removed it from the `openapi.json` again.
You can …
=> Fix redocly by using relative paths

app/queue/export_service.py, tests/helpers/api_utils.py, tests/helpers/export_service_utils.py, tests/test_export_service.py
This PR is being created to address [RHINENG-15180](https://issues.redhat.com/browse/RHINENG-15180).
Encodes export_service's POST requests in utf-8 and sets the charset header accordingly. Also makes a try/catch more specific so we can more easily detect this kind of error in the future - it used to just broadly catch all Exceptions and handle them the same way, so the UnicodeEncodeError went undetected.
=> fix(RHINENG-15180): Fix CSV data export with unicode chars

app/serialization.py, lib/staleness.py
This PR is being created to address [RHINENG-12028](https://issues.redhat.com/browse/RHINENG-12028).
See my comment with all the explanations about this refactoring and improvements that can be done, in the Jira ticket above or in the commit message.
=> (RHINENG-12028): serialize_host refactoring

api/host_query_db.py, app/exceptions.py, app/queue/export_service.py, tests/test_export_service.py, tests/test_host_mq_service.py
This PR is being created to address [RHINENG-15555](https://issues.redhat.com/browse/RHINENG-15555).
When we initiated an export and then deleted a host, the export would never finish and the status would say that it is "pending" forever. I found out that there were 2 reasons why this was happening:
- When we delete a host while fetching them for export, SQLAlchemy raises a `DeletedObjectError`. We didn't catch the DB errors when fetching hosts for export, so when the DB error occurred, we didn't send the failure status to the export service. I'm fixing this by catching the DB errors in `get_hosts_to_export` function and raising `InventoryException`, which is caught and correctly handled by `create_export` function. I also added a unit test for this.
- Recently we switched from …
=> fix(RHINENG-15555): Fix infinite export when a host is deleted

lib/middleware.py, tests/test_api_groups_create.py, tests/test_api_groups_delete.py, tests/test_api_hosts_delete.py
This PR is being created to address [RHINENG-15829](https://issues.redhat.com/browse/RHINENG-15829).
Restricts write/delete endpoints when API is in read-only mode (i.e. when hbi.api.read-only feature flag is True).
=> feat(RHINENG-15829) Restrict write/delete endpoints in read-only mode

tests/test_api_hosts_delete.py, tests/test_api_hosts_get.py
This PR is being created to address [RHINENG-16248](https://issues.redhat.com/browse/RHINENG-16248).
During the migration from xjoin, we created many tests whose logic was gated on a feature flag. We removed the feature flag references from the code, but did not remove the feature flag mocks from the unit tests. This PR removes the feature flag mocks from the unit tests.
=> chore(RHINENG-16248) Remove obsolete feature flag mocks from tests

app/instrumentation.py, app/queue/host_mq.py
This PR is being created to address [RHINENG-16229](https://issues.redhat.com/browse/RHINENG-16229).
This will help me to identify how many (if any) payloads without subscription_manager_id use basic-auth.
=> Add auth_type to add_host_attempt log

api/host.py, api/host_query_db.py, tests/test_api_hosts_delete.py
This PR is being created to address [RHINENG-16421](https://issues.redhat.com/browse/RHINENG-16421).
Fixes the bulk delete endpoint with respect to the changes to the staleness functions. Passes the current identity through the endpoint, and uses its org_id in the staleness functions. Also adds a test to make sure that scenario is covered.
Fixes an issue introduced in #2332.
=> fix(RHINENG-16421) Fix bulk delete endpoint

deploy/clowdapp.yml
This PR is being created to address [RHINENG-16675](https://issues.redhat.com/browse/RHINENG-16675).
Add `CONSOLEDOT_HOSTNAME` to stale-host-notification Clowdapp
=> fix(RHINENG-16675): Add CONSOLEDOT_HOSTNAME to stale-host-nofitication app

app/models.py, app/utils.py, tests/test_host_mq_service.py, tests/test_models.py
This PR is being created to address [RHINENG-15447](https://issues.redhat.com/browse/RHINENG-15447).
- Changes the logic of `_replace_tags_in_namespace()` to account for different numbers of items to update
=> fix(RHINENG-15447): improve replace_tags_alt logic

api/filtering/db_filters.py, lib/host_repository.py, lib/middleware.py, tests/test_api_hosts_get.py, tests/test_api_hosts_update.py, tests/test_rbac.py
This PR is being created to address [RHINENG-16842](https://issues.redhat.com/browse/RHINENG-16842).
In order for HBI to work in read-only mode during the Kessel Phase 0 migration, we need to allow the None attributeFilter value from RBAC to not only allow access to ungrouped hosts, but also hosts that are in the "ungrouped" group. This will allow the API to continue working as expected in-between HBI's data migration and RBAC's data migration.
Also, mgmt-fabric doesn't necessarily need to remove the None attributeFilter values during migration, and it may exist afterwards. Because of this, I'm removing the code that restricted the None value post-migration.
=> feat(RHINENG-16842) Include hosts in "ungrouped" group when filtering on group=None

app/__init__.py, app/config.py, app/models.py, lib/host_repository.py, tests/fixtures/mq_fixtures.py, tests/test_host_mq_service.py
This PR is being created to address [RHINENG-16293](https://issues.redhat.com/browse/RHINENG-16293).
* Added a configuration variable controlled by an ENV var; defaults to false
* Added a flow for setting the Host model's id to the subscription manager id if its present and the configuration value is set
* Updated find existing host flow to only use subscription manager id as the elevated id in the case where the USE_SUBMAN_ID variable is True
=> feat(rhineng-16293): Enable deployments where host uuid needs to be the subscription manager ID

api/host_query_db.py, swagger/api.spec.yaml, swagger/openapi.json, tests/test_api_hosts_get.py
OBS: PR #2310 must be merged first.
This PR is being created to address [RHINENG-15654](https://issues.redhat.com/browse/RHINENG-15654).
- Update OpenAPI spec
- Add sorting by `last_check_in` 
Functionality is enabled when using feature flag: `hbi.create_last_check_in_update_per_reporter_staleness` 
=> feat(RHINENG-15654): Add last_check_in timestamp to the hosts response

deploy/clowdapp.yml
This commit adds two new floorist queries to get daily created/updated hosts by reporters. So far, we've had weekly metrics data which is not very helpful for the hbi_metrics CLI.
This PR addresses the Jira Card RHINENG-17020.
This PR is being created to address [RHINENG-17020](https://issues.redhat.com/browse/RHINENG-17020).
=> Floorist: Add two new floorist queries

deploy/clowdapp.yml
This PR increases the chunksize (defaulted to 1000) for the heaviest SQL queries. The purpose of this change is to reduce our floorist job execution time and/or figure out the best configuration.
It also pauses the query gathering hosts.
This PR is being created to address [RHINENG-8904](https://issues.redhat.com/browse/RHINENG-8904).
=> RHINENG-8904: Increase floorist chunksize

deploy/clowdapp.yml, jobs/update_hosts_last_check_in.py
This PR is being created to address [RHINENG-15654](https://issues.redhat.com/browse/RHINENG-15654).
It creates a OCP cronjob to update Host last_check_in field.
By default it limits the update size to 50000 hosts each run.
The job runs hourly by default
=> feat: Add job to update last_check_in field in the DB

deploy/clowdapp.yml, jobs/update_hosts_last_check_in.py
It addes `PYTHONPATH` ENV var to all jobs that are under `jobs/*` folder.
This is required because `PYTHONPATH` is not being initialized for the Clowdapp jobs.
=> chore: add python path

jobs/update_hosts_last_check_in.py
This PR is being created to address [RHINENG-15654](https://issues.redhat.com/browse/RHINENG-15654).
Linter complained about `Host.last_check_in == None` and suggested `Host.last_check_in is None`, but this won't with SQLAlchemy. 
`text()` method was receiving 2 parameters, and it only expect one (a string).
This is now fixed.
=> fix: Fix SQL query to make job to work properly

lib/group_repository.py
- The passed workspace_id is a UUID, so it needs to be cast to a string.
- `notify.payload` is already a string, so both values are cast to strings to ensure a reliable comparison.
=> Fix: Ensure consistent string comparison for workspace ID in notification payload

api/group.py, app/config.py, deploy/clowdapp.yml, lib/group_repository.py, lib/middleware.py, logconfig.yaml, tests/fixtures/api_fixtures.py, tests/test_host_mq_service.py
This PR is being created to address [RHINENG-15822](https://issues.redhat.com/browse/RHINENG-15822).
An issue arose with the original approach because it attempted to pass in the existing request headers to the RBAC call. This would not work when called from an MQ context. This PR addresses this by making it so the original headers are only used when coming from an API context; when coming from MQ, it uses the identity from the payload for the outgoing header.
=> fix(RHINENG-15822) Fix context issue for host-mq RBAC call

Dockerfile, Dockerfile.upstream
Adding the copy of the new makefiles forgotten in https://github.com/RedHatInsights/insights-host-inventory/pull/2871
=> build: Include the makefiles in the Image
